### ISSUE TITLE
For all Windows versions ?

### ISSUE THREAD

**Issue by zymase** [crazy-max/WindowsSpyBlocker#1]
Hi,

Sorry to use the issue section when I wish only to know if this very nice and complete _WindowsSpyBlocker_, if its rules concern only Windows 10 or if they are applicable, pertinent to all Windows versions, even if some rules may concern only Windows 10.

I've added hostsBlockWindowsSpy.txt to my HostsMan's sources and installed the outbound rules for Windows' Firewall. I guess it can't do no harm... in fact I believe it already does a lot of good!

Windows 7SP1 x-64 here.

Thanks.

**Comment by crazy-max** [comment]
Hi,

For the moment these rules concern only Windows 10 because my Wireshark instance is on a virtual machine on Windows 10 Pro 64bits.
But it's possible to create another instance on Windows 7 / 8 virtual machine but not for now.

And it's not a problem to post a question! ;)

**Comment by zymase** [comment]
OK. 
I'm keeping nevertheless the hostsBlockWindowsSpy.txt as a source for HostsMan, considering spies here may concern all Windows versions,
I'm removing the Firewall rules,
I hadn't installed the Proxifier.

Thanks- Of course if Windows 10 spying is CheckPointCharly, Windows 7 itself has a touch of Vienna ;)

**Comment by crazy-max** [comment]
Good point ;)

**Comment by crazy-max** [comment]
The next release will introduce win7, win8 and maybe winxp rules

**Comment by crazy-max** [comment]
Win 7 and Win 8.1 were added on 3.1
