### ISSUE TITLE
Windows added you to block list

### ISSUE THREAD

**Issue by Tmp341** [crazy-max/WindowsSpyBlocker#100]
Here it is:

![untitled-2](https://user-images.githubusercontent.com/1683388/36070801-daca02ba-0f13-11e8-98e1-34fd92236f7b.jpg)

All the blurred parts are in Turkish. They aren't needed, they say "threat is serious" i should consider taking action etc.

**Comment by crazy-max** [comment]
Hi @Tmp341, we already talked about this in #82 and [FAQ](https://github.com/crazy-max/WindowsSpyBlocker/wiki/miscFAQ#antivirus-complains-about-windowsspyblocker). I have sent the exe to Microsoft and everything is fine :

![image](https://user-images.githubusercontent.com/1951866/36074138-1edf2f20-0f3c-11e8-8b0d-dad8db7fbd80.png)

If you encounter this issue next time, you can send the file for analysis to Micrososft : https://www.microsoft.com/en-us/wdsi/filesubmission

**Comment by Tmp341** [comment]
I know it is a false positive. Opened this just to notify you. My bad, i should have checked faq.

**Comment by crazy-max** [comment]
No problem, thanks for your input
