### ISSUE TITLE
131.253.34.230 not in Telemetry list, but in Third Party list?

### ISSUE THREAD

**Issue by loxia01** [crazy-max/WindowsSpyBlocker#101]
First of all I want to thank you for this project, I use it through WPD and are very grateful for its usability.

But some improvements could perhaps be made to move some ip addresses from Third Party list to Telemetry List. I have done some testing from my Win10 Home system (basic telemetry setting) with Glasswire and Windows Firewall logging.

I was surprised to see how often my system tries to connect to 131.253.34.230 (bn2wns1.wns.windows.com). For example every time I open/close an application (even Tor Browser) and every time I connect/disconnect to a VPN service.  Wouldn't this qualify to list 131.253.34.230 in the Telemetry list instead of Third Party list? Also IP address range 204.79.197.000-255 is frequently contacted at these events.

If moved to Telemetry list, the advantage will be you are able to use just the Telemetry block list, not needing to use the Third Party block list. The Third Party list blocks for example Windows Time service, Outlook.com and some other services which some people might find useful.

**Comment by Atavic** [comment]
Technet Microsoft support:
 
>If you disable OneDrive both from the metro control panel and via local/group policy, then this persistent connection goes away.

Instructions to disable via (local) Group Policy:

`Start > Run > gpedit.msc`

Computer Configuration\Administrative Templates\Windows Components\OneDrive
Prevent the usage of OneDrive for file storage = Enabled

Related: https://github.com/WindowsLies/BlockWindows/issues/22

**Comment by loxia01** [comment]
Ok,

thank you! Sorry for posting before checking this.




17. Feb 2018 22:46 by notifications@github.com:

**Comment by crazy-max** [comment]
Hi @loxia01,

You're right, `131.253.34.230` and `204.79.197.1/24` should be in the spy list. Moreover, these ips reflect the domain names already present in the spy list. This will be available in the next release.

Thanks for your support

**Comment by loxia01** [comment]
Update: Did some more testing and connection attempts to 131.253.34.230 ended when stopping Windows service WpnService (Windows Push Notification). Disabling OneDrive alone had no effect.

**Comment by crazy-max** [comment]
This has been solved in the latest release (4.11.0)
