### ISSUE TITLE
Hostsman

### ISSUE THREAD

**Issue by Noruas29** [crazy-max/WindowsSpyBlocker#103]
Boujour, jusqu'à présent j'utilisais ce type de liens dans Hostsman pour ajouter les listes à mon hosts:
http://www.crazyws.fr/WindowsSpyBlocker/hosts/win81/spy.txt
car les liens directs via github ne fonctionnent pas. Or ces liens ne fonctionnent plus non plus depuis quelques jours, comment y remédier ou quels sont les adresses viables que l'on peut ajouter dans Hostsman ?

**Comment by huwtf** [comment]
Yes, the hosts files are dead and nowhere to be found.  When I try to update with Hostsman it says all 3 host servers are 404 not found.

**Comment by Atavic** [comment]
Data hosts is here:
https://github.com/crazy-max/WindowsSpyBlocker/tree/master/data/hosts

**Comment by huwtf** [comment]
I made 3 sources on Hostsman but get 1... check failed (error code: 200).,
are these the correct paths for the sources?

https://github.com/crazy-max/WindowsSpyBlocker/blob/master/data/hosts/win7/spy.txt

https://github.com/crazy-max/WindowsSpyBlocker/blob/master/data/hosts/win7/extra.txt

https://github.com/crazy-max/WindowsSpyBlocker/blob/master/data/hosts/win7/update.txt

**Comment by Atavic** [comment]
Try these ones:

https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/win7/spy.txt
https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/win7/extra.txt
https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/win7/update.txt

**Comment by huwtf** [comment]
Thank you

**Comment by Atavic** [comment]
@Noruas29 Issue been solved, please close it.

**Comment by crazy-max** [comment]
HostMan does not work on https unfortunately.

**Comment by huwtf** [comment]
Makes sense thanks

**Comment by dartsmaster** [comment]
Hostsman does not work with GitHub sources unfortunately. This is why is was very useful to have http://www.crazyws.fr as a source for the hosts files. Are these sources likely to return?

**Comment by Atavic** [comment]
Maybe you can get the files first, then add them locally to hostsman.

**Comment by crazy-max** [comment]
I will put these files on an other server. I keep you in touch.

**Comment by dartsmaster** [comment]
Thanks @crazy-max , much appreciated :-)

**Comment by huwtf** [comment]
can anyone else host the files and post them here?

**Comment by crazy-max** [comment]
I put the files on another subdomain and updated the wiki page : https://github.com/crazy-max/WindowsSpyBlocker/wiki/dataHosts

**Comment by ts-ts** [comment]
>I put the files on another subdomain

where?

**Comment by crazy-max** [comment]
@ts-ts Hosts files are no longer available on this website. I will set up a hook to publish hosts files on pastebin through their API. Keep you in touch.

**Comment by ts-ts** [comment]
Thank you for your comment.
When is it?
