### ISSUE TITLE
Dev, have you looked at MS Docs?

### ISSUE THREAD

**Issue by Atavic** [crazy-max/WindowsSpyBlocker#104]
From another [issue](https://github.com/MrAlex94/Waterfox/issues/460#issuecomment-372155064) I saw an URL that appears in your CSV Lists. MS Docs have a list of domains, specific for different Windows versions, I pasted them [here](https://gist.github.com/Atavic/c6413717d9c9798e2cd906e68d937361). That gist is for Home, Pro and Edu... the Enterprise list isn't there.

**Comment by Atavic** [comment]
MS Source: https://docs.microsoft.com/en-us/windows/configuration/manage-windows-endpoints-version-1709

**Comment by crazy-max** [comment]
Hi @Atavic !

Thanks! I will use these enpoints in the next release
