### ISSUE TITLE
Windows 10 connection endpoints documents (actualized) (info)

### ISSUE THREAD

**Issue by Ainatar** [crazy-max/WindowsSpyBlocker#114]
Hi. As stated in [this thread](https://github.com/crazy-max/WindowsSpyBlocker/issues/104), Microsoft released new documents and actualized the existent ones. Urls to check out:

[https://docs.microsoft.com/en-us/windows/privacy/manage-windows-endpoints](https://docs.microsoft.com/en-us/windows/privacy/manage-windows-endpoints)
[https://docs.microsoft.com/en-us/windows/privacy/windows-endpoints-1709-non-enterprise-editions](https://docs.microsoft.com/en-us/windows/privacy/windows-endpoints-1709-non-enterprise-editions)
[https://docs.microsoft.com/en-us/windows/privacy/windows-endpoints-1803-non-enterprise-editions](https://docs.microsoft.com/en-us/windows/privacy/windows-endpoints-1803-non-enterprise-editions)

Keep the good work! :D

**Comment by crazy-max** [comment]
Hi @Ainatar, thanks for your input i will add this [to the wiki](https://github.com/crazy-max/WindowsSpyBlocker/wiki/miscTelemetry) and opt-in the endpoints for the next release
