### ISSUE TITLE
False positiv: i1.services.social.microsoft.com

### ISSUE THREAD

**Issue by beerisgood** [crazy-max/WindowsSpyBlocker#116]
If you block it, you got no CSS on https://msdn.microsoft.com/

Its included in https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt

**Comment by crazy-max** [comment]
@beerisgood Thanks, I'll dig that up.

**Comment by crazy-max** [comment]
You right, this domain is linked to MSDN, ASP.net CDN and some 3rd party services like segment-pixel.
Will be moved to extra rules in the next release.

**Comment by crazy-max** [comment]
Solved in 4.16.1
