### ISSUE TITLE
DNSCrypt rules lack of IPs

### ISSUE THREAD

**Issue by dimqua** [crazy-max/WindowsSpyBlocker#118]
Is it intentional or not? FYI, dnscrypt-proxy [supports](https://github.com/jedisct1/dnscrypt-proxy/wiki/Filters) both IPv4 and IPv6 addresses as well as prefixes such as `204.79.197.*`.

**Comment by zeffy** [comment]
I can't say if it is intentional or not, but you're probably better off using a firewall to block the IPs regardless, as using DNScrypt will only block DNS name queries that resolve to those IPs, and won't block anything if they are connected to directly, bypassing DNS.

**Comment by crazy-max** [comment]
Like @zeffy said, DNS is bypassed anyway. Use a firewall instead.
