### ISSUE TITLE
Windows LTSC 2019 Extra Rules block Windows Update

### ISSUE THREAD

**Issue by b350** [crazy-max/WindowsSpyBlocker#119]
![error](https://user-images.githubusercontent.com/43731239/46449826-c04b9200-c796-11e8-8bc8-a7442bdc1817.JPG)

**Comment by crazy-max** [comment]
Hi @b350,

Hosts or Firewall rules ?

And please read the [SUPPORT](https://github.com/crazy-max/WindowsSpyBlocker/blob/master/.github/SUPPORT.md) page before reporting an issue.

Thanks

**Comment by anthony-wh** [comment]
Hi,

I can confirm this, extra firewall rules on new windows update (i.e. 1809) block Windows Update.

**Comment by crazy-max** [comment]
Can you try to remove IPs `65.52.108.*` and try again ?

**Comment by anthony-wh** [comment]
tried, did not help

**Comment by crazy-max** [comment]
@anthony-wh Ok I think I have catched the culprits : `40.77.224, 65.52.108, 191.232.139.2`

**Comment by crazy-max** [comment]
Should be solved in 4.17.1
