### ISSUE TITLE
info/question

### ISSUE THREAD

**Issue by dibdot** [crazy-max/WindowsSpyBlocker#12]
Hi,

we're using your list in our openwrt/LEDE based [adblock package](https://github.com/openwrt/packages/tree/master/net/adblock/files). Thanks for your efforts to provide this kind of block list!

Just a small suggestion: Please keep the github link to your list more stable and it would be nice - whenever you add domains for winX - to provide one overall list.

Thanks again!

**Comment by crazy-max** [comment]
Hi,

Like i said to the pi-hole community, this is the final move for the links :)

Thanks for your support!
