### ISSUE TITLE
Beware of KB4462927 update.

### ISSUE THREAD

**Issue by KOLANICH** [crazy-max/WindowsSpyBlocker#121]
Hi. I have found a new update with telemetry.

[KB4462927 - Preview of Monthly Rollup](https://support.microsoft.com/ru-ru/help/4462923/windows-7-update-kb4462923)
>This non-security update includes improvements and fixes that were a part of KB4462923 (released October 9, 2018) and also includes these new quality improvements as a preview of the next Monthly Rollup update:
>Addresses the redenomination of local currency that the Central Bank of Venezuela implemented to enter the Bolivar Soberano into circulation. 
>Addresses an issue that makes it impossible to disable TLS 1.0 and TLS 1.1 when the Federal Information Processing Standard (FIPS) mode is enabled.
>Addresses an issue that causes navigation across eras to stop working in the Japanese Calendar view. For more information, see KB4469068.
>Addresses an issue r elated to the date format for the Japanese era calendar. For more information, see KB4469068.
>Addresses an issue that causes the GetCalendarInfo function to return a wrong value for the Japanese era. For more information, see KB4469068.

As you see, the description looks benign, so does KB4462923's one. But there is telemetry in the update.

* http://download.windowsupdate.com/c/msdownload/update/software/updt/2018/10/windows6.1-kb4462927-x86_ccefd90f830cc37f3d14d9086268b42ade1a5677.msu
* sha256: 78f8bb631690880579200cd1de360830a4c1d6bc82f7330af121ccc7fedb7442
* sha1: ccefd90f830cc37f3d14d9086268b42ade1a5677
* md5: a11f209dc55031e3b9dbbe44287336fa

**Comment by crazy-max** [comment]
Is taken into account in 4.18.1

**Comment by KOLANICH** [comment]
I have done some investigation, it is written that this Monthly Rollup cointains previous one, and in each previous one it is written that it cointains the preceeding one. Fortunately KB page cointains a JS object cointaining some data, and these data cointain kb numbers of a large part of the chain of rollups and there are also links to list of files in each Rollup on its KB page. So I did a binary search and found out that all the Rollup updates after some update I don't remember which number it has cointain telemetry.

So, ones who don't want telemetry have to stay away of Monthly Rollups.
