### ISSUE TITLE
Not working Xbox app

### ISSUE THREAD

**Issue by Agagamand** [crazy-max/WindowsSpyBlocker#124]
I applied this list of rules on the router https://github.com/crazy-max/WindowsSpyBlocker/blob/master/data/hosts/spy.txt and now the Xbox app is not working. The Xbox app is required to run Forza Horizon 3.
https://lh3.googleusercontent.com/-30pSFiQ5nyU/XAEywBIyqFI/AAAAAAACX6A/OadpemzXGa8gEUqdiULbCecsnRonw6ffACHMYCw/s0/ApplicationFrameHost_2018-11-30_14-53-19.png

Operating system: Windows 10, 64 bits, 1809, Enterprise LTSC

**Comment by crazy-max** [comment]
@Agagamand Try to remove the following lines and keep me in touch :

```
0.0.0.0 apac1.notify.windows.com.akadns.net
0.0.0.0 sg2p.wns.windows.com
```

**Comment by Agagamand** [comment]
It did not help.

**Comment by Agagamand** [comment]
Sorry, its my fall. The reason is due to paragraph 10 of this instruction: https://docs.microsoft.com/en-us/windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services
