### ISSUE TITLE
Microsoft Exchange

### ISSUE THREAD

**Issue by CaptainFrosty** [crazy-max/WindowsSpyBlocker#127]
### Behaviour
Not sure if you are aware, but the NCSI settings appear to break access to Microsoft Exchange servers, at least on Outlook 2016.

#### Steps to reproduce this issue

1. Application of NCSI settings (no firewall rules)

### Rules used
Opening key SYSTEM\CurrentControlSet\Services\NlaSvc\Parameters\Internet...OK!
Getting reg value of ActiveWebProbeHost...OK!
Getting reg value of ActiveWebProbePath...OK!
Getting reg value of ActiveWebProbeContent...OK!
Getting reg value of ActiveWebProbeHostV6...OK!
Getting reg value of ActiveWebProbePathV6...OK!
Getting reg value of ActiveWebProbeContentV6...OK!
Getting reg value of ActiveDnsProbeHost...OK!
Getting reg value of ActiveDnsProbeContent...OK!
Getting reg value of ActiveDnsProbeHostV6...OK!
Getting reg value of ActiveDnsProbeContentV6...OK!

### Configuration

**Country (ex. United-States)** :
US

**Operating system (ex. Windows 10 Pro 64 bits)** :
10 Home x64

**Comment by crazy-max** [comment]
Yeah this seems linked to #128

**Comment by Atavic** [comment]
The exact name of Windows NCSI is *Network Connectivity Status Indicator*, see: 
https://blog.superuser.com/2011/05/16/windows-7-network-awareness/

**Comment by crazy-max** [comment]
@CaptainFrosty NCSI configuration seems ok. If Outlook relies on NCSI probes to check connectivity, maybe it compares these probes with hardcoded values inside Outlook. Can you try to [disable NCSI through Group Policy](https://docs.microsoft.com/en-US/windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services#bkmk-ncsi) and tell me if Outlook works ?
