### ISSUE TITLE
Windows 10 1809 and Server 2019 compatible ? 

### ISSUE THREAD

**Issue by F3000** [crazy-max/WindowsSpyBlocker#130]
Hi , 

are Therese version of windows are supported ? 

And what about following when it is possible to block something e.g. IP's) : 

- Office 2016 
- Exchange 2016 
-  SCCM Server

**Comment by crazy-max** [comment]
Yes and Windows Server 2019 is based on the Windows version 1809 codebase. Virtual machine used to collect data is based on Windows 10 1809 (17763.195).

Third-party Microsoft applications (office, etc.) are not installed on this virtual machine at the moment and I do not plan to integrate them for further analysis.

**Comment by F3000** [comment]
ok . Thanks for explaining . 

So how do you get the list of ip's etc ? 

Usa a VM with installed WIn10/Server OS and check with WireShark what he sends to Microsoft or not ?

**Comment by crazy-max** [comment]
Everything is explained in the README :)

**Comment by F3000** [comment]
Ok thanks . 

Would be nice when you can install office in the future  ;)
