### ISSUE TITLE
Blocker list for Pi-Hole 

### ISSUE THREAD

**Issue by F3000** [crazy-max/WindowsSpyBlocker#136]
Hi , 

I found nothing , but can you provide a list that a user can import into his pi-hole installation ?

**Comment by anothernewusername** [comment]
Just take a look in WindowsSpyBlocker/data/hosts/ in github. You can use the raw format and copy the link into your pihole gui like this: https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt

**Comment by 7uppi** [comment]
You are not able to do that, with 0.0.0.0 standing in front of the domains.
Pihole needs a list with just the domain, on each line. Does that exist?

**Comment by dnmTX** [comment]
@7uppi  if Pi-Hole accepts wildcards aka `*.domain.com` you can use [dnscrypt's lists](https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/dnscrypt/spy.txt).Otherwise @crazy-max needs to implement one(if willing 😉 ) or you need to create some small script,i guess on your end to remove the zeroes before you fetch it to Pi-Hole.

**Comment by timmkrause** [comment]
@7uppi Did not check the documentation. But where did you get that Pi-hole does not support the hosts format? Even some of the pre-configured lists which you can enable/add during the setup process do have this format.
I don‘t think they would do that if the format is not supported.

**Comment by 7uppi** [comment]
> 
> 
> @7uppi if Pi-Hole accepts wildcards aka `*.domain.com` you can use [dnscrypt's lists](https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/dnscrypt/spy.txt).Otherwise @crazy-max needs to implement one(if willing 😉 ) or you need to create some small script,i guess on your end to remove the zeroes before you fetch it to Pi-Hole.

Honestly didn't know that Pi-Hole supported wildcards in an adlist. Thank you for the information!
