### ISSUE TITLE
[extra] spy domains to add

### ISSUE THREAD

**Issue by dnmTX** [crazy-max/WindowsSpyBlocker#138]
@crazy-max:  Discovered by reputable fellow [curator](https://github.com/lightswitch05/hosts/commit/f3aac2a5472ab7b45da89c3436247e03dd102b8f).
You can check our conversation at the bottom of the commit. Whenever you can,just add them.Thank you.

`0.0.0.0 events.data.microsoft.com`
`0.0.0.0 browser.events.data.microsoft.com`
`0.0.0.0 eu-v20.events.data.microsoft.com`
`0.0.0.0 mobile.events.data.microsoft.com`
`0.0.0.0 self.events.data.microsoft.com`
`0.0.0.0 umwatsonc.events.data.microsoft.com`
`0.0.0.0 us-v20.events.data.microsoft.com`
`0.0.0.0 v10c.events.data.microsoft.com`

**Comment by crazy-max** [comment]
Hi @dnmTX,

From what I see on my VMS, some of these domain names are already flagged for the next version. Stay tuned for the next release (~6days) and thanks for your contrib!

**Comment by crazy-max** [comment]
Done thanks for your contrib
