### ISSUE TITLE
hosts/win10/spy.txt blocking windows update in Windows 10 Build 160522

### ISSUE THREAD

**Issue by yantis** [crazy-max/WindowsSpyBlocker#14]
hosts/win10/spy.txt

If you REM out this line it works fine otherwise Windows update will be blocked.
0.0.0.0 fe3.delivery.mp.microsoft.com

#### Configuration
- Western United States
- Windows 10 Pro Insider Preview Build 14352

![windows_10_screenshot](https://cloud.githubusercontent.com/assets/4214239/15828069/ba59f4da-2bc2-11e6-9317-e4344ce881f1.PNG)

**Comment by crazy-max** [comment]
Solved on 3.1
Thanks for your support!
