### ISSUE TITLE
cy2.settings.data.microsoft.com.akadns.net & settings.data.microsoft.com

### ISSUE THREAD

**Issue by beerisgood** [crazy-max/WindowsSpyBlocker#140]
cy2.settings.data.microsoft.com.akadns.net is false positive:
The following endpoint is used as a way for apps to dynamically update their configuration. Apps such as System Initiated User Feedback and the Xbox app use it. If you turn off traffic for this endpoint, an app that uses this endpoint may stop working.

https://docs.microsoft.com/en-us/windows/privacy/manage-windows-1809-endpoints

Same for settings.data.microsoft.com

**Comment by crazy-max** [comment]
Done thanks for your contrib
