### ISSUE TITLE
Please add telemetry.remoteapp.windowsazure.com

### ISSUE THREAD

**Issue by lightswitch05** [crazy-max/WindowsSpyBlocker#141]
I installed Microsoft Remote Desktop on my mac today and noticed this new host in my pihole: `telemetry.remoteapp.windowsazure.com`

**Comment by crazy-max** [comment]
Hi @lightswitch05, this domain is used to connect to the apps deployed in the Azure RemoteApp collection. I will add this one to extra rules. Thanks for your input!

**Comment by lightswitch05** [comment]
I understand that `remoteapp.windowsazure.com` would be used for that purpose, but is not `
telemetry.remoteapp.windowsazure.com` purely tracking based?

**Comment by dnmTX** [comment]
@crazy-max i agree with @lightswitch05. Usually if there is a `telemetry.*` present in the domain it's used just for that purpose.

**Comment by crazy-max** [comment]
I'll take a closer look at it. Thanks

**Comment by crazy-max** [comment]
Done thanks for your contrib
