### ISSUE TITLE
Of interest re: DMCA Notice

### ISSUE THREAD

**Issue by ghost** [crazy-max/WindowsSpyBlocker#142]
https://gitlab.com/CHEF-KOCH/cks-filterlist
https://github.com/CHEF-KOCH/CKs-FilterList-Mirror

**Comment by crazy-max** [comment]
Update, see https://github.com/CHEF-KOCH/CKs-FilterList-Mirror

**Comment by existential-fallacy** [comment]
This is intr0 @ https://GitLab.com/intr0. GitLab would like you, if you wish, to also submit a DMCA takedown to GitLab considering the repo being ‘mirrored’ there is a way for that person to continue the violation of your MIT licensing terms.
EDIT: link to GitLab’s policy: 
https://about.gitlab.com/handbook/dmca/
☮️ - intr0
