### ISSUE TITLE
Info in description.

### ISSUE THREAD

**Issue by existential-fallacy** [crazy-max/WindowsSpyBlocker#144]
This is intr0 @ https://GitLab.com/intr0. GitLab would like you, if you wish, to also submit a DMCA takedown to GitLab considering the repo being ‘mirrored’ there is a way for that person to continue the violation of your MIT licensing terms.
EDIT: link to GitLab’s policy: 
https://about.gitlab.com/handbook/dmca/
☮️ - intr0

**Comment by crazy-max** [comment]
Hi @existential-fallacy,

Thank you for your support on this case. Can you post your message in #142 to avoid duplicating issues ?
