### ISSUE TITLE
Error on start - Cannot write

### ISSUE THREAD

**Issue by ovz93br43v7** [crazy-max/WindowsSpyBlocker#145]
On start with admin right I just get:

`Fatal: Cannot write file /app.conf: open C:\Users\XXX\Desktop/app.conf: Das System kann die angegebene Datei nicht finden.
Press Enter to exit...`

**Comment by dnmTX** [comment]
@crazy-max looks like improper slash separator( '/' ) before `app.conf:` and Windows can not read it(in my opinion). I think it should be '\'.

**Comment by ovz93br43v7** [comment]
I have tested the last two versions, same result.
Can it be that the Windows Defender / Smartscreen modifies something, I got a warning before launching...

**Comment by crazy-max** [comment]
@ovz93br43v7 Can you post a concise report using the [bug report template](https://github.com/crazy-max/WindowsSpyBlocker/issues/new?template=bug_report.md) please ?

@dnmTX No, `/` is handled on Windows ;)

**Comment by dnmTX** [comment]
> @dnmTX No, / is handled on Windows ;)

Yep,you right. I tested it and it does. Sorry,thought it could help narrow it down. 👍

**Comment by crazy-max** [comment]
@dnmTX No worries, I always appreciate your involvement :handshake:

**Comment by ovz93br43v7** [comment]
### Behaviour
WindowsSpyBlocker.exe stops and cmd shows `Fatal: Cannot write file /app.conf: open C:\Users\XXX\Desktop/app.conf: Das System kann die angegebene Datei nicht finden. Press Enter to exit...`

#### Steps to reproduce this issue

1. download to desktop https://github.com/crazy-max/WindowsSpyBlocker/releases/download/4.19.0/WindowsSpyBlocker.exe
2. start WindowsSpyBlocker.exe
3. Ignore warning of Windows Smartscreen

#### Expected behaviour

> Tell me what should happen
WindowsSpyBlocker.exe should start and act like described on https://github.com/crazy-max/WindowsSpyBlocker

#### Actual behaviour

> Tell me what happens instead
WindowsSpyBlocker.exe stops and cmd shows `Fatal: Cannot write file /app.conf: open C:\Users\XXX\Desktop/app.conf: Das System kann die angegebene Datei nicht finden. Press Enter to exit...`

### Rules used
No rules used

### Configuration

**Country (ex. United-States)** :
Germany

**Operating system (ex. Windows 10 Pro 64 bits)** :
Windows 10 Pro 64 bit, version 1809 from 07.03.2019, build 17763.379

**Comment by crazy-max** [comment]
@ovz93br43v7 Ok SmartScreen filter is the culprit. I will create a new release of WindowsSpyBlocker with signed executable.

**Comment by ovz93br43v7** [comment]
I searched myself also and found out that it is the combination of Windows Smartscreen and Windows Defender option "monitored folder access".

**Comment by crazy-max** [comment]
Yes indeed and unfortunately Certum is not free anymore to handle Code Signing so it will stay as it is for now. What you can do is [whitelisting](https://www.addictivetips.com/windows-tips/whitelist-apps-in-the-smartscreen-on-windows-10/) WindowsSpyBlocker in the program properties.

**Comment by ovz93br43v7** [comment]
As I understand this webpage offeres free code signing: http://wiki.cacert.org/CodesigningCert

**Comment by crazy-max** [comment]
@ovz93br43v7 Yes but:

```
However, these certificates will only work if the CAcert root cert is installed and trusted by the end-user and if the end-user agrees to execute the code.
```
