### ISSUE TITLE
Skype

### ISSUE THREAD

**Issue by talal2** [crazy-max/WindowsSpyBlocker#147]
Hi !

I Can't connect to skype, This is what i get: http://prntscr.com/n4jcys
My hosts file: https://ghostbin.com/paste/wmdqb

                        Thanks in advance :-) ;-)

**Comment by crazy-max** [comment]
Hi @talal2, please fill a proper [bug report](https://github.com/crazy-max/WindowsSpyBlocker/issues/new?template=bug_report.md).
