### ISSUE TITLE
Use with Outlook

### ISSUE THREAD

**Issue by CaptainFrosty** [crazy-max/WindowsSpyBlocker#148]
I'm no expert on it and don't really expect anyone else to be, but I thought I'd give it a shot and see if anyone knows of any possibilities of making email on Exchange servers work without the Microsoft NCSI. It is the one thing that forces me to maintain connections with Microsoft IPs and I'd love to avoid it if possible. Every now and then the client will even manage to update without it, but most of the time when Outlook doesn't have the phone home connection it acts like it is being firewalled which is ridiculous but here we are. I suppose I could use a third party client that supports Exchange but that entails a loss of a lot of features like the native directory and other things. Any help would be appreciated.

**Comment by crazy-max** [comment]
You could use [GPO or registry](https://www.ghacks.net/2014/02/07/disable-customize-windows-internet-connection-test-improve-privacy/) to disable NCSI if you want but don't know if it will work with Exchange.

**Comment by CaptainFrosty** [comment]
Thanks for the suggestion, I'll look into it
