### ISSUE TITLE
Bing Maps blocked in spy.txt

### ISSUE THREAD

**Issue by oneman123** [crazy-max/WindowsSpyBlocker#149]
The following entries in spy.txt are blocking Bing Maps:

dev.virtualearth.net
ecn.dev.virtualearth.net
t0.ssl.ak.dynamic.tiles.virtualearth.net
t0.ssl.ak.tiles.virtualearth.net

Since these are not spying entries, could you move them to extra.txt?

**Comment by crazy-max** [comment]
@oneman123 I will take a look on the virtualearth endpoint as I have not detected telemetry data recently. I keep you in touch.

**Comment by oneman123** [comment]
@crazy-max Thanks!

**Comment by crazy-max** [comment]
Should be fixed in latest release
