### ISSUE TITLE
www.bing.com connection.-

### ISSUE THREAD

**Issue by Jorgu81** [crazy-max/WindowsSpyBlocker#150]
Hi!

With the three hosts applied there is a connection to that web if I open the General Options.
I saw it with Wireshark.

So you only have to add this to the update or extra hosts.

Greetings and keep up the good work!

Windows 10 LTSC 2019

**Comment by crazy-max** [comment]
Hi @Jorgu81, can you create a proper [bug report](https://github.com/crazy-max/WindowsSpyBlocker/issues/new?template=bug_report.md) please? Thanks.
