### ISSUE TITLE
Bug:www.bing.com connection

### ISSUE THREAD

**Issue by Jorgu81** [crazy-max/WindowsSpyBlocker#151]
### Behaviour

Wireshark detects www.bing.com connection in a Windows with the 3 hosts (spy, update and extra) applied.

#### Steps to reproduce this issue

1.Activate Wireshark. Everything is OK, only connections between router and network card.
2.Open modern general menu
3.Wireshark detects a connection to www.bing.com

#### Expected behaviour

Not to connect to that website

#### Actual behaviour

It is always connecting there only when we open Windows Configuration but if I add this domain to Windows host it disappears that connection.

### Rules used

Wireshark for Windows

### Configuration

Spain

Windows 10 LTSC 2019

**Winver screenshot** :

![Save](https://user-images.githubusercontent.com/44495008/57237096-6063e500-701e-11e9-8061-fd613e667e98.jpg)

**Comment by dnmTX** [comment]
@Jorgu81 you don't really expect 'www.bing.com` to be added to any of the lists here,do you?
You need to find out on your end which service is responsible and disable it.

**Comment by Jorgu81** [comment]
Well, it is a connnection with Microsoft, isn't it? I thought the purpose of these list are to avoid calling Microsoft.

It appears automatically when you open the modern Windows Options and never before.

Nevertheless, you are right there must be a service that is responsible but I don't know what it is. To tell the truth I disable Windows update service but the connection remains.

Greetings.

**Comment by dnmTX** [comment]
@Jorgu81  i'm still with Windows 10 LTSB 2016 and i remember i had to disable bunch of them.
Do your research,you'll be amazed how much info is out there.
Just for reference i'll post here a screenshot on some of them so you know at least what to look for:
![Capture](https://user-images.githubusercontent.com/34774426/57245921-99419100-7001-11e9-80c9-25bccfbe0f4f.PNG)

P.S. You can close this if you want as it is not solvable and i'm pretty sure @crazy-max will not honor your request. Good luck 👍

**Comment by crazy-max** [comment]
Hi @Jorgu81,

Thanks for your report. As @dnmTX explains very clearly this is probably due to a service that calls this probe. `www.bing.com` being a multi front-end service I will not add it to any list. In your case it is probably a simple "ping" to check the connection or to establish a connection to your Microsoft account if you are not using a local account. Same principle as for [NCSI probes](https://github.com/crazy-max/WindowsSpyBlocker/wiki/miscFAQ#what-is-ncsi-).

**Comment by Jorgu81** [comment]
Hi @crazy-max.
AFAIK, the ping is to the adress http://www.msftconnecttest.com/ 
In fact, if I block it the system warns me about no internet connection.

BTW, I use a local account not a Microsoft one.

So weird. Well, I will continue looking for the reasons or services.

Greetings.

**Comment by bipface** [comment]
To offer some more detail for the sake of anyone who stumbles upon this discussion,
I found that the `www.bing.com` requests originate from two sources:
1. The Microsoft.Windows.Search app (`%windir%\SystemApps\Microsoft.Windows.Search_cw5n1h2txyewy\SearchApp.exe`).
2. The system settings app (`%windir%\ImmersiveControlPanel\SystemSettings.exe`).

It seems these can be prevented using some system policies (`HKLM\SOFTWARE\Policies\Microsoft\Windows\Explorer\DisableSearchBoxSuggestions=1`, `HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer\AllowOnlineTips=0`).

It's hard to think of any way of mitigating it which would be appropriate for WindowsSpyBlocker, so users may just have to take matters into their own hands with this one.

Note that these observations were all made on a Windows 10 22H2 system.
