### ISSUE TITLE
Unable to login in Skype

### ISSUE THREAD

**Issue by Blank517** [crazy-max/WindowsSpyBlocker#152]
### Behaviour
If some firewall rules are used is not possible to login in Skype for Desktop and in Skype (Windows Store).
I tried both with a new/clean installation.

#### Steps to reproduce this issue

1. Open Skype
2. Try to login

#### Expected behaviour

> A successful login

#### Actual behaviour

> It hangs for some minutes and then it shows "Unable to sign in, please try again"

### Rules used

1. `data/firewall/extra.txt`

2. `data/firewall/spy.txt`

### Configuration

**Country (ex. United-States)** : Italy

**Operating system (ex. Windows 10 Pro 64 bits)** : Windows 10 Enterprise 64 bits

**Winver screenshot** :
![WinVer](https://user-images.githubusercontent.com/26778354/59718774-29870e80-921b-11e9-9dbe-0885432cf15c.png)

**Comment by crazy-max** [comment]
@Blank517 Don't use `extra` rules if you want Skype to work. Extra rules block third party applications like Skype, Bing, Live, Outlook, NCSI, etc.
