### ISSUE TITLE
Ip Address blocking hotmail.com, login.live.com, outlook.live.com

### ISSUE THREAD

**Issue by hyber-code** [crazy-max/WindowsSpyBlocker#153]
![Annotation 2019-07-05 233754](https://user-images.githubusercontent.com/18413990/60744290-f4e6b700-9f7d-11e9-98dc-08fcee6924f8.jpg)
### Behaviour
Following ip are related to hotmail.com
13.107.42.11
40.90.23.213
204.79.197.212

#### Steps to reproduce this issue

1. www.hotmail.com
2. outlook.live.com
3. login.live.com

#### Expected behaviour

website shout open for signing in

> Tell me what should happen
these ips and if any similar ips should be removed from the rule 

#### Actual behaviour

> Tell me what happens instead
login page does not open. 

### Rules used

general rules,
new rules
additional rule, option 1,2,3 used from the firewall menu.

### Configuration

Saudi Arabia
Windows 10 Pro 64 bits
```
C:\Windows\system32>tracert www.hotmail.com

Tracing route to a-0010.a-msedge.net [204.79.197.212]
over a maximum of 30 hops:

  1  General failure.

Trace complete.

C:\Windows\system32>tracert www.hotmail.com

Tracing route to a-0010.a-msedge.net [204.79.197.212]
over a maximum of 30 hops:

  1     1 ms    <1 ms    <1 ms  192.168.1.1
  2     5 ms     5 ms     4 ms  185.76.136.8
  3     4 ms     3 ms     4 ms  10.188.205.10
  4    13 ms    12 ms    12 ms  10.188.195.3
  5   101 ms   102 ms   101 ms  84-235-94-230.saudi.net.sa [84.235.94.230]
  6   111 ms   110 ms   111 ms  msft-decix-01-fra.ntwk.msn.net [80.81.194.52]
  7     *        *        *     Request timed out.
  8     *        *        *     Request timed out.
  9     *        *        *     Request timed out.
 10     *        *        *     Request timed out.
 11   109 ms   109 ms   109 ms  a-0010.a-msedge.net [204.79.197.212]

Trace complete.

C:\Windows\system32>tracert  outlook.live.com

Tracing route to l-0002.l-msedge.net [13.107.42.11]
over a maximum of 30 hops:

  1  General failure.

Trace complete.

C:\Windows\system32>tracert  login.live.com

Tracing route to lgin.msa.trafficmanager.net [40.90.23.213]
over a maximum of 30 hops:

  1  General failure.

Trace complete.

```

**Comment by crazy-max** [comment]
Don't use `extra` rules if you want hotmail to work. Extra rules block third party applications like Skype, Bing, Live, Outlook, NCSI, etc.

**Comment by hyber-code** [comment]
thank you

**Comment by hyber-code** [comment]
Update:

Following is the exact url bookmarked. after i removed all rules it worked fine and again after applying the rules excluding the extra rules, the page though connects fine ( previously it was 404) but doesnt display anything.

```
https://login.live.com/login.srf?wa=wsignin1.0&rpsnv=13&ct=1506165323&rver=6.7.6643.0&wp=MBI_SSL&wreply=https%3a%2f%2foutlook.live.com%2fowa%2f&lc=1033&id=292841&mkt=en-us&cbcxt=out&fl=wld
```
did not attached the screenshot as it is white.

**Comment by crazy-max** [comment]
@hyber-code Latest release should fix your issue.
