### ISSUE TITLE
The regular "spy" firewall rules (without "extra" rules) are blocking Office C2R API connection, therefore Microsoft Office can't be installed online with those firewall rules applied.

### ISSUE THREAD

**Issue by Hyperyia** [crazy-max/WindowsSpyBlocker#154]
Office C2R API link: https://mrodevicemgr.officeapps.live.com/mrodevicemgrsvc/api/v2/C2RReleaseData

Can't be accessed with the "spy" rules applied to Windows Firewall. Many Office C2R tools use this API to install Microsoft Office online.

Fix: Remove the 52.109.88.44 IP address from the "spy" rules.

**Comment by crazy-max** [comment]
@Hyperyia Latest release should fix your issue.
