### ISSUE TITLE
ncsi error with test option adding ncsi rules 

### ISSUE THREAD

**Issue by leeuwtjex** [crazy-max/WindowsSpyBlocker#157]
![errorNCSI](https://user-images.githubusercontent.com/27788737/62728629-8b464680-ba1c-11e9-8eb2-04912984d871.jpg)

Doesn't work.

Windows 7 professional x64 build 7601

**Comment by crazy-max** [comment]
Please edit your issue and use the [bug report template](https://github.com/crazy-max/WindowsSpyBlocker/issues/new?template=bug_report.md).
