### ISSUE TITLE
ncsi error with test option adding ncsi rules

### ISSUE THREAD

**Issue by leeuwtjex** [crazy-max/WindowsSpyBlocker#158]
### Behaviour
![errorNCSI](https://user-images.githubusercontent.com/27788737/62728629-8b464680-ba1c-11e9-8eb2-04912984d871.jpg)

Doesn't work.
Windows 7 professional x64 build 7601

#### Steps to reproduce this issue

# NCSI
 1 - Apply WindowsSpyBlocker NCSI
 2 - Apply Microsoft NCSI
 3 - Test the internet connection

#### Expected behaviour

> test ok?

#### Actual behaviour

> red lined errors 

![winver](https://user-images.githubusercontent.com/27788737/62730595-91d6bd00-ba20-11e9-9436-92284cc02370.jpg)

**Comment by crazy-max** [comment]
Hi @leeuwtjex,

Thanks for your report.

> 1 - Apply WindowsSpyBlocker NCSI
> 2 - Apply Microsoft NCSI

You must choose one or the other. But I think in your case you wanted to test a rollback and I think I know where the issue comes from. I modified the Microsoft probe in January 3f7e012 to use the most recent one. In your case you should use the old probes to return to the original behavior on Windows 7.

I will fix this with a condition on Windows version. As a quick workaround to restore the original probes, you can apply the following reg:

[restore_ncsi_win7.txt](https://github.com/crazy-max/WindowsSpyBlocker/files/3483346/restore_ncsi_win7.txt)
> Rename this file to `restore_ncsi_win7.reg` and launch.

**Comment by leeuwtjex** [comment]
Hi crazy-max,

So that is what is does, 

 2 - Apply WindowsSpyBlocker NCSI   =>  spyblock == on
 3 - Apply Microsoft NCSI                    =>  spyblock == off

Nice to know, I asked a few questions today, shown as 'question' to ask for backup functionality
it is not answered yet.

Ok. I renamed your textfile to a .reg extension  (I could see it was a key regedit text structure).
I imported the key in windows, and rebooted.  After rebooting, I ran the tool with admin rights again, 
I did a '4 - Test the internet connection' results in the picture.

![error2](https://user-images.githubusercontent.com/27788737/62734801-2560bb80-ba2a-11e9-969c-389ff973a7c1.jpg)

Not much change...
And no, I tried option 4 before I used option 2 to modify regedit.
It was ok that moment before activating, so it wasn't an existing issue before using spyblocker.

Could I also have a txt file of the regedit '1 - Apply WindowsSpyBlocker NCSI'  on key?
 I think right now, your NCSI mods do not work for all windows versions....

**Comment by crazy-max** [comment]
Do you have apply some firewall or host rules previously ?

Also can you apply the following NCSI steps and give me the result :

```
2 - Apply WindowsSpyBlocker NCSI
4 - Test the internet connection
```

**Comment by leeuwtjex** [comment]
Please just assume it was ok before running the tool...

Some improvement, web request ok....
![error3](https://user-images.githubusercontent.com/27788737/62736693-44614c80-ba2e-11e9-9fff-7d6a5e710909.jpg)
![error4](https://user-images.githubusercontent.com/27788737/62736700-49260080-ba2e-11e9-9c40-16368c67a037.jpg)

**Comment by leeuwtjex** [comment]
Sorry.... This is my specific situation. When I switch off vpn (and by doing so switch off my vpn's dns server) it is all-right:
![error5](https://user-images.githubusercontent.com/27788737/62738402-87bdba00-ba32-11e9-99da-b2b0b027f968.jpg)
