### ISSUE TITLE
Windows Spy Blocker causing Windows Update/Microsoft Store error downloadings

### ISSUE THREAD

**Issue by theluckyman** [crazy-max/WindowsSpyBlocker#160]
When I use it for the first time for using all kind of full blocking ip address via Firewall then Windows Updates or Microsoft Store is stopping working and I get message error code '0x80072EFD' and it turned out it working after I removed like rollback to unblocking everything after I used it. so is there specific IP addresses after I use it full blocking again but I need to know IP addresses where I can still continue to get windows updates/Microsoft store?

Thanks

**Comment by crazy-max** [comment]
Like I said [before](https://github.com/crazy-max/WindowsSpyBlocker/issues/143#issuecomment-522763997), read the [SUPPORT page](https://github.com/crazy-max/WindowsSpyBlocker/blob/master/.github/SUPPORT.md) >> Create a proper [bug report](https://github.com/crazy-max/WindowsSpyBlocker/issues/new?template=bug_report.md).
