### ISSUE TITLE
Windows update issues

### ISSUE THREAD

**Issue by wilbie** [crazy-max/WindowsSpyBlocker#162]
So my problem is that I have spy + extra rules activated and still can't update Windows. I always just get the message "We ran in a problem". If I understood everything right extra rules shouldn't block the update process. Thanks for the help already.

**Comment by crazy-max** [comment]
@wilbie Please read [SUPPORT page](https://github.com/crazy-max/WindowsSpyBlocker/blob/master/.github/SUPPORT.md) to report an issue and use the [bug report](https://github.com/crazy-max/WindowsSpyBlocker/issues/new?template=bug_report.md) template.
