### ISSUE TITLE
Windows Update issue

### ISSUE THREAD

**Issue by wilbie** [crazy-max/WindowsSpyBlocker#163]
#### Steps to reproduce this issue

1. Just run WindowsSpyBlocker
2. Install the firewall rules
3.

#### Expected behaviour

> Windows updates should still work due to not installing data/firewall/update.txt

#### Actual behaviour

> Windows can't connect to the Windows update Service

### Rules used

> (ex: `data/firewall/spy.txt`)

1. data/firewall/spy.txt
2. data/firewall/extra.txt
3.

### Configuration

**Country (ex. United-States)** : Germany

**Operating system (ex. Windows 10 Pro 64 bits)** : Windows 10 Pro 64 bits

**Winver screenshot** : 
![Annotation 2019-09-09 132719](https://user-images.githubusercontent.com/53477544/64527246-b6ff6980-d305-11e9-88bc-69ba9560ae0d.png)

> Open a command prompt and type winver then take / save the screenshot of the window and drag the image file in this issue. For example: http://bit.ly/2vA5sxR[](url)

**Comment by crazy-max** [comment]
Thanks for your report, I keep you in touch!

**Comment by wilbie** [comment]
I have no clue why, but I just tried it again and it worked. I don't think I changed anything but who knows maybe it was my fault. Thanks for this great program have a good one :)
