### ISSUE TITLE
Hosts and Hostman

### ISSUE THREAD

**Issue by huwtf** [crazy-max/WindowsSpyBlocker#169]
I see you updated the hosts for extra but I no longer see the links where the hosts files are located and hostman no longer updates.  Thanks.

**Comment by crazy-max** [comment]
@huwtf I have added links on [Data - Hosts page](https://github.com/crazy-max/WindowsSpyBlocker/blob/master/doc/data/hosts.md).

**Comment by dartsmaster** [comment]
Hostsman does not recognise host sources from Github. Are the hosts files available anywhere else? Thanks :-)

**Comment by dartsmaster** [comment]
I've just found an answer to my own question!...
https://www.celsoazevedo.com/hosts/
