### ISSUE TITLE
more host

### ISSUE THREAD

**Issue by kvnsmmm** [crazy-max/WindowsSpyBlocker#170]
0.0.0.0 az725175.vo.msecnd.net
0.0.0.0 msedge.api.cdp.microsoft.com
0.0.0.0 cds26.ams9.msecn.net
0.0.0.0 db3aqu.atdmt.com
0.0.0.0 msnbot-65-55-108-23.search.msn.com
0.0.0.0 ca.telemetry.microsoft.com

**Comment by kvnsmmm2** [comment]
0.0.0.0 edgetipscdn.microsoft.com

**Comment by crazy-max** [comment]
Done
