### ISSUE TITLE
Office 2016 Update

### ISSUE THREAD

**Issue by talal2** [crazy-max/WindowsSpyBlocker#171]
In this latest release, Office 2016 in Windows 7 'x64' won't Update !!!

                                                          Thanks in advance ;-)

**Comment by crazy-max** [comment]
@talal2 Please read [SUPPORT page](https://github.com/crazy-max/WindowsSpyBlocker/blob/master/.github/SUPPORT.md) to report an issue and use the [bug report](https://github.com/crazy-max/WindowsSpyBlocker/issues/new?template=bug_report.md) template.
