### ISSUE TITLE
ncsi.bat - Test Internet Connection fails

### ISSUE THREAD

**Issue by zymase** [crazy-max/WindowsSpyBlocker#18]
Hi,

WindowsSpyBlocker-3.4.4 on Windows 7SP1 64-BIT

When performing \scripts\ncsi\ncsi.bat Option **5 - Test Internet connection**, I receive the information hereafter. _The same information is displayed whether I've ran previously_
1 - Apply WindowsSpyBlocker NCSI (local) or 2 - Apply Microsoft NCSI (local)

> IPv4 web probe failed.
> IPv6 web probe failed.
> Le terme « Resolve-DnsName » n'est pas reconnu comme nom d'applet de commande, fonction, fichier de script ou programme exécutable. Vérifiez l'orthographe du nom, ou si un chemin d'accès existe, vérifiez que le chemin d'accès est correct et réessayez.
> Au niveau de D:\My Data\WindowsSpyBlocker\WindowsSpyBlocker-3.4.4\scripts\ncsi\testConnection.ps1 : 21 Caractère : 21
> - if( (Resolve-DnsName <<<<  -Type A -ErrorAction SilentlyContinue (Get-ItemProperty HKLM:\SYSTEM\CurrentControlSet\Services\NlaSvc\Parameters\Internet).ActiveDnsProbeHost).IPAddress -eq
>   - CategoryInfo          : ObjectNotFound: (Resolve-DnsName:String) [], CommandNotFoundException
>   - FullyQualifiedErrorId : CommandNotFoundException

No idea if this is important or not.
I do not have a "No Internet access" warning in my system tray : OK
Moreover, I did not have as well a "No Internet access" warning in my system tray before running ncsi.bat although I had 
added  \data\hosts\win7\extra.txt to my HOSTS file
and
ran \scripts\firewall\firewall.bat with Option 1  - Add extra rules (local)

Thanks for your advice (merci d'avance) !

**Comment by crazy-max** [comment]
Hi,

Are you on a Windows 7 Home or Pro ?

**Comment by share3141** [comment]
Windows 10 - "Anniversary" and Cinnamon Mint 18

**Comment by crazy-max** [comment]
This might be an issue with your PowerShell environment.
Can you open a PowerShell prompt, enter the command `$PSVersionTable.PSVersion` and give me the output ?

Like this :

![image1](https://cloud.githubusercontent.com/assets/1951866/18617323/35a874b6-7dcd-11e6-9f98-88096f59ba49.png)

**Comment by crazy-max** [comment]
@share3141 ?
