### ISSUE TITLE
Hi, I try to download the net framework from https://dotnet.microsoft.com/download/thank-you/net48-developer-pack and is blocked, please can you fix this bug?

### ISSUE THREAD

**Issue by zamdavtrabajo** [crazy-max/WindowsSpyBlocker#182]
#### Steps to reproduce this issue

1.
2.
3.

#### Expected behaviour

> Tell me what should happen

#### Actual behaviour

> Tell me what happens instead

### Rules used

> (ex: `data/firewall/spy.txt`)

1.
2.
3.

### Configuration

**Country (ex. United-States)** :

**Operating system (ex. Windows 10 Pro 64 bits)** :

**Winver screenshot** :

> Open a command prompt and type winver then take / save the screenshot of the window and drag the image file in this issue. For example: http://bit.ly/2vA5sxR

**Comment by crazy-max** [comment]
@wilbie Please create a new bug report with a concise title and fill in the template.
