### ISSUE TITLE
"Extra" firewall rule blocks Windows Update

### ISSUE THREAD

**Issue by braycarlson** [crazy-max/WindowsSpyBlocker#183]
### Behaviour
The firewall rule for `64.4.54.18` from the `extra` ruleset blocks Windows Update using `WindowsSpyBlocker 4.25.0`.

#### Steps to reproduce this issue

1. Open WindowsSpyBlocker 4.25.0
2. Select `Telemetry `
3. Select `Firewall`
4. `Add extra rules`

### Rules used

> `data/firewall/extra.txt`

### Configuration

**Country**
Canada

**Operating system**
Windows 10 Home (x64)

**Winver screenshot** :
![winver](https://user-images.githubusercontent.com/17258012/69013762-ffa85400-0940-11ea-9695-b34fe92c70e3.png)

**Comment by crazy-max** [comment]
Hi @braycarlson, thanks for your report. It happens quiet often that Windows Update rules can be superseded by extra rules. It is therefore recommended not to use them if you want Windows Update to continue to work.
