### ISSUE TITLE
ESET Firewall syntax template

### ISSUE THREAD

**Issue by FadeMind** [crazy-max/WindowsSpyBlocker#187]
Please provide txt file with syntax for ESET Firewall (part of ESET Internet Security). 
Must look like this:
https://pastebin.com/raw/RZmtf0Xa

SCHEMA
```
1.4.5.2,
2.3.4.5,
5.5.5.5
```

WORK LOG

![20191219-1576734268-001](https://user-images.githubusercontent.com/9846948/71148249-7af47280-222b-11ea-86ff-57e7810b402d.png)
![20191219-1576734299-001](https://user-images.githubusercontent.com/9846948/71148781-de32d480-222c-11ea-92b1-e17aaa2ae7dc.png)
![20191219-1576734342-001](https://user-images.githubusercontent.com/9846948/71148252-7b8d0900-222b-11ea-846c-227e0f635ee4.png)

WU
![20191219-1576734529-001](https://user-images.githubusercontent.com/9846948/71148307-a5dec680-222b-11ea-93e5-615921aaf622.png)

Regards

**Comment by crazy-max** [comment]
@FadeMind Done

**Comment by FadeMind** [comment]
@crazy-max thanks for adding this. ONE thing. SYNTAX IPs should be like I posted in main. AT END of IP list should be only line with IP **without comma**. Please add notice about this to MD file. Self screenshot maybe is not clear for others. ESET will not save incorrect syntax rules. 

```
A.A.A.A,
B.B.B.B,
C.C.C.C,
F.F.F.F-T.T.T.T,
Z.Z.Z.Z
```
Regards

**Comment by crazy-max** [comment]
@FadeMind Fixed now, thanks for your input.
