### ISSUE TITLE
distinguish "vortex-win.data.microsoft.com"

### ISSUE THREAD

**Issue by beerisgood** [crazy-max/WindowsSpyBlocker#189]
While _v10c.vortex-win.data.microsoft.com_ is for Diagnostics data Telemetry and _v20.vortex-win.data.microsoft.com_ is for Functional Telemetry, the domain _de.vortex-win.data.microsoft.com_ is for **Microsoft Defender Advanced Threat Protection** - while the prefix (in this case ".de") is country specific.

So please remove

- eu.vortex-win.data.microsoft.com
- us.vortex-win.data.microsoft.com
- vortex-win.data.microsoft.com

from your list.

Source: https://docs.microsoft.com/en-us/windows/privacy/configure-windows-diagnostic-data-in-your-organization#endpoints

Edit:
Also this issue affect both https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt and https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy_v6.txt

**Comment by skipik** [comment]
@beerisgood what about web.vortex.data.microsoft.com?

**Comment by beerisgood** [comment]
> @beerisgood what about web.vortex.data.microsoft.com?

I don't found any information about.

**Comment by beerisgood** [comment]
@crazy-max

**Comment by beerisgood** [comment]
No statement? Another lists already remove it from their list
@crazy-max

**Comment by dnmTX** [comment]
@beerisgood be patient,when @crazy-max find some free time will respond.

**Comment by crazy-max** [comment]
@beerisgood Done
