### ISSUE TITLE
2 Spy entries are maybe incorrect

### ISSUE THREAD

**Issue by beerisgood** [crazy-max/WindowsSpyBlocker#19]
Can you say something about that two entries?
# crl.microsoft.com (https://www.reddit.com/r/privacy/comments/50pa9c/real_windows_7_spying_blocklist/d76iq7k)
#207.46.114.58 (https://www.reddit.com/r/privacy/comments/50pa9c/real_windows_7_spying_blocklist/d76ixib)

**Comment by crazy-max** [comment]
Hi,

Thanks, I'll keep you in touch!

**Comment by beerisgood** [comment]
You should also take a visit here: https://www.reddit.com/r/privacy/comments/50pa9c/real_windows_7_spying_blocklist/

**Comment by crazy-max** [comment]
Ok thx

**Comment by crazy-max** [comment]
So

Indeed there is a mistake for `crl.microsoft.com` in Win7 Spy rules.
It must be only an extra rule because the Microsoft Certificate Revocation List is necessary for some applications.

207.46.114.58 must be on the "update list" and not spy so an other mistake ;)

Thanks for your time btw!

**Comment by akquise** [comment]
`crl.microsoft.com` is still on the Win7 Spy list.

**Comment by crazy-max** [comment]
@akquise thanks!

**Comment by crazy-max** [comment]
Solved on 3.7.5
