### ISSUE TITLE
Which domain on the list blocks the "Your Phone" windows app?

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [crazy-max/WindowsSpyBlocker#190]
I know this isn't bug but I'm struggling to find the domain responsible for blocking the Your Phone app.
I'm using the OpenWRT add-on and narrowed it down to this list: https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt

I can't for the life of me figure it out and thought might as well ask creator since he/she will know the best.

Thank you for your help!

**Comment by mcrossman** [comment]
Try `continuum.dds.microsoft.com`

Your Phone is very finicky with its connection so it may not work immediately.
