### ISSUE TITLE
adl.windows.com

### ISSUE THREAD

**Issue by beerisgood** [crazy-max/WindowsSpyBlocker#191]
"Allows the compatibility update to receive the latest compatibility data from Microsoft."

Please remove that from your list. (Both ttps://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt & https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy_v6.txt)

Source: https://docs.microsoft.com/en-us/windows/deployment/update/windows-analytics-get-started#enable-data-sharing

**Comment by beerisgood** [comment]
@crazy-max

**Comment by crazy-max** [comment]
@beerisgood Will be moved to extra rules on next release

**Comment by beerisgood** [comment]
Fixed.
