### ISSUE TITLE
Combining different security tools

### ISSUE THREAD

**Issue by mr-manh** [crazy-max/WindowsSpyBlocker#193]
Dear CrazyMax and WindowsSpyBlocker community,

I am about to install Windows 10 LTSC 2019 and I plan on using the following tools for privacy, in this order:
1- WPD
2- ShutUp10
3- WindowsSpyBlocker

It seems to me that these tools might complement each other but I'd like to make sure that they're not actually completely redundant. Also more importantly, I'd like to know if they might conflict with each other's configurations. I intend on running them one by one, with a restart in between each.

I'd also be interested to know if you'd run these tools in a different order.

Thanks!

**Comment by crazy-max** [comment]
Hi @mr-manh,

You can use WindowsSpyBlocker in combination with these other tools because WindowsSpyBlocker only impacts network rules and not profound system changes like WPD or ShutUp10.
