### ISSUE TITLE
ISP Website Blocked

### ISSUE THREAD

**Issue by JesseJames8046** [crazy-max/WindowsSpyBlocker#195]
### Behaviour

When attempting to go to ISP website ("teksavvy.com") it will say "Server Not Found" along with "We can’t connect to the server at www.teksavvy.com." When going to the network troubleshooter on Windows and typing in "teksavvy.com" it cites "WPD MS Update IP Block V38" as the issue for the ISP website ("teksavvy.com") being blocked.

#### Steps to reproduce this issue

Enabling WPD MS Update IP Block V38

#### Expected behaviour

Normally when using Firefox my ISP website will load but will not with this rule set in motion.

> Tell me what should happen

#### Actual behaviour

> Tell me what happens instead

### Rules used

> (ex: `data/firewall/spy.txt`)

1.
2.
3.

### Configuration

**Country (ex. United-States)** : Canada

**Operating system (ex. Windows 10 Pro 64 bits)** : Windows 10 Pro
![W10Pro](https://user-images.githubusercontent.com/59541400/71829432-a02e1100-3072-11ea-9e8e-fb2559d48892.PNG)

**Winver screenshot** :

> Open a command prompt and type winver then take / save the screenshot of the window and drag the image file in this issue. For example: http://bit.ly/2vA5sxR

**Comment by crazy-max** [comment]
@JesseJames8046, _WPD MS Update IP Block V38_ is not part of WindowsSpyBlocker but [Windows Privacy Dashboard](https://wpd.app/).

So it looks like this is linked to `data/firewall/update.txt`.
After digging `13.107.246.10` is the culprit here. In the meantime you can remove this IP from the Windows Firewall outbound rule.

**Comment by JesseJames8046** [comment]
I realize this thread is for WindowsSpyBlocker, however, I was lead here by someone on the WPD Discord giving me a link for help leading here. Any way, how do I remove the IP from Windows Firewall?

**Comment by crazy-max** [comment]
@JesseJames8046 https://www.tomshardware.com/news/how-to-open-firewall-ports-in-windows-10,36451.html

**Comment by JesseJames8046** [comment]
Is there a way to allow hotmail/outlook or is that going to be blocked regardless because its Microsoft?

**Comment by crazy-max** [comment]
`13.107.246` range has been removed
