### ISSUE TITLE
Test IP

### ISSUE THREAD

**Issue by TasakaSan** [crazy-max/WindowsSpyBlocker#2]
Hi, 

I currently testing WindowsSpyBlocker and I have a problem when I do a test on the IP firewall rules ...
- Test IPs ...
C: \ Users \ globy \ AppData \ Local \ Temp \ firewallBlockWindowsSpy.vbs (6, 13) Microsoft VBScript runtime error: ActiveX component can not create object: 'InternetExplorer.Application'

![spyblocker](https://cloud.githubusercontent.com/assets/19388363/15289120/4468a35a-1b70-11e6-9104-e669a9a31146.jpg)

**Comment by crazy-max** [comment]
Hi!

* Are you on home ? pro ? 32bits ? 64 bits ?
* Do you have Internet Explorer installed ?

**Comment by TasakaSan** [comment]
Windows 10 Pro Insider Preview #Build 14332 / OS64Bits
Features Internet Explorer 11 uncheck on "Turn Windows Features On or Off"

**Comment by crazy-max** [comment]
Ok that's why InternetExplorer.Application cannot be created.
This part is juste for development purposes not to end user but i will improve WindowsSpyBlocker and create a "real application" ;)

**Comment by crazy-max** [comment]
Solved on 3.0
