### ISSUE TITLE
OpenWRT dnsmasq.conf alternative method

### ISSUE THREAD

**Issue by Tony-il-Capo** [crazy-max/WindowsSpyBlocker#20]
Hi 
Instead of having
address=/domainexample.com/0.0.0.0
Using it like this
server=/domainexample.com/
OpenWRT forum quote user Middling

> The "server" directive tells dnsmasq to forward DNS requests for that domain to the DNS server on the specified IP.  By not specifying an IP you're telling dnsmasq that it's in charge of that domain and should get the info for it from /etc/hosts or it's dhcp config.
> Since there's no hostname-IP mapping for that domain on the router it'll respond with an nxdomain and the browser won't make any connection attempts anywhere.

I have tested this and it is better, ping the "domainexample.com" will display unknown host intead of 'pinging itself' (0.0.0.0)

**Comment by crazy-max** [comment]
Fixed on 3.7.0

**Comment by Tony-il-Capo** [comment]
I think commit is wrong, you should use " server" directive instead of "address", "server=/domainexample.com/" NOT "address=/domainexample.com/" , note that you have "address" instead of "server"

**Comment by crazy-max** [comment]
Oups!

**Comment by Tony-il-Capo** [comment]
Seems OK now
Thanks.
