### ISSUE TITLE
More Host

### ISSUE THREAD

**Issue by zesta995** [crazy-max/WindowsSpyBlocker#202]
0.0.0.0 statics-marketingsites-wcus-ms-com.akamaized.net
0.0.0.0 cds26.ams9.msecn.net
0.0.0.0 compatexchange.cloudapp.net
0.0.0.0 msnbot-65-55-108-23.search.msn.com
0.0.0.0 pricelist.skype.com
0.0.0.0 sls.update.microsoft.com.akadns.net
0.0.0.0 choice.microsoft.com.nstac.net
0.0.0.0 speech.platform.bing.com
0.0.0.0 img-s-msn-com.akamaized.net
0.0.0.0 c.bing.com

**Comment by dnmTX** [comment]
@zesta995 give some info where did you stumble upon them. This way @crazy-max can analyze each one and decide to add them or not.

P.S. `0.0.0.0 sb.scorecardresearch.com` and `0.0.0.0 ad.doubleclick.net` are present almost in every popular website and are not Windows/Microsoft specific.

**Comment by beerisgood** [comment]
sls.update.microsoft.com.akadns.net is part from Windows Update.
Looks like you doesn't know what you're doing.

**Comment by zesta995** [comment]
> @zesta995 give some info where did you stumble upon them. This way @crazy-max can analyze each one and decide to add them or not.
> 
> P.S. `0.0.0.0 sb.scorecardresearch.com` and `0.0.0.0 ad.doubleclick.net` are present almost in every popular website and are not Windows/Microsoft specific.

Thank you dnmTX. Removed.

**Comment by zesta995** [comment]
> sls.update.microsoft.com.akadns.net is part from Windows Update.
> Looks like you doesn't know what you're doing.

beerisgood paid by Microsoft.

**Comment by crazy-max** [comment]
Guys.. GitHub is not a forum or a board so please leave constructive criticism...
@zesta995 as @dnmTX point out, please give some background about those domains.

**Comment by zesta995** [comment]
> Guys.. GitHub is not a forum or a board so please leave constructive criticism...
> @zesta995 as @dnmTX point out, please give some background about those domains.

Microsoft Edge Canary
https://www.microsoftedgeinsider.com/en-us/download/

**Comment by crazy-max** [comment]
@zesta995 I prefer to use passive detection from my VMs to make sure I don't include false positives. I still keep this list aside. Thanks.
