### ISSUE TITLE
DNS vs IP blocking

### ISSUE THREAD

**Issue by haarp** [crazy-max/WindowsSpyBlocker#204]
Hello,

I am missing some information on the merits of using DNS blackholing vs IP blocking. DNS blocking is bound to be less effective as there could theoretically be tens of thousands of sub-domains that could change with every update. On the other hand, IP-based blocking is effective, but might also include false-positives in case Microsoft is offering legit services together with spyware on one of its IP addresses.

What are people's experiences? Is DNS blackholing effective enough?

**Comment by beerisgood** [comment]
Reading DNS Domains is much easier then IPs which also can be changed but change DNS get more attention.

In my setup I block all directly IP connections so only the way over DNS is possible.
Then I can see everything and got more transparency which also works good

**Comment by dnmTX** [comment]
> Reading DNS Domains is much easier then IPs which also can be changed but change DNS get more attention.

In my setup I block all directly IP connections so only the way over DNS is possible.
Then I can see everything and got more transparency which also works good

👎 👎 👎

**Comment by beerisgood** [comment]
> 
> 
> > Reading DNS Domains is much easier then IPs which also can be changed but change DNS get more attention.
> > In my setup I block all directly IP connections so only the way over DNS is possible.
> > Then I can see everything and got more transparency which also works good
> 
> 👎 👎 👎

What a helpfully post. I am proud of you.
