### ISSUE TITLE
continuum.dds.microsoft.com

### ISSUE THREAD

**Issue by beerisgood** [crazy-max/WindowsSpyBlocker#206]
continuum.dds.microsoft.com is in your spy.txt & spy_v6.txt blocked.

It's used for Xbox archivements and also used on Windows if the same Microsoft/ Xbox account is used and/ or only the Windows Store is used with that account.

So that isn't telemetry.

Also this user confirm it: https://www.trueachievements.com/forum/viewthread.aspx?tid=998988&anchor=8080806#m8080806

**Comment by crazy-max** [comment]
@beerisgood,

As this domain has been detected on a healthy system without a Microsoft / Xbox account it is a spy probe. If this impinges on the use of Xbox achievements, I suggest you whitelist it in your DNS configuration.

**Comment by beerisgood** [comment]
How has this been done? Connect to a domain doesn't mean automatically that data are send

**Comment by fraencko** [comment]
I just needed to whitelist this domain in order to use the Your Phone Companion app that lets you connect Win10 with Android phones.

**Comment by ramazansancar** [comment]
> I just needed to whitelist this domain in order to use the Your Phone Companion app that lets you connect Win10 with Android phones.

It's all complete nonsense :D

![image](https://github.com/user-attachments/assets/e5345041-f645-4542-afaa-dd596fd883e4)


Just Working this :P

![image](https://github.com/user-attachments/assets/f6a3ba80-451e-4bd1-b7db-1597e259ebd2)
