### ISSUE TITLE
NCSI invalid content

### ISSUE THREAD

**Issue by Mr-Sheep** [crazy-max/WindowsSpyBlocker#207]
Hi,
I setup my own ncsi server. 
When testing, WindowsSpyBlocker prompts error when testing web request. But apparently, the contents were the same.
```

Testing web request IPv4... Error: Invalid content '992288
'. Expected '992288'
Testing web request IPv6... Error: Invalid content '992288
'. Expected '992288'

```

**Comment by crazy-max** [comment]
Hi @Mr-Sheep,

Looks like you have a carriage return at this endpoint.
