### ISSUE TITLE
answers.microsoft.com and login.live.com and support.microsoft.com should not be blocked

### ISSUE THREAD

**Issue by p1r473** [crazy-max/WindowsSpyBlocker#208]
answers.microsoft.com should not be blocked
It is not a spy tracker. Just a help forum.

login.live.com should not be blocked either
It is a login website for Live

support.microsoft.com should not be blocked either
It is a support page.

**Comment by crazy-max** [comment]
@p1r473 These domains are part of [extra rules](https://github.com/crazy-max/WindowsSpyBlocker/blob/master/doc/usage.md#datatypeextratxt). If you don't want them blocked, don't use extra rules.

**Comment by coredumperror** [comment]
You should probably explain in the app itself that the extra rules have major consequences like breaking the Microsoft Store. Having it in the README isn't sufficient, imo.

**Comment by crazy-max** [comment]
@coredumperror Good idea!
