### ISSUE TITLE
Breaking answers.microsoft.com

### ISSUE THREAD

**Issue by dartraiden** [crazy-max/WindowsSpyBlocker#21]
https://github.com/crazy-max/WindowsSpyBlocker/blob/master/data/openwrt/win10/spy/dnsmasq.conf

`address=/answers.microsoft.com/0.0.0.0`

Are we really should block this address? Blocking it leads to inaccessible of Microsoft Community Forums. For example, [this URL](https://answers.microsoft.com/en-us/surface/forum/surfbook-surfrepair/new-ms-tool-to-repair-problems-with-anniversary/e994965b-8a2a-4ebc-99ee-7f7ad2715c6d) cannot be opened (IE tells "enable TLS", Firefox tells "error occurred while establishing a secure connection").

**Comment by Tony-il-Capo** [comment]
I would strongly recommend to not remove it from blocking,  there's a lot of tracking even when you visit that address using browser, you can't even image the data that windows sends to microsoft using background processes. (using those addresses)

You can always use something like TOR to connect to those addresses safely via browser, you can even run it on a openwrt router...

I personally block every system process on comodo firewall, only allow dhcp and lan access, always use ssh tunneling to reach lan when on the go, so, windows will actually never connect to addresses.
The openwrt firewall/dnsmasq blocking is just a supplement to my privacy.

**Comment by crazy-max** [comment]
I agree with @Tony-il-Capo statement
`answers.microsoft.com` is used by Windows background processes as rollback domain.
If you want to surf on this domain you can use TOR or [Google cache](https://webcache.googleusercontent.com/search?q=cache:lFSayXec9boJ:answers.microsoft.com/en-us/surface/forum/surfbook-surfrepair/new-ms-tool-to-repair-problems-with-anniversary/e994965b-8a2a-4ebc-99ee-7f7ad2715c6d)
