### ISSUE TITLE
Question about Windows updates

### ISSUE THREAD

**Issue by Bondarz** [crazy-max/WindowsSpyBlocker#215]
Hello,

thanks for this program.

Since I (must) actively use Win from time to time, I would like to run WIndows updates.
Do I always have to remove all rules and set it again, or can I explicitly "whitelist" the updates?

Is there a recommendation here? Thanks!

**Comment by crazy-max** [comment]
Hi @Bondarz,

Everything is explained in the [documentation](https://github.com/crazy-max/WindowsSpyBlocker/blob/master/doc/usage.md#data). See also [this thread](https://github.com/crazy-max/WindowsSpyBlocker/blob/master/doc/faq.md#couldnt-connect-to-the-update-service) if you've got issues with Windows Updates.
