### ISSUE TITLE
Windows 10 Store Blocked

### ISSUE THREAD

**Issue by psych0d0g** [crazy-max/WindowsSpyBlocker#22]
#### Steps to reproduce this issue
1. update win10 to build 1607
2. start store

#### Expected Behaviour
Windows App store should load

#### Actual Behaviour
Dies with a connection error due to "storeedgefd.dsx.mp.microsoft.com" being actively blocked

#### Configuration

Germany , windows 10 pro 32bit
Build 1607 (Build 14393.351)
```

**Comment by crazy-max** [comment]
Hi,

Do you use Proxifier or another network post-level application ?

**Comment by crazy-max** [comment]
Solved on 3.6.0
