### ISSUE TITLE
Service CDPUserSvc high cpu usage 

### ISSUE THREAD

**Issue by andyalt23** [crazy-max/WindowsSpyBlocker#220]
After applying firewall spy rules this service has started running at 30/50% cpu usage. 
If i disable it from HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\CDPUserSvc the issue is solved but i can't naturally use some function like night light.

**Comment by crazy-max** [comment]
@andyalt23 Nothing to do with Windows Firewall AFAIK. See also:

* https://www.reddit.com/r/Windows10/comments/8qquks/anyone_experiencing_cpu_issues_with_cdpusersvc/
* https://www.tenforums.com/performance-maintenance/115244-cdpusersvc-using-high-cpu.html
* https://www.surfacetablethelp.com/2018/09/cdpusersvc-causes-high-cpu-usage-and-battery-drains-in-windows-10.html

**Comment by consal** [comment]
I have exactly the same issue.
I choose `2 - Add spy rules`, immediate spike in `CDPUserSvc` to 30%
I delete all the rules, it immediately goes down to 0%.

Maybe someone else managed to find how's it related to the rules?
