### ISSUE TITLE
Using normal Router to stop Microsoft from spying?

### ISSUE THREAD

**Issue by Golddouble** [crazy-max/WindowsSpyBlocker#222]
Very happy, that I have discovered your site. I am not a professional user. I am just a normal private user.

### **Question 1:**
I read, that when I want to use hosts, I have to make this on a second machine (for example on a Raspberry). When I use the hosts from your list in the windows host file ("%windir%\system32\drivers\etc\hosts") this has no effect. Is this true?

### **Question 2:**
If the answer of question 1 was "yes", I just must say, that I am looking for a solution without an additional PC. 
Question: So can I have the same, with my Router, that already is installed?
Is it enough only to enter simply the entries from here:
https://github.com/crazy-max/WindowsSpyBlocker/blob/master/data/firewall/spy.txt
into my router?

### **Question 3:**
If question 2 was "yes":
I am not sure, if my router does support this function. I have found in my Router this:
`Firewall->user defined rules:`
Here I have 7 fields. Can you please say me, which fields I would have to use, and what I have to enter in this fields? Can you make an example?

**Here are the fields:**
```
-Service (FTP, HTTP, SMTP...)
-Protocol (TCP, UDP...)
-local IP- address
-remote IP- address
-local port 
-remote port
-action (I guess here I have to choose: Reject from local address)
```

Would appreciate, if you could answer me all 3 questions. Thank you.

**Comment by crazy-max** [comment]
@Golddouble,

> Question 1

Yes and no, see https://github.com/crazy-max/WindowsSpyBlocker/issues/93#issuecomment-370204892

> Question 2

Depends of the brand but most of the time yes. See https://github.com/crazy-max/WindowsSpyBlocker/issues/156#issuecomment-519224548 about suggested alternatives.

> Question 3

Sorry I don't know all the routers on the market. I advise you to look for help on the brand's forum.
