### ISSUE TITLE
Something in the "extra rules" breaks the Microsoft Store.

### ISSUE THREAD

**Issue by coredumperror** [crazy-max/WindowsSpyBlocker#223]
### Behaviour
If you install the "extra rules", Microsoft Store complains that you're not connected to the Internet, and refuses to install anything. Oddly enough, installing the WindowsSpyblocker NCSI does *not* break the store.

#### Steps to reproduce this issue

1. Install the Extra Rules.
2. Attempt to install anything from the Microsoft Store.
3. Error message "It seems like you're not connected to the Internet." and it won't let you install anything.

### Configuration

Country: USA

Operating system: Windows 10 Enterprise 64bit version 1909 (OS build 18363.836)

**Comment by yc51** [comment]
Me too,Bro!
Don't Use The IP Blocker when u install app from Store!

**Comment by crazy-max** [comment]
https://github.com/crazy-max/WindowsSpyBlocker/issues/208#issuecomment-590975970
