### ISSUE TITLE
settings-win.data.microsoft.com

### ISSUE THREAD

**Issue by xxcriticxx** [crazy-max/WindowsSpyBlocker#224]
#### Steps to reproduce this issue

1. found it via my pihole 
2.
3.

#### Expected behaviour

domain should be unblocked

#### Actual behaviour

domain should is blocked

### Rules used

> (ex: `data/firewall/spy.txt`)

1. pihole 5.0
2.
3.

### Configuration

**Country (ex. United-States)** : USA

**Operating system (ex. Windows 10 Pro 64 bits)** : Windows 10 Pro 64 bits

**Winver screenshot** :

please review https://github.com/WaLLy3K/wally3k.github.io/issues/108 for more details

**Comment by crazy-max** [comment]
@p1r473 `settings-win.data.microsoft.com` is already in the extra rules.
