### ISSUE TITLE
simple dnscrypt support?

### ISSUE THREAD

**Issue by Skrell** [crazy-max/WindowsSpyBlocker#23]
I'm sure this is wrong place to ask this but could you possible add support for Simple Dnscrypt so that I don't have to manually parse your proxifier files for each new release?

**Comment by crazy-max** [comment]
You can use the data inside the [dnscrypt folder](https://github.com/crazy-max/WindowsSpyBlocker/tree/master/data/dnscrypt) instead of proxifier

**Comment by Skrell** [comment]
But then what about the hard coded IPs that need to be blocked?  Is there another folder that JUST contains these?

**Comment by crazy-max** [comment]
Yes you can use the `data/firewall` folder and/or the firewall.bat script in `scripts/firewall`
