### ISSUE TITLE
Windows 10 Telemetry

### ISSUE THREAD

**Issue by jjwgtdbr5ssn** [crazy-max/WindowsSpyBlocker#230]
fb2acc3814078dbc5bc0619db1c0acf2.clo.footprintdns.com
bgpdefault-amb.msedge.net
peer2-amb.msedge.net
peer1-amb.msedge.net

**Comment by crazy-max** [comment]
@jjwgtdbr5ssn I prefer to use passive detection from my VMs to make sure I don't include false positives. I still keep this list aside. Thanks.
