### ISSUE TITLE
Telemetry Hosts

### ISSUE THREAD

**Issue by webga123** [crazy-max/WindowsSpyBlocker#234]
fb2acc3814078dbc5bc0619db1c0acf2.clo.footprintdns.com
bgpdefault-amb.msedge.net
peer2-amb.msedge.net
peer1-amb.msedge.net
42db8d1db64991029778e4c30936289b.clo.footprintdns.com
azwantest2germany.trafficmanager.net
segments-s.msedge.net
a830edad9050849405e20022917.sharepoint.com
fp-as.azureedge.net
graph.azurefd.net
fp-afd.azurefd.net
c-ring.msedge.net
b-ring.msedge.net
fp-afd.azureedge.net
a-ring.msedge.net
azwanp.trafficmanager.net
dw8wjz3q0i4gj.cloudfront.net
ow1.res.office365.com
l-ring.msedge.net
tring.clo.footprintdns.com
moiawsorigin.clo.footprintdns.com
fp-as.azureedge.net
bing.com
moiafdaws.clo.footprintdns.com
fp-vs.azureedge.net
moiafdazure.clo.footprintdns.com
exo-ring.msedge.net
q-ring-fallback.msedge.net
ow1.res.office365.com
s-ring.msedge.net
fp-afd.azureedge.net
a-ring-fallback.msedge.net
m.qualifytring.com
azwancan.trafficmanager.net
eafddirect.msedge.net
graph.microsoft.com
frca1lbip.francecentral.cloudapp.azure.com
fp-vp.azureedge.net
graph.microsoft.com
dw8wjz3q0i4gj.cloudfront.net
t-ring.msedge.net
moiazureorigin.clo.footprintdns.com
fp-vs.azureedge.net
fp-vp.azureedge.net
fp-afd.azurefd.us
graph.azurefd.net
q-ring.msedge.net
fp-afd.azureedge.us
k-ring.msedge.net
fp.msedge.net
da.xboxservices.com

source
https://fp.msedge.net/conf/v1/asgw/fpconfig.min.json

**Comment by crazy-max** [comment]
@webga123 I prefer to use passive detection from my VMs to make sure I don't include false positives. I still keep this list aside. Thanks.
