### ISSUE TITLE
Blocker list for OPNSense

### ISSUE THREAD

**Issue by elbast** [crazy-max/WindowsSpyBlocker#235]
Hi crazy-max,
i have successfully tried your list variety in several use cases.
I would appreciate a list format for the OPNSense Firewall.

Unfortunately, none of the many list formats in the Data folder worked here.
I use the alias lists of the OPNSense (https://docs.opnsense.org/manual/aliases.html) and only the format of the DROP list (https://www.spamhaus.org/drop/drop.txt) seems to work. 
("X.X.X.X/Y ;")

Thank you.

**Comment by crazy-max** [comment]
Hi @elbast,

You can already block **hosts** with a predefined DNSBL list:

![image](https://user-images.githubusercontent.com/1951866/84684119-bbf1e900-af27-11ea-9938-a4cac9b2ce82.png)

For **firewall** (IPs) rules, you can use an URL alias type in your firewall:

> **Firewall > Aliases**
![image](https://user-images.githubusercontent.com/1951866/84684343-0ecba080-af28-11ea-9973-3b098cc5a6fc.png)

And add it as a _Disable rule_ in your firewall rules:

![image](https://user-images.githubusercontent.com/1951866/84684454-33277d00-af28-11ea-82b7-da4cb82b487b.png)
