### ISSUE TITLE
No EOLs on simplewall files

### ISSUE THREAD

**Issue by Cade66** [crazy-max/WindowsSpyBlocker#238]
Hi,

I use all three simplewall files,
```
https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/dnscrypt/extra.txt
https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/dnscrypt/spy.txt
https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/dnscrypt/update.txt
```
which I all merge with several other blocklists.

Unfortunately all three miss an EOL with the obvious consequence that last item gets mixed with first item of following file in the merge process.
At this time I have to add a `FileAppend , \n, [FILE]` in order to get things done correctly (Autohotkey scripting).

Thanks!

**Comment by crazy-max** [comment]
@Cade66 Since you do it programmatically, continue with your method.

**Comment by llacb47** [comment]
Just add a newline, it's not that hard...?

**Comment by Cade66** [comment]
All lists I use include a final blank line, pity not these three.
I can manage programmatically as noted above but I have in mind those who may merge several blacklists without being aware of the possible mix (unless next file starts itself with a blank line of course).

**Comment by crazy-max** [comment]
@Cade66 This is now fixed

**Comment by Cade66** [comment]
@crazy-max , indeed. I removed the add of a blank line accordingly for all three lists and all is OK, of course.
Merging scripts could very well add an EOL to all lists of course, given the process removes them once the job is done, and that could be a pertinent caution practice, but not sure they all do (mine didn't) and that can lead to two missed items at least.
Thanks for notifying the enhancement.
I already use all three of your blocking lists in their IP version with the _Windows Privacy Dashboard_ application, adding the three domain equivalences is an extra caution, here.
**Thanks** for your work, most appreciated by many, obviously.
