### ISSUE TITLE
Seems like your "Update" list might be out of date

### ISSUE THREAD

**Issue by privacyguy123** [crazy-max/WindowsSpyBlocker#240]
All these new IPs asking for connections in Microsoft Store and Windows Update on Windows 10 build 2004.

![image](https://user-images.githubusercontent.com/50337995/85902662-7de4a700-b7fc-11ea-954f-ba795ca90452.png)

**Comment by privacyguy123** [comment]
![image](https://user-images.githubusercontent.com/50337995/86160066-25b2eb00-bb03-11ea-8ab6-9d9b339adf44.png)

**Comment by crazy-max** [comment]
@privacyguy123 I prefer to use passive detection from my VMs to make sure I don't include false positives. I still keep this list aside. Thanks.
