### ISSUE TITLE
Issue reporting - Connection / Edge blocked by 3 IP (on the latest version 4.30.0.0

### ISSUE THREAD

**Issue by LPey** [crazy-max/WindowsSpyBlocker#242]
### Behaviour
Connection / Edge blocked
#### Steps to reproduce this issue
13.107.6.158
40.90.22.184
40.90.22.186
#### Actual behaviour
Error message: Connection blocked by firewall
Diagnostic tool > Detail > Gives the 'faulty' IP
### Rules used
windowsSpyBlockerExtra-13.107.6.158
windowsSpyBlockerExtra-40.90.22.184
windowsSpyBlockerExtra-40.90.22.186
### ConfigurationwindowsSpyBlockerExtra-40.90.22.184
4.30.0.0
**Country (ex. United-States)** :
France
**Operating system (ex. Windows 10 Pro 64 bits)** :
Windows 10 Family 64 bits (2004)
**Winver screenshot** :
![Copie d'écran_2020-07-05_1339](https://user-images.githubusercontent.com/34707449/86531851-0f22e000-bec5-11ea-9b12-0ba7f9e4bbfc.png)

> Open a command prompt and type winver then take / save the screenshot of the window and drag the image file in this issue. For example: http://bit.ly/2vA5sxR

**Comment by crazy-max** [comment]
@LPey These IPs are part of [extra rules](https://github.com/crazy-max/WindowsSpyBlocker/blob/master/doc/usage.md#datatypeextratxt). If you don't want them blocked, don't use extra rules. More info about rules in [doc](https://github.com/crazy-max/WindowsSpyBlocker/blob/master/doc/usage.md#data).
