### ISSUE TITLE
Why block answers.microsoft.com?

### ISSUE THREAD

**Issue by gatolanudo** [crazy-max/WindowsSpyBlocker#25]
Sorry, but I don't get it. As far as I know it's just a support forum.
Is there any outgoing automated request from Windows 10 to that host or some shady connection through a troubleshooter? It's blocked from Windows 10 spy file.

**Comment by Tony-il-Capo** [comment]
I said it right, 'as far as you know'!
[Here](https://github.com/crazy-max/WindowsSpyBlocker/issues/21)

**Comment by crazy-max** [comment]
Hi @Tony-il-Capo, like on issue #21, i keep this rule because like i said this one is used by Windows background processes as rollback domain.
