### ISSUE TITLE
NCSI: No Internet access reported

### ISSUE THREAD

**Issue by Gittyperson** [crazy-max/WindowsSpyBlocker#251]
This is most probably a [Windows bug](https://www.ghacks.net/2020/07/19/windows-10-version-2004-may-show-no-internet-even-though-there-is-internet-access/), but I can confirm that when applying the WindowsSpyBlocker NCSI, Windows 10 2004 will report there is no Internet connection (connection still works fine). Reverting to the Microsoft NCSI, fixes the wrong warning message.

**Comment by Gittyperson** [comment]
Connection works fine, although it seems some Microsoft-releated software will not work properly or at all (Store Apps, Office etc.)

**Comment by crazy-max** [comment]
Hi @Gittyperson,

Indeed, now pastebin redirects http to https so our custom NCSI is broken. Will fix that on next release.

**Comment by ViRb3** [comment]
May I recommend using another platform's internet connectivity check endpoint to avoid similar problems in the future.
- Google (e.g. Android): http://connectivitycheck.gstatic.com | [reference](https://community.arubainstanton.com/t5/Everything-Instant-On/How-Does-Apple-CNA-works-for-Guest-Users-connecting-to-Aruba/m-p/1244#M408)
- Apple (e.g. iOS): http://captive.apple.com | [reference](https://community.arubainstanton.com/t5/Everything-Instant-On/How-Does-Apple-CNA-works-for-Guest-Users-connecting-to-Aruba/m-p/1244#M408)

**Comment by llacb47** [comment]
Firefox: http://detectportal.firefox.com/

**Comment by ViRb3** [comment]
I vouch for Firefox's, as it's the simplest to use. Here's how to do it by hand for the eager ones:
```reg
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\NlaSvc\Parameters\Internet]
"ActiveWebProbeContent"="success
"
"ActiveWebProbeContentV6"="success
"
"ActiveWebProbeHost"="detectportal.firefox.com"
"ActiveWebProbeHostV6"="detectportal.firefox.com"
"ActiveWebProbePath"="/"
"ActiveWebProbePathV6"="/"
```
Note that there's a `/n` at the end of the `success` message, that's `0a 00` as binary.

Apple and Google return HTML responses which may cause issues with Windows now or in the future.

**Comment by crazy-max** [comment]
@ViRb3 LGTM, thanks for your input

**Comment by crazy-max** [comment]
Fixed: https://github.com/crazy-max/WindowsSpyBlocker/releases/tag/4.31.0
