### ISSUE TITLE
Duplicate DNSCrypt rules

### ISSUE THREAD

**Issue by guser-sudo** [crazy-max/WindowsSpyBlocker#258]
DNSCrypt treats example.com and *.example.com as identical (see [here](https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Filters)). Therefore some rules are duplicates and could be removed.

**Comment by crazy-max** [comment]
@guser-sudo This is [already available](https://github.com/crazy-max/WindowsSpyBlocker/blob/master/data/dnscrypt/spy.txt). Wildcard rules to process blocking list for DNSCrypt are [here](https://github.com/crazy-max/WindowsSpyBlocker/blob/78884f2c5274fddc22a5016ad2f2190f1fbc0ac4/app/settings.json#L145-L201).

**Comment by guser-sudo** [comment]
@crazy-max
What I'm saying is that there are too many/redundant/unnecessary/duplicated entries in that list, e.g. *.adnxs.com = adnxs.com. DNSCrypt only ever uses the first it encounters and never the other. So one could remove a few rules. But it's not a big deal as long as the number of unnecessary rules stays small.
