### ISSUE TITLE
Blocking login.live.com

### ISSUE THREAD

**Issue by StevenBlack** [crazy-max/WindowsSpyBlocker#26]
I see closed Issue #15.  This seems related.

Is there a reason `login.live.com` is listed [here](https://github.com/crazy-max/WindowsSpyBlocker/blob/4df24c02daa4dbba2dbce092279c9f1cd01e666c/data/hosts/win10/extra.txt#L17) and [here](https://github.com/crazy-max/WindowsSpyBlocker/blob/4df24c02daa4dbba2dbce092279c9f1cd01e666c/data/hosts/win81/extra.txt#L13) which are the `extra.txt` files under `Win10/` and `Win81/`?

Reason I ask is, this domain is required for Skype login.

**Comment by crazy-max** [comment]
Hi @StevenBlack,

Extra files must be used carefully.
Some domains in these files are "required" by third party applications on Windows (like Skype like you said).
In other words, with "extra" rules you add an extra shield but at your own risk ;)

**Comment by StevenBlack** [comment]
@crazy-max ah!  Thank you for that.

> Btw, can i quote your repo?

But of course!  Keep up the good fight!

**Comment by crazy-max** [comment]
Ok i will send you a PR as a gift ;)
