### ISSUE TITLE
Suggestion: clean all temp files after closing

### ISSUE THREAD

**Issue by BigKananga** [crazy-max/WindowsSpyBlocker#265]
When running WindowsSpyBlocker, in the same folder several files will be created. Would it be possible to create them in default Windows temp folder and delete them after WindowsSpyBlocker is closed? It's a bit annoying to do this manually. Especially when you also have other files and folders where the WindowsSpyBlocker.exe is.

**Comment by crazy-max** [comment]
@BigKananga 

> When running WindowsSpyBlocker, in the same folder several files will be created. Would it be possible to create them in default Windows temp folder and delete them after WindowsSpyBlocker is closed?

This is the excpected behavior. WindowsSpyBlocker has been designed to be portable so everything resides in its own directory.

>  Especially when you also have other files and folders where the WindowsSpyBlocker.exe is.

You should place the executable in its own folder then. (like `C:\opt\WindowsSpyBlocker\WindowsSpyBlocker.exe`)

**Comment by BigKananga** [comment]
@crazy-max 
I know how to circumvent it. Would it be possible that WindowsSpyBlocker deletes all the temp files and folder automatically after closing? I think they are not needed anymore then.
