### ISSUE TITLE
Microsoft OneNote Sync is Blocked

### ISSUE THREAD

**Issue by ArtiomL** [crazy-max/WindowsSpyBlocker#27]
Following one of the latest `spy` rules updates - MS OneNote isn't able to sync notebooks.

Possibly because of:

- 0.0.0.0 nexus.officeapps.live.com
- 0.0.0.0 officeclient.microsoft.com
- 0.0.0.0 mobile.pipe.aria.microsoft.com

**Comment by crazy-max** [comment]
Hi,

Can you attach to this issue your OneNote logs (https://bealers.com/2013/03/20/enable-onenote-2013-logging/) ?
Have you tried the [OneNote Diagnostics Tool](https://www.microsoft.com/en-us/download/details.aspx?id=53336) ?

**Comment by crazy-max** [comment]
@ArtiomL Could be related to the issue #29. Can you confirm ?

**Comment by lazer15** [comment]
I have found that commenting the following out of a different windows 10 privacy host file script fixed the sync failure as described here.

login.live.com
oneclient.sfx.ms

I'm using a local windows account (not a microsoft account) to login to my computer if that makes a difference.  Login.live.com seemed to be required to login to onenote and the oneclient.sfx.ms for syncing.

**Comment by crazy-max** [comment]
oneclient.sfx.ms is linked to onedrive.
I will move this rule to the extra one.

**Comment by crazy-max** [comment]
I just checked and `oneclient.sfx.ms` and `login.live.com` are already in the extra rules.
