### ISSUE TITLE
IP address that should be moved from spy to extra

### ISSUE THREAD

**Issue by loxia01** [crazy-max/WindowsSpyBlocker#278]
### Behaviour
IP address 51.11.168.160 is blocked in spy rules, but points to arc.msn.com (Windows Spotlight), which is an extra feature.

#### Steps to reproduce this issue

1. See latest spy firewall list.
2.
3.

#### Expected behaviour

> Tell me what should happen
The IP address should not be blocked in spy rules, but instead in extra rules.

#### Actual behaviour

> Tell me what happens instead

### Rules used

> (ex: `data/firewall/spy.txt`)

1.
2.
3.

### Configuration

**Country (ex. United-States)** :

**Operating system (ex. Windows 10 Pro 64 bits)** :

**Winver screenshot** :

> Open a command prompt and type winver then take / save the screenshot of the window and drag the image file in this issue. For example: http://bit.ly/2vA5sxR

**Comment by crazy-max** [comment]
@loxia01 Thanks for your input. The rule has been moved to extra.
