### ISSUE TITLE
Windows Updates are recovered

### ISSUE THREAD

**Issue by EyesReye** [crazy-max/WindowsSpyBlocker#282]
#### Steps to reproduce this issue

1. Disable Windows Updates in the Advanced Settings
2. Disable Windows Updates with the Firewall Rule or Filtering Platform
3. Restart PC

#### Expected behaviour

> Windows updates should be completely blocked from doing anything.

#### Actual behaviour

> Windows Update services recovered after a day or so and Windows starts doing it's thing again by installing new Updates.
Firewall / Filtering platform don't seem like they block the updates from being downloaded and the services are being recovered even when "PerformRemediation and Update Medic Service" are disabled. They all just randomly start working again and I'm not even restarting my PC, it's left on 24/7.

### Rules used

> (ex: `data/firewall/spy.txt`)

1. The ones that the WPD Application uses to block the Windows Updates 

### Configuration

**Country (ex. United-States)** :
The Netherlands

**Operating system (ex. Windows 10 Pro 64 bits)** :
Windows 10 Home 64 bits

**Winver screenshot** :
![image](https://user-images.githubusercontent.com/20639679/97196364-ae3d5180-17ac-11eb-8d1b-56c040cd4f21.png)

> Open a command prompt and type winver then take / save the screenshot of the window and drag the image file in this issue. For example: http://bit.ly/2vA5sxR

**Comment by crazy-max** [comment]
@EyesReye Should be fixed now
