### ISSUE TITLE
Data Invalid when importing simplewall [SOLUTION]

### ISSUE THREAD

**Issue by dennyamarojr** [crazy-max/WindowsSpyBlocker#286]
Hi crazy-max,

This is just a fix for the files in the project, I installed simplewall and when importing the file blocklist.xml appear the message data invalid, as showed in the picture below
![Capture](https://user-images.githubusercontent.com/36896116/98255958-d9553d00-1f32-11eb-9b44-0853a7fba606.JPG)

So what I did was changing a little things to work, here's the update folder with the changes made
[simplewall.zip](https://github.com/crazy-max/WindowsSpyBlocker/files/5495053/simplewall.zip)

**Comment by crazy-max** [comment]
@dennyamarojr 

![image](https://user-images.githubusercontent.com/1951866/98468290-c2804600-21d1-11eb-95a8-a554500d10c1.png)

**File > Import** is not designed to import blocking rules but profile settings (including blocking rules) so it will overwrite current settings in simplewall. You should open an issue on the [official repo](https://github.com/henrypp/simplewall) about that.
