### ISSUE TITLE
Office365 Clients are blocked

### ISSUE THREAD

**Issue by danishabdullah** [crazy-max/WindowsSpyBlocker#29]
#### Steps to reproduce this issue
1. Install office 365 desktop apps
2. Activate the spy blocker hostfile
3. Try to log in to activate and use your licensed product

#### Expected Behaviour
You should be able to sign into your office 365 desktop apps and keep them working

#### Actual Behaviour
You cannot sign in and access the configuration

#### Configuration
```0.0.0.0 officeclient.microsoft.com```

#### Fix
```# 0.0.0.0 officeclient.microsoft.com```

**Country** : Germany

**Operating system** : Windows 10 Pro 64 bit

**Winver** : Version 1607 OS Build 14393.0

**Comment by crazy-max** [comment]
Hi,

Indeed `officeclient.microsoft.com` is the signin domain for the Office365 clients.
This rule will be moved to the extra ruleset on the next release.

**Comment by crazy-max** [comment]
Solved on 3.7.2
