### ISSUE TITLE
Telemetry in Visual Studio

### ISSUE THREAD

**Issue by misaka00251** [crazy-max/WindowsSpyBlocker#294]
### Behaviour

These hostnames are Visual Studio's telemetry hostnames.

```
vortex.data.microsoft.com
dc.services.visualstudio.com
visualstudio-devdiv-c2s.msedge.net
az667904.vo.msecnd.net
az700632.vo.msecnd.net
sxpdata.microsoft.com
sxp.microsoft.com
```

#### Steps to reproduce this issue

1.
2.
3.

#### Expected behaviour

> These should be added in spy rules.

#### Actual behaviour

> Tell me what happens instead

### Rules used

> (ex: `data/firewall/spy.txt`)

1.
2.
3.

### Configuration

**Country (ex. United-States)** :

**Operating system (ex. Windows 10 Pro 64 bits)** :

**Winver screenshot** :

> Open a command prompt and type winver then take / save the screenshot of the window and drag the image file in this issue. For example: http://bit.ly/2vA5sxR

**Comment by crazy-max** [comment]
@misaka00251 The only domain recorded on WSB spy rules in your list is `vortex.data.microsoft.com` and it's a valid telemetry endpoint.
