### ISSUE TITLE
Q: how to make Microsoft telemetry visible?

### ISSUE THREAD

**Issue by HK53** [crazy-max/WindowsSpyBlocker#295]
Dear All,
Is there an easy (or: not too complex) way to make the actual Microsoft telemetry visible? I need this in a discussion about the privacy of Windows 10.
TIA, 
HK

**Comment by crazy-max** [comment]
@HK53 Not AFAIK, but that could help: https://crazymax.dev/WindowsSpyBlocker/telemetry-info/
