### ISSUE TITLE
 Spy rules prevent 'OneDrive' application/website from working.

### ISSUE THREAD

**Issue by xcom169** [crazy-max/WindowsSpyBlocker#302]
#### Steps to reproduce this issue

1. Install spy rules and go to  https://onedrive.live.com/ 
2.
3.

#### Expected behaviour

> Tell me what should happen

#### Actual behaviour

> Tell me what happens instead

### Rules used

> (ex: `data/firewall/spy.txt`)

1. Spy
2.
3.

### Configuration

![image](https://user-images.githubusercontent.com/17802090/103997090-f1e40c80-519a-11eb-82d2-3603e0a28b4e.png)

**Country (ex. United-States)** :

**Operating system (ex. Windows 10 Pro 64 bits)** :

**Winver screenshot** :
![image](https://user-images.githubusercontent.com/17802090/103741592-a80ff080-4ff9-11eb-8e7d-03ef266dabee.png)

> Open a command prompt and type winver then take / save the screenshot of the window and drag the image file in this issue. For example: http://bit.ly/2vA5sxR

**Comment by fgsiout** [comment]
Can confirm this is still an issue.

Blocked IPs I've encountered a problem so far:
40.90.142.226 (i-am3p-cor002.api.p001.1drv.com)
13.104.208.162 (i-db3p-cor004.api.p001.1drv.com)
