### ISSUE TITLE
IP addresses that should be moved from spy to extra

### ISSUE THREAD

**Issue by loxia01** [crazy-max/WindowsSpyBlocker#304]
The followoing IP addresses in spy rules points to storage.live.com, a domain blocked in extra rules, but not in spy rules:

13.104.158.177
13.104.158.179
13.104.158.180
13.104.158.183
13.104.208.160
13.104.208.162
13.104.208.164
13.104.208.165
13.105.66.144
40.90.128.17
40.90.142.224
40.90.142.226
40.90.142.230

**Comment by crazy-max** [comment]
Should be fixed with latest release
