### ISSUE TITLE
can't add spy.txt link to hostsman

### ISSUE THREAD

**Issue by Skrell** [crazy-max/WindowsSpyBlocker#307]
When attempting to add the following web address to hostsman I get the error "this source is not compatible"

https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt

Would love to be able to add this to the excellent hostsman app!

**Comment by crazy-max** [comment]
@Skrell https://github.com/crazy-max/WindowsSpyBlocker/issues/169#issuecomment-575315641

**Comment by Skrell** [comment]
Thank you!!
