### ISSUE TITLE
Suggestion: Add command line parameter handling

### ISSUE THREAD

**Issue by RalMay** [crazy-max/WindowsSpyBlocker#317]
For automation purposes it was very handy if WSP handled command line parameters.
Ideally I could call WSP.exe with parameters corresponding to the menu selection(s) like
"WindowsSpyBlocker.exe 1 1 1" to "Add extra rules" or "WindowsSpyBlocker.exe 1 2 3" to "Apply Firefox NCSI".

Ideally the application exited after completion and the return code would tell about error/succes.

P.S. Why? To call WSP e.g. weekly using Task Scheduler to update firewall rules to newest.

**Comment by crazy-max** [comment]
Duplicate #87
