### ISSUE TITLE
Whitelist Tresorit

### ISSUE THREAD

**Issue by TheAresjej** [crazy-max/WindowsSpyBlocker#319]
#### Steps to reproduce this issue

1. Use wpd.app
2. Set Extra blocking list
3. Open tresorit.com

#### Expected behaviour

> Website should work

#### Actual behaviour

> Your Internet access is blocked / Firewall or antivirus software may have blocked the connection.

### Rules used
![Untitled](https://user-images.githubusercontent.com/19390797/107866498-f2468600-6e71-11eb-8063-8d9c7adf94d8.png)

### Configuration

**Country (ex. United-States)** : UK

**Operating system (ex. Windows 10 Pro 64 bits)** : Windows 10 LTS 2019

**Winver screenshot** :
![image](https://user-images.githubusercontent.com/19390797/107866459-8f54ef00-6e71-11eb-825c-27c4d8ecd12b.png)

**Comment by crazy-max** [comment]
@TheAresjej https://crazymax.dev/WindowsSpyBlocker/blocking-rules/#extra-rules
