### ISSUE TITLE
Skype problem

### ISSUE THREAD

**Issue by Gittyperson** [crazy-max/WindowsSpyBlocker#32]
Many thanks for your work. I think there's something in the latest spy IP list (data/firewall/win10/spy.txt) that causes problems to Skype, which now only partially works. The status icon keeps spinning (always "Connecting") and only some friends are available. Disabling these rules in my Firewall makes the problem go away after a Skype restart.

Tried several Skype for Windows versions, including the current 7.31.0.104 (the client's auto-update does yet push v.7.32, available on FileHippo etc. - also tried that).

Win 10 x64 (1607 / 14393.693)

**Comment by crazy-max** [comment]
Hi!

Thanks for your feedback!
Do you try to check IP by IP if you are brave enough 😀 ?
I'll keep you in touch!

**Comment by Gittyperson** [comment]
I'm not that brave! But I think this happened with the latest WindowsSpyBlocker update, perhaps you added some new IP's there? I could try with those.

**Comment by crazy-max** [comment]
Yes please and i think it's the 3.7.2 release

**Comment by Gittyperson** [comment]
Following the 3.7.2 release notes, I removed all 52.164.xx and 134.170.xx IP's but problem remains. Perhaps there are more new ones?

**Comment by crazy-max** [comment]
Ok i will investigate on this issue

**Comment by Gittyperson** [comment]
Noticed Skype's internal updater is also affected - they are now pushing version 7.32.0.104 but the updater fails, unless the rules are disabled.

I tried looking at my Firewall's logs to see which IP is being blocked but they're not helpful.

**Comment by Oscar-Geare** [comment]
Hey, since skype ate windows live messenger, I think it's also adopted the clientconfig.passport.net domain for updates. Seems like traffic to this domain is being routed through Proxifier? Maybe it is interfering with Skype.

**Comment by Atavic** [comment]
Since Skype was bought by MS, it was included in MS botnet
.
StevenBlack's [repo](https://github.com/StevenBlack/hosts/issues/183) removed `s.gateway.messenger.live.com` for this issue.

**Comment by crazy-max** [comment]
@Atavic thanks

**Comment by crazy-max** [comment]
@Gittyperson Ok, Can you try to remove `mobile.pipe.aria.microsoft.com` from your host file ?

**Comment by crazy-max** [comment]
@Gittyperson Hum i think the ip range `13.107.3` could be your problem

**Comment by Gittyperson** [comment]
Thank you crazy-max! Removing 40.77.226.0-40.77.226.255 solves the problem. Removing 13.107.3.128 has no effect on this issue.

**Comment by crazy-max** [comment]
Iw will close the issue for the next release

**Comment by crazy-max** [comment]
Solved on 3.7.4
