### ISSUE TITLE
Merge Option is broken

### ISSUE THREAD

**Issue by n0101** [crazy-max/WindowsSpyBlocker#329]
#### Steps to reproduce this issue

1.  Run program, press 2 for Dev
2.  Press 6 to run Merge - Merge HOSTS and Firewall data

`Firewall extra
Seeking /data/firewall/extra.txt... Error: CreateFile F:\Apps/data/firewall/extra.txt: The system cannot find the path specified.

Firewall spy
Seeking /data/firewall/spy.txt... Error: CreateFile F:\Apps/data/firewall/spy.txt: The system cannot find the path specified.

Firewall update
Seeking /data/firewall/update.txt... Error: CreateFile F:\Apps/data/firewall/update.txt: The system cannot find the path specified.

Hosts extra
Seeking /data/hosts/extra.txt... Error: CreateFile F:\Apps/data/hosts/extra.txt: The system cannot find the path specified.

Hosts spy
Seeking /data/hosts/spy.txt... Error: CreateFile F:\Apps/data/hosts/spy.txt: The system cannot find the path specified.

Hosts update
Seeking /data/hosts/update.txt... Error: CreateFile F:\Apps/data/hosts/update.txt: The system cannot find the path specified.`

Seems like just a matter of correcting the "/" to "\" for Windows file path format.

**Comment by crazy-max** [comment]
@n0101 You have to first extract data to be able to merge:

* Run WindowsSpyBlocker
* 2 > dev
* 7 > extract data
* 6 > merge
