### ISSUE TITLE
Can't download Windows 10 updates

### ISSUE THREAD

**Issue by niklas1212** [crazy-max/WindowsSpyBlocker#349]
#### Steps to reproduce this issue

1.
2.
3.

#### Expected behaviour

> Tell me what should happen

#### Actual behaviour

> Tell me what happens instead

### Rules used

> (ex: `data/firewall/spy.txt`)

1.
2.
3.

### Configuration

**Country (ex. United-States)** :

**Operating system (ex. Windows 10 Pro 64 bits)** :

**Winver screenshot** :

> Open a command prompt and type winver then take / save the screenshot of the window and drag the image file in this issue. For example: http://bit.ly/2vA5sxR

**Comment by niklas1212** [comment]
I think is something with this ip:s

52.114.77.164 ----

204.79.197.200 ----

20.83.81.160 ----

**Comment by crazy-max** [comment]
`52.114.77` and `204.79.197` are part of the [extra rules](https://crazymax.dev/WindowsSpyBlocker/blocking-rules/#extra-rules) and `20.83.81` and the [update rules](https://crazymax.dev/WindowsSpyBlocker/blocking-rules/#update-rules).
