### ISSUE TITLE
[Suggestion] Add telemetry info on README.md

### ISSUE THREAD

**Issue by Atavic** [crazy-max/WindowsSpyBlocker#35]
#### [FYI] Add the following info to README.md

What is contained into telemetry data sent by the OS to various servers?
You can read a list [here](https://www.ghacks.net/2017/04/06/windows-10-full-and-basic-telemetry-data-collection-information/) or look at the [original info](https://technet.microsoft.com/itpro/windows/configure/windows-diagnostic-data) from the Corporation.

**Comment by crazy-max** [comment]
Thanks for your contrib i will grean additional info in the readme

**Comment by Atavic** [comment]
Your efforts are simply the best around (compared to most host file based workarounds). Proxifier isn't free, though. A free solution instead will make this project perfect.

**Comment by crazy-max** [comment]
Wow thanks!
And for your question about proxifier, i have planned to develop a similar app linked to WSB.

**Comment by Atavic** [comment]
A Wow back to you, @crazy-max

**Comment by crazy-max** [comment]
Telemetry info have been added to the [Wiki](https://github.com/crazy-max/WindowsSpyBlocker/wiki/Telemetry) ;)
