### ISSUE TITLE
Question/Suggestion: Why is Add extra rules first when in docs it says "ONLY use if you know what you do"

### ISSUE THREAD

**Issue by rasmus-z** [crazy-max/WindowsSpyBlocker#352]
Since Spy rules are "Recommended", I'd assume they would be the first option instead of after the option the docs stat "ONLY use if you know what you do".
Perhaps change it from:
 1 - Add extra rules
 2 - Add spy rules
 3 - Add update rules
to:
 1 - Add spy rules - Recommended
 2 - Add update rules
 3 - Add extra rules - ONLY use if you know what you do

**Comment by crazy-max** [comment]
@rasmus-z Good idea, thanks for your feedback.
