### ISSUE TITLE
Windows 11 widgets panel + insider preview options in settings blocked by spy rules

### ISSUE THREAD

**Issue by antintin0** [crazy-max/WindowsSpyBlocker#372]
### Behaviour

I installed simplewall on windows 11 and only have the "spy" blocklist active (not the update or extras blocklist), and both the windows insider settings and widgets panel are seemingly blocked. 

#### Steps to reproduce this issue

1. Enable spy rules

#### Expected behaviour

Spy rules should optimally not block widgets panel or beta channel updates. 

####

If anyone knows which specific spy rule blocks these 2 features, please let me know.

**Comment by crazy-max** [comment]
@antintin0 I was able to create a Windows 11 VM. Will push new rules soon. Thanks for your feedback.

**Comment by crazy-max** [comment]
@antintin0 Will push the update tonight. Looks good so far on my side:

## widgets

![image](https://user-images.githubusercontent.com/1951866/134820772-58390d80-1b08-4a88-9400-d56ad5edf1a1.png)

![image](https://user-images.githubusercontent.com/1951866/134820779-3f0bdfc3-e3de-4b82-9406-4749a8ce73d8.png)

![image](https://user-images.githubusercontent.com/1951866/134820785-c96295d5-da34-4e5d-ac28-74463ede676f.png)

![image](https://user-images.githubusercontent.com/1951866/134821162-41e17ef3-2107-44ae-80b3-fc2c5cb2496e.png)

## insider options

![image](https://user-images.githubusercontent.com/1951866/134821427-d319bd05-58d5-4403-8c99-72d73a0b3f04.png)

## store

![image](https://user-images.githubusercontent.com/1951866/134820868-25ed8954-d3bf-436d-96aa-c56f3951fe81.png)

**Comment by azumukupoe** [comment]
it's still blocked for me with 4.39.0

**Comment by rfgamaral** [comment]
> it's still blocked for me with 4.39.0 ![image](https://user-images.githubusercontent.com/31339007/169641474-0b8a3ed7-cbb2-49d1-956e-c39d433080c2.png)

I have this same issue, and unblocking `insideruser.trafficmanager.net` from the `hosts` solves it for me.

Maybe this domain shouldn't be blocked?

**Comment by balu100** [comment]
unblocking insideruser.microsoft.com fixes the issue

`@@||insideruser.microsoft.com^$important`
