### ISSUE TITLE
Version 4.37.0 crashes when adding firewall rules

### ISSUE THREAD

**Issue by 1024mb** [crazy-max/WindowsSpyBlocker#379]
#### Steps to reproduce this issue

1. Try to update firewall (spy) rules

#### Expected behaviour

No to crash

#### Actual behaviour

Crashes without creating any log

### Rules used

> (ex: `data/firewall/spy.txt`)

1. Spy

### Configuration

**Country (ex. United-States)** : Why do you need this?

**Operating system (ex. Windows 10 Pro 64 bits)** : Windows 10 Pro Workstation x64

**Winver screenshot** :
![winver_2021-09-26_16-49-56](https://user-images.githubusercontent.com/9301204/134825359-f992f306-db02-462d-bba4-f11ebaba00e7.png)

> Open a command prompt and type winver then take / save the screenshot of the window and drag the image file in this issue. For example: http://bit.ly/2vA5sxR

**Comment by 1024mb** [comment]
Trying to remove the rules also makes it crash.

**Comment by crazy-max** [comment]
https://github.com/crazy-max/WindowsSpyBlocker/releases/tag/4.37.1 should fix this issue. Thanks for your feedback.

**Comment by 1024mb** [comment]
Thank you!
