### ISSUE TITLE
 connection establish to Remote address

### ISSUE THREAD

**Issue by ZamanOof** [crazy-max/WindowsSpyBlocker#381]
Hello,
i noticed there is 443 connection for a windwosspyblocker.exe 
like
104.21.233.190:443 
185.199.110.133:443
https://i.imgur.com/xma6to8.png
so what the reasons behind
thanks

**Comment by crazy-max** [comment]
@ZamanOof Use to [check the latest version](https://github.com/crazy-max/WindowsSpyBlocker/blob/e5e001b3a28620bc7dc2035163b2f89e34e20996/app/utils/app/app.go#L153-L171) of WindowsSpyBlocker on GitHub. Endpoint is [`https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/.res/latest`](https://github.com/crazy-max/WindowsSpyBlocker/blob/8c59f2961a658c4dbdbb51f42428a179105712a8/app/settings.json#L3).

`185.199.110.153` [belongs to GitHub](https://ipinfo.io/185.199.110.153) but `104.21.233.190` has nothing to do with WindowsSpyBlocker.
