### ISSUE TITLE
Microsoft Teams and Outlook365

### ISSUE THREAD

**Issue by jevou** [crazy-max/WindowsSpyBlocker#385]
I had to whitelist these addresses in extra to get Teams and Outlook working.

config.teams.microsoft.com
outlook.office365.com
ic3.events.data.microsoft.com
teams.events.data.microsoft.com
login.microsoftonline.com

------------------

EDIT: found a couple more in wireshark log my comp trying to reach, but software is working with above exceptions

self.events.data.microsoft.com
graph.microsoft.com
v10.events.data.microsoft.com
browser.events.data.microsoft.com

------------------

EDIT again: sorry for edits, seems to be working without events addresses, now i have whitelisted

config.teams.microsoft.com
outlook.office365.com
login.microsoftonline.com

**Comment by crazy-max** [comment]
@jevou Same as https://github.com/crazy-max/WindowsSpyBlocker/issues/398#issuecomment-1127089061
