### ISSUE TITLE
spy\131.253.61.0-131.253.61.255 blocks "login.live.com" (131.253.61.100)

### ISSUE THREAD

**Issue by henrypp** [crazy-max/WindowsSpyBlocker#39]
spy\131.253.61.0-131.253.61.255 blocks "login.live.com" (131.253.61.100)

**Comment by crazy-max** [comment]
Hi, thanks for your contrib, i will take a look on your issue

**Comment by ltGuillaume** [comment]
So... this is still happening. You sure this IP is actively being used for telemetry?

**Comment by crazy-max** [comment]
> 131.253.61.100
> 131.253.61.66

@ltGuillaume Those ips are not in the spy rules in the latest release

**Comment by ltGuillaume** [comment]
They're still in extra. If you're not supposed to add the extra rules if you're going to use any Microsoft website, it should be documented properly.

**Comment by crazy-max** [comment]
> They're  still in extra. If you're not supposed to add the extra rules if you're  going to use any Microsoft website, it should be documented properly.

It's documented in the README :

![image](https://user-images.githubusercontent.com/1951866/31770487-6d98fc72-b4d8-11e7-9e7e-1000cdf59e5d.png)

**Comment by ltGuillaume** [comment]
Sorry but I really don't think that's a proper description. A website is no
application, no matter what definition you adhere to. Applications could be
Skype or something, so I could see why this would be blocked by it (plus,
there's telemetry in Skype).

But is Windows actively seeking a connection to this domain without the
user having set up an e-mail account or something? Why is it in the list?

**Comment by Atavic** [comment]
By logging into _live.com_ site you agree to the [services agreement](https://www.microsoft.com/en-us/servicesagreement/) and you **Consent for Internet-based or wireless services**, which means they map your LAN.

Also its [privacy statement](https://privacy.microsoft.com/en-us/privacystatement) has a
**Reasons We Share Personal Data** section: 

>We also share data with Microsoft-controlled affiliates and subsidiaries;

By accepting MS Cookies you let MS so do much more and MS includes both applications and services into those agreements above.

Related: https://github.com/crazy-max/WindowsSpyBlocker/issues/35

**Comment by ltGuillaume** [comment]
Thanks @Atavic for the info. They'll map my LAN if using the Windows Store or something like the Mail app from the Store, yes, not when I visit the website. Cookies are removed as soon as I close the tab. But I do see that this domain is probably heavily integrated with Windows (Microsoft account, Mail), so the inclusion in the -extra list is justified. The thing is that I still think that for such consequences, a meager description like "Block third party applications" does not cover the scope.

**Comment by Atavic** [comment]
It lacks "and services".

**Comment by crazy-max** [comment]
@ltGuillaume You right, i will update the description
