### ISSUE TITLE
Rules for extras?

### ISSUE THREAD

**Issue by 358k** [crazy-max/WindowsSpyBlocker#391]
Hi, I've noticed some microsoft domains on my nextdns logs, which are not being blocked

ecs.office.com
(Documented here: https://docs.microsoft.com/en-us/dynamics365/customer-service/system-requirements-omnichannel)

cdn.odc.officeapps.live.com
(https://docs.microsoft.com/en-us/microsoft-365/enterprise/network-requests-in-office-2016-for-mac?view=o365-worldwide)

messaging.office.com
(https://social.technet.microsoft.com/Forums/en-US/8654af5e-a1bf-413c-b552-ad1075bc75c7/why-is-office-trying-to-connect-to-messagingofficecom?forum=officeitpro)

clients.config.office.net
metadata.templates.cdn.office.net
login.windows.net
nleditor.osi.office.net
uci.cdn.office.net
odc.officeapps.live.com
(https://officeclient.microsoft.com/serverconfig16)

**Comment by crazy-max** [comment]
Should be fixed with latest release: https://github.com/crazy-max/WindowsSpyBlocker/releases/tag/4.39.0
