### ISSUE TITLE
Website Broken - cs.dds.microsoft.com

### ISSUE THREAD

**Issue by gyCfjSnO** [crazy-max/WindowsSpyBlocker#394]
### Issue(s):

- Website Broken

### Domain(s):

- Domain(s):
```cs.dds.microsoft.com```

### Your Config:

- Client: AdGuard Home
- Version: v0.107.0-b.14

### Detail:

- Your Issue Detail: This domain should not be blocked as it is part of Windows Autopilot deployment. Windows Autopilot is a collection of technologies used to set up and pre-configure new devices, getting them ready for productive use. You can also use Windows Autopilot to reset, repurpose, and recover devices. This solution enables an IT department to achieve the above with little to no infrastructure to manage, with a process that's easy and simple. You can learn more here - ```https://docs.microsoft.com/en-us/mem/autopilot/windows-autopilot```

**Comment by crazy-max** [comment]
Same as https://github.com/crazy-max/WindowsSpyBlocker/issues/398#issuecomment-1127089061
