### ISSUE TITLE
Website Broken - settings-win.data.microsoft.com

### ISSUE THREAD

**Issue by gyCfjSnO** [crazy-max/WindowsSpyBlocker#395]
### Issue(s):

- Website Broken

### Domain(s):

- Domain(s):

```settings-win.data.microsoft.com```

### Your Config:

- Client: AdGuard Home
- Version: v0.107.0-b.14

### Detail:

- Your Issue Detail:

> This endpoint is used to remotely configure diagnostics-related settings and data collection. For example, we use the settings endpoint to remotely block an event from being sent back to Microsoft. We do not recommend disabling this endpoint. This endpoint does not upload Windows diagnostic data.
> https://docs.microsoft.com/en-us/windows/privacy/configure-windows-diagnostic-data-in-your-organization

**Comment by crazy-max** [comment]
Same as https://github.com/crazy-max/WindowsSpyBlocker/issues/398#issuecomment-1127089061
