### ISSUE TITLE
Website Broken - activity.windows.com

### ISSUE THREAD

**Issue by gyCfjSnO** [crazy-max/WindowsSpyBlocker#396]
### Issue(s):

- Website Broken

### Domain(s):

- Domain(s):

```activity.windows.com```

### Your Config:

- Client: AdGuard Home
- Version: v0.107.0-b.14

### Detail:

- Your Issue Detail:

Endpoint ```activity.windows.com``` listed as required for Windows 10 & Office.

> The following endpoints are used by Activity Feed Service which enables multiple cross-device data roaming scenarios on Windows - https://docs.microsoft.com/en-us/windows/privacy/windows-endpoints-20h2-non-enterprise-editions

> https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide

**Comment by crazy-max** [comment]
@gyCfjSnO Afaik `activity.windows.com` is only required for activity feed and office online activity and doesn't break any core functionality. Just brings enhancements for online experience which is a telemetry probe. Suggest to whitelist this domain on your side.
