### ISSUE TITLE
Website Broken - evoke-windowsservices-tas.msedge.net

### ISSUE THREAD

**Issue by gyCfjSnO** [crazy-max/WindowsSpyBlocker#397]
### Issue(s):

- Website Broken

### Domain(s):

- Domain(s):

```evoke-windowsservices-tas.msedge.net```

### Your Config:

- Client: AdGuard Home
- Version: v0.107.0-b.14

### Detail:

- Your Issue Detail:

Endpoint ```evoke-windowsservices-tas.msedge.net``` is used by the Photos app to download configuration files, and to connect to the Microsoft 365 admin center’s shared infrastructure, including Office.

https://docs.microsoft.com/en-us/windows/privacy/windows-endpoints-1709-non-enterprise-editions

**Comment by crazy-max** [comment]
@gyCfjSnO Same as https://github.com/crazy-max/WindowsSpyBlocker/issues/398#issuecomment-1127089061
