### ISSUE TITLE
Separate list for blocking Windovs Store and online search.

### ISSUE THREAD

**Issue by slipeer** [crazy-max/WindowsSpyBlocker#4]
It would be nice to allocate separate list of hosts needed for Windovs Store and online search.
Thanks.

**Comment by crazy-max** [comment]
Ok I assume you have Windows Store online searches denied ?

**Comment by slipeer** [comment]
No I would like to block these services.
But someone may be necessary, therefore, I propose to make this lock a separate option .

**Comment by crazy-max** [comment]
For Windows Store, the queries domains / ips are on :
* Akamai Technologies CDN
* Search MSN

So you can use the Windows Extra file to block Windows Store but i suggest for you to remove Windows Store from your computer with this command on PowerShell (as admin) :

```
Get-AppxPackage *windowsstore* | Remove-AppxPackage
```
