### ISSUE TITLE
Hostsman won't accept the github URL's as a source

### ISSUE THREAD

**Issue by JordanBoulan** [crazy-max/WindowsSpyBlocker#400]
This is an issue with Hostsman compatible not the app.

#### Steps to reproduce this issue

1. Download hostman or hostman-portable (I used portable maintained by you)
2. Add a source with:
https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
as the url in 2nd box labeled "filename or URL"
3. Click test connection
![image](https://user-images.githubusercontent.com/16548279/142279736-43dc5d9e-56fa-415f-a98d-9c88966a769f.png)

#### Expected behaviour

> It works and should be able to update my hosts file with that as a source

#### Actual behaviour

> It says:
"The source is not compatible.  Server does not return all the necessary information"

Also when I add the source and try to update anyway. I look at the log and it says this, it is confusing because http 200 means OK so not sure what the issue is:
![image](https://user-images.githubusercontent.com/16548279/142280275-ee96cd08-b41d-4961-a663-b9a61d26032f.png)

### Rules used

> (ex: `data/firewall/spy.txt`)

I followed the instructions on your website here: https://crazymax.dev/WindowsSpyBlocker/blocking-rules/hosts/

1. https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
2. https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/update.txt
3. https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/extra.txt

### Configuration

 Windows 10 Pro 64 bit

**Comment by JordanBoulan** [comment]
Thanks for that. Was that in the readme or instructions anywhere? Seems like it was not. The only problem is he only hosts the v4 version of the files. He doesn't host spy_v6.txt and the v6 for the other files. Is that an issue? Do I need both v4 and v6 to be secure or properly block?

**Comment by dnmTX** [comment]
> Was that in the readme or instructions anywhere? Seems like it was not.

It's not as far as i can tell but i found the answer in another issue posted here: #169 
Looks like the lists there are updated regularly so it's a worry free for ya 😉 

> Is that an issue? Do I need both v4 and v6 to be secure or properly block?
@JordanBoulan the IPv6 lists here are optional and are meant for users who have it enabled on their end.
You,generally don't need it enabled so,if it is,just disable it. 
When using only IPv4 protocol,loading both variations is just too much overhead with no extra protection whatsoever.
![Capture](https://user-images.githubusercontent.com/34774426/142284395-d7f9a888-77bb-4ff6-a215-385379e4caaa.PNG)

**Comment by JordanBoulan** [comment]
@dnmTX Ok v6 was enabled for me and I disabled it.

However, I don't see a reason not to leave it enabled and use both v4 and v6 lists combined into one. Unfortunately the v6 lists are not hosted by that guy. Like sure I don't need v6 in most cases but it would be nice to be able to leave it enabled anyway.

**Comment by JordanBoulan** [comment]
Is there any disadvantage to disabling v6? What is a situation where you need it enabled?

**Comment by dnmTX** [comment]
@JordanBoulan read about IPv6 and decide for yourself. I never had it enabled on my end and so far haven't seen any disadvantages to be honest.
Anyway....we are going OFF TOPIC here and the repo owner wouldn't like it so GOOD LUCK 👍
