### ISSUE TITLE
Add Microsoft tracking domains

### ISSUE THREAD

**Issue by JuanRodenas** [crazy-max/WindowsSpyBlocker#424]
Please, add Microsoft tracking domains:
~~~
0.0.0.0 aria.microsoft.com
0.0.0.0 privacy.microsoft.com
0.0.0.0 wpc.v0cdn.net
0.0.0.0 nexusrules.officeapps.live.com
~~~

Best regards,
Thanks you, Juan

**Comment by thatsprettygood** [comment]
Any update on this?

**Comment by crazy-max** [comment]
`nexusrules.officeapps.live.com` is already taken into account and others are not valid.
