### ISSUE TITLE
Many Windows Update/Microsoft Store server IPs are not whitelisted

### ISSUE THREAD

**Issue by privacyguy123** [crazy-max/WindowsSpyBlocker#428]
and need to be added manually in Simplewall. Easiest way to see this is to block svchost.exe and run Windows Update/Microsoft Store and see the IPs it tries to contact.

**Comment by Kamaldeep0625** [comment]
Yeah, I am having to disable it all until this is fixed.

**Comment by privacyguy123** [comment]
Bump this - been broken for an age.

**Comment by crazy-max** [comment]
@privacyguy123 Please create a proper [bug report](https://github.com/crazy-max/WindowsSpyBlocker/issues/new?assignees=&labels=&template=bug_report.md)
