### ISSUE TITLE
Cannot download image from Onedrive with spy.txt in Adguard Home blocked list

### ISSUE THREAD

**Issue by quyleanh** [crazy-max/WindowsSpyBlocker#437]
#### Steps to reproduce this issue

1. Add content from `spy.txt` file to Adguard Home blocked list
2. Open Onedrive Android app and download image
3. Image cannot be downloaded
4. Check Adguard Home log

#### Expected behaviour

File should be downloaded normally

#### Actual behaviour

File cannot be downloaded with these following log

**Request details**

    Time        10:04:24.570
    Date        2/24/2022
    Domain      skyapi.live.net
    Type        A
    Protocol    Plain DNS

**Response details**

    Status:             Blocked by CNAME or IP
    DNS server:         https://dns.google:443/dns-query (served from cache)
    Elapsed:            2 ms
    Response code:      NOERROR
    Rule(s):            0.0.0.0 i-sn3p-cor002.api.p001.1drv.com
                        WindowsSpyBlocker - Hosts spy rules
    Response:           A: 0.0.0.0 (ttl=10)
    Original response:  CNAME: common-geo.ha.1drv.com. (ttl=60)
                        CNAME: common-geo.onedrive.trafficmanager.net. (ttl=60)
                        CNAME: sn3pcor002-com.be.1drv.com. (ttl=60)
                        CNAME: i-sn3p-cor002.api.p001.1drv.com. (ttl=60)
                        A: 40.90.136.163 (ttl=60)

### Rules used

 `data/firewall/spy.txt`

### Configuration

**Country (ex. United-States)** : N/A

**Operating system (ex. Windows 10 Pro 64 bits)** : N/A

**Winver screenshot** : N/A

**Comment by crazy-max** [comment]
Should be fixed with latest release: https://github.com/crazy-max/WindowsSpyBlocker/releases/tag/4.39.0
