### ISSUE TITLE
Cannot sign into Onedrive when using this list with Pi-hole

### ISSUE THREAD

**Issue by FrancisCarmine** [crazy-max/WindowsSpyBlocker#450]
#### Steps to reproduce this issue

1.  Add list to Gravity on Pi-hole
2. Open OneDrive in Windows
3. OneDrive fails to sign in

#### Expected behaviour

Open OneDrive and it signs in normally.

#### Actual behaviour

> Tell me what happens instead
OneDrive attempts to sign in and the following is the only DNS request is blocked by spy.txt:

db3pap004.storage.live.com
(blocked i-db3p-cor004.api.p001.1drv.com)

![image](https://user-images.githubusercontent.com/32243958/162357570-2d94a330-0b41-4449-b192-f2538dc41f9f.png)

![image](https://user-images.githubusercontent.com/32243958/162357511-6aca217f-3cda-43da-88a0-03e8cdcc4069.png)

### Rules used

> (ex: `data/firewall/spy.txt`)

1. i-db3p-cor004.api.p001.1drv.com
2.
3.

### Configuration

PiHole, Synology Docker

OneDrive on Windows 10.

**Operating system (ex. Windows 10 Pro 64 bits)** :

**Winver screenshot** :
![image](https://user-images.githubusercontent.com/32243958/162357446-74a6f026-5c8c-4377-9a16-35cc3f06a8a7.png)

> Open a command prompt and type winver then take / save the screenshot of the window and drag the image file in this issue. For example: http://bit.ly/2vA5sxR

**Comment by JourneyOver** [comment]
Found this solution while looking for the same exact problem of not being able to sign in on onedrive recently, and low and behold I had the same list enabled on my adguard home. Disabling the list solved the issue pretty much instantly.

Only thing is it was `by3301.storage.live.com` being blocked instead of

```
db3pap004.storage.live.com
(blocked i-db3p-cor004.api.p001.1drv.com)
```

**Comment by crazy-max** [comment]
Should be fixed with latest release: https://github.com/crazy-max/WindowsSpyBlocker/releases/tag/4.39.0
