### ISSUE TITLE
Feature request Lightweight version of windows spyblocker list.

### ISSUE THREAD

**Issue by blixten85** [crazy-max/WindowsSpyBlocker#454]
There is no feature request tab so i put it here instead.

I want a lightweight windows spy blocker list, where the most common applications still work, such as onedrive sync and Microsoft Edge browser data sync. Stuff that we regular users like to have and don't want to cherrypick out from the default blocklist.
There is probably more things than the two mention above that could fit into a lightweight version. 
I hope this is recieved well by the windows spy blocker staff and sympatice with my reasoning.

**Comment by rDuckDev** [comment]
For anyone that wants/needs Edge and OneDrive sync to work while using this blocklist, allowlisting the following seems to work:
```plaintext
edge.activity.windows.com
storage.live.com
```

**Comment by crazy-max** [comment]
> I want a lightweight windows spy blocker list,

Use the spy rules as explained in the docs: https://crazymax.dev/WindowsSpyBlocker/blocking-rules/
