### ISSUE TITLE
Add missing spy domains

### ISSUE THREAD

**Issue by livingentity** [crazy-max/WindowsSpyBlocker#465]
The following spy domains are already blocked by hosts but not by DNSCrypt or proxifier:
```
cy2.vortex.data.microsoft.com.akadns.net
db5.vortex.data.microsoft.com.akadns.net
geo.vortex.data.microsoft.com.akadns.net
sqm.telemetry.microsoft.com.nsatc.net
v10-win.vortex.data.microsoft.com.akadns.net
```
Please add them everywhere.

**Comment by crazy-max** [comment]
already there through wildcards.

**Comment by livingentity** [comment]
The entries are from _your_ hosts file, not anything new. I only suggest to make all your different data files (hosts, DNSCrypt, proxifier, etc.) match the same domains.

**Comment by crazy-max** [comment]
Oh indeed wildcard is missing, will fix that, thanks for your feedback.

**Comment by thatsprettygood** [comment]
Will a hotfix for this be released soon?

**Comment by livingentity** [comment]
@thatsprettygood This only affects DNSCrypt and proxifier spy rules, so it's not that urgent.

**Comment by einfacharthur** [comment]
what about this adresses?

au-v10.events.data.microsoft.com
au-v20.events.data.microsoft.com
au.vortex-win.data.microsoft.com
de-v20.events.data.microsoft.com
de.vortex-win.data.microsoft.com
eu-v10.events.data.microsoft.com
eu-v20.events.data.microsoft.com
eu.vortex-win.data.microsoft.com
events-sandbox.data.microsoft.com
events.data.microsoft.com
jp-v10.events.data.microsoft.com
jp-v20.events.data.microsoft.com
settings-win.data.microsoft.com
telecommand.telemetry.microsoft.com
uk-v20.events.data.microsoft.com
uk.vortex-win.data.microsoft.com
us-v10.events.data.microsoft.com
us-v20.events.data.microsoft.com
us.vortex-win.data.microsoft.com
us4-v20.events.data.microsoft.com
us5-v20.events.data.microsoft.com
v10.events.data.microsoft.com
v10.vortex-win.data.microsoft.com
v20.events.data.microsoft.com
v20.vortex-win.data.microsoft.com
vortex-win-sandbox.data.microsoft.com
vortex-win.data.microsoft.com
watson.*.microsoft.com

https://www.bsi.bund.de/SharedDocs/Downloads/DE/BSI/Cyber-Sicherheit/SiSyPHus/Telemetrie-Endpunkte_Windows10_Build_Build_21H2.html
