### ISSUE TITLE
Failed to resolve DNS both in IPv4&IPv6 in the NCSI test

### ISSUE THREAD

**Issue by chenxijun** [crazy-max/WindowsSpyBlocker#474]
#### Steps to reproduce this issue

1. Open WindowsSpyBlocker
2. 1-2-5 Enter the NCSI test
3. Get the result

#### Expected behaviour

> Testing DNS resolution IPv4... OK!
Testing DNS resolution IPv6... OK!

#### Actual behaviour

> Testing DNS resolution IPv4... Error: Error getting the IPv4 address of dns.msftncsi.com: read udp 192.168.0.228:60344-131.107.255.255:53: i/o timeout
Testing DNS resolution IPv6... Error: Error getting the IPv6 address of dns.msftncsi.com: read udp 192.168.0.228:60345-131.107.255.255:53: i/o timeout

<img width="592" alt="image" src="https://user-images.githubusercontent.com/16610294/177003654-93bce397-9888-4f39-8fcb-ad80e780a844.png">
However, NCSI reports that I have access to the Internet both in IPv4&IPv6

### Rules used

1.data/firewall/spy.txt
2.
3.

### Configuration

**Country (ex. United-States)** : China Mainland

**Operating system (ex. Windows 10 Pro 64 bits)** : Windows 11 Pro 21H2 64 bits

**Winver screenshot** :
<img width="422" alt="image" src="https://user-images.githubusercontent.com/16610294/177003606-c79c4d19-4bda-47e0-b2c2-7c7fde5b59cc.png">
(Forgive me for not changing the language)

**Comment by crazy-max** [comment]
We do not block Microsoft NCSI endpoints. This may be related to your router configuration. What is the result of applying Debian NCSI?
