### ISSUE TITLE
Interference with Spotify

### ISSUE THREAD

**Issue by adamsocrat** [crazy-max/WindowsSpyBlocker#476]
I applied the default IP rules, after that spotify songs went gray. I suspected IP rules because Spotify doesn't showing  offline status just couldn't playing the songs. Removed the IP rules and songs came back. (Restarted spotify for multiple times deleted cache and it was still the same when IP rules were applied)

**Comment by crazy-max** [comment]
> I applied the default IP rules

Spy rules I guess?

**Comment by adamsocrat** [comment]
Correct

**Comment by dsfargeegrafsd** [comment]
If you installed Spotify from the Windows App Store that's gonna happen. Install it from the .exe on Spotify's website.

**Comment by adamsocrat** [comment]
Probably that would solve it. Since it has been so long and can't reproduce now, I close the issue.
