### ISSUE TITLE
what windows versions are supported exactly ?

### ISSUE THREAD

**Issue by BigBroza** [crazy-max/WindowsSpyBlocker#480]
"windows systems" is a bit vague

can you specify in the description what windows versions are supported exactly

**Comment by fabestah** [comment]
Or at least tell us if Windows 11 is supported, please?

**Comment by BigBroza** [comment]
wndows 7 has telemetry as well

**Comment by crazy-max** [comment]
Windows 10/11: https://crazymax.dev/WindowsSpyBlocker/blocking-rules/#how-it-works
