### ISSUE TITLE
Why is there no light version/option to WindowsSpyBlocker?

### ISSUE THREAD

**Issue by blixten85** [crazy-max/WindowsSpyBlocker#486]
As title reads, why is there no light version/option to WindowsSpyBlocker?
Either you block it all or you block nothing. But synchronization, webhistory over edge browser and such does not work. 

I want to see a feature where a light version is added and i don't have to manually unblock the easy going of life things.

**Comment by crazy-max** [comment]
There are currently 3 [blocking rules](https://crazymax.dev/WindowsSpyBlocker/blocking-rules/). Most common one is the [Spy rules](https://crazymax.dev/WindowsSpyBlocker/blocking-rules/#spy-rules). Should be enough for most use cases.
