### ISSUE TITLE
Please update your WindowsSpyBlocker 'spy' Host

### ISSUE THREAD

**Issue by ghost** [crazy-max/WindowsSpyBlocker#510]
Hi Maxime,

Please update your spy host file.
The latest update is of: May 16, 2022.

Since 2022. Microsoft released multiple updates. And also, unfortunately with new update's on its telemetry hosts. 
As you know, new telemetry hosts can be reviewed on internet data package analyses. 
Or simple links like: 

https://learn.microsoft.com/en-us/windows/privacy/manage-windows-11-endpoints and other sources: https://view.officeapps.live.com/op/view.aspx?src=https%3A%2F%2Fwww.bsi.bund.de%2FSharedDocs%2FDownloads%2FDE%2FBSI%2FCyber-Sicherheit%2FSiSyPHus%2FTelemetrie-Endpunkte_Windows10_Build_Build_21H2.xlsx%3F__blob%3DpublicationFile%26v%3D3&wdOrigin=BROWSELINK

But also of the road trackers like: turing-writingassistance.edge.microsoft.com 

Once again please like a thorough reanalysis based on the end-2023 tracker. 

Thanks,

**Comment by crazy-max** [comment]
Duplicated of #505, see https://github.com/crazy-max/WindowsSpyBlocker/issues/505#issuecomment-1619100100
