### ISSUE TITLE
Could not run on some Windows 7 systems

### ISSUE THREAD

**Issue by AdKiller** [crazy-max/WindowsSpyBlocker#61]
#### Steps to reproduce this issue
1.  Run WindowsSpyBlocker-3.7.5\scripts\firewall\firewall.bat
or
2. Run WindowsSpyBlocker.exe 4.2.1

#### Expected Behaviour
Program should execute

#### Actual Behaviour

- Test system 1:  WindowsSpyBlocker-3.7.5

Error php.exe - System Error 
The program can't start because MSVCRI 10. dll is missing From 
your computer. Try reinstalling the program to Fix this problem. 

- Test system 1:  WindowsSpyBlocker.exe 4.2.1

The version OF this File is not compatible with the version OF Windows you're running. Check your 
computer's system information to see whether you need an x86 (32-bit) or x64 (64-bit) version OF the 
program, and then contact the software publisher 

- Test system 2:  WindowsSpyBlocker-3.7.5

**Works as expected.**

- Test system 2:  WindowsSpyBlocker.exe 4.2.1

The version OF this File is not compatible with the version OF Windows you're running. Check your 
computer's system information to see whether you need an x86 (32-bit) or x64 (64-bit) version OF the 
program, and then contact the software publisher 

#### Configuration

**Country** : ITALY

**Operating system** : 

- Test system 1:

OS Name	Microsoft Windows 7 Starter
Version	6.1.7601 Service Pack 1 Build 7601
System Type	X86-based PC
Processor	Intel(R) Atom(TM) CPU N455   @ 1.66GHz, 1666 Mhz, 1 Core(s), 2 Logical Processor(s)
**installed: 
Microsoft Visual C++ 2010  x86 Redistributable - 10.0.40219
Microsoft Visual C++ 2015 Redistributable (x86) - 14.0.23026**

- Test system 2:

OS Name	Microsoft Windows 7 Home Premium
Version	6.1.7601 Service Pack 1 Build 7601
System Type	X86-based PC
Processor	Intel(R) Pentium(R) M processor 1.50GHz, 1495 Mhz, 1 Core(s), 1 Logical Processor(s)
**Microsoft Visual C++ Redistributable NOT installed.**

**Comment by crazy-max** [comment]
Hi, thanks for your feedback, this will be solved in the next release

**Comment by crazy-max** [comment]
Solved on latest release 4.3.0
