### ISSUE TITLE
[Proposal] Promote Offline Updating in the wiki

### ISSUE THREAD

**Issue by Atavic** [crazy-max/WindowsSpyBlocker#64]
#### Promote Offline Updating here:
https://github.com/crazy-max/WindowsSpyBlocker/wiki/miscFAQ#couldnt-connect-to-the-update-service

Flame on this, but some issues like https://github.com/crazy-max/WindowsSpyBlocker/issues/62 make little sense, as a system can be updated offline, without a direct connection to MS update servers and all the included reports about system usage.

#### Tools to update offline your system:
1. [Portable Update](http://www.portableupdate.com/) is a windows-based tool for updating a Microsoft Windows computer in a isolated environment. (Simple and straightforward)
2. WSUS Offline Update: [Update Microsoft Windows and Office without an Internet connection].(http://www.wsusoffline.net/docs/) (Unofficial and powerful)
3. Official links?

**Comment by crazy-max** [comment]
Yes indeed! You give me an idea for the next release of WSB but for the moment i will update the FAQ with your ideas. Thanks!!

**Comment by crazy-max** [comment]
Done : https://github.com/crazy-max/WindowsSpyBlocker/wiki/miscFAQ#couldnt-connect-to-the-update-service
