### ISSUE TITLE
New windows watson domain, which isnt on your blocking list.

### ISSUE THREAD

**Issue by razzor1984** [crazy-max/WindowsSpyBlocker#66]
Hello, found a new domain, which isnt on your blocking list.
"modern.watson.data.microsoft.com.akadns.net"
best regards 
Razzor

**Comment by Atavic** [comment]
wineus2.ipv6.microsoft.com.akadns.net
oca.watson.data.microsoft.com.akadns.net
akampr.fullproduct.download.microsoft.com.akadns.net
api.mucp.microsoft.com.akadns.net
displaycatalogv5.md.mp.microsoft.com.akadns.net
displaycatalog-asia.md.mp.microsoft.com.akadns.net
collections-asia.md.mp.microsoft.com.akadns.net
purchase-europe.md.mp.microsoft.com.akadns.net
licensing-europe.md.mp.microsoft.com.akadns.net	
displaycatalog-europe.md.mp.microsoft.com.akadns.net
collections-europe.md.mp.microsoft.com.akadns.net
hk2.purchase.md.mp.microsoft.com.akadns.net
bn2.purchase.md.mp.microsoft.com.akadns.net
displaycatalog-europe-golive.md.mp.microsoft.com.akadns.net
displaycatalog-df.md.mp.microsoft.com.akadns.net
licensing.md.mp.microsoft.com.akadns.net
bn2.licensing.md.mp.microsoft.com.akadns.net
cy2.licensing.md.mp.microsoft.com.akadns.net
db5.licensing.md.mp.microsoft.com.akadns.net
displaycatalog.md.mp.microsoft.com.akadns.net
hk2.displaycatalog.md.mp.microsoft.com.akadns.net
bn2.displaycatalog.md.mp.microsoft.com.akadns.net
cy2.displaycatalog.md.mp.microsoft.com.akadns.net
db5.displaycatalog.md.mp.microsoft.com.akadns.net
collections.md.mp.microsoft.com.akadns.net
hk2.collections.md.mp.microsoft.com.akadns.net
db5.collections.md.mp.microsoft.com.akadns.net
licensing-useast.md.mp.microsoft.com.akadns.net
displaycatalog-useast.md.mp.microsoft.com.akadns.net
purchase-uswest.md.mp.microsoft.com.akadns.net
licensing-uswest.md.mp.microsoft.com.akadns.net
displaycatalog-uswest.md.mp.microsoft.com.akadns.net
collections-uswest.md.mp.microsoft.com.akadns.net
livetileedge.dsx.mp.microsoft.com.akadns.net
officecdn15.c2r.microsoft.com.akadns.net
officecdn15-worldwide.c2r.microsoft.com.akadns.net
officecdn15-rotw.c2r.microsoft.com.akadns.net
continuum.dds.microsoft.com.akadns.net
cs.dds.microsoft.com.akadns.net
dmd.metaservices.microsoft.com.akadns.net
download.dmd.metaservices.microsoft.com.akadns.net
gamesudf.metaservices.microsoft.com.akadns.net
redir.metaservices.microsoft.com.akadns.net
origin.redir.metaservices.microsoft.com.akadns.net
prod.fs.microsoft.com.akadns.net	
origin.windows.microsoft.com.akadns.net
origin-res.windows.microsoft.com.akadns.net
s-origin-res.windows.microsoft.com.akadns.net
hs.windows.microsoft.com.akadns.net
rssgov.windows.microsoft.com.akadns.net
cdn.account.microsoft.com.akadns.net
ux.account.microsoft.com.akadns.net

**Comment by Atavic** [comment]
[Here](https://www.threatcrowd.org/domain.php?domain=modern.watson.data.microsoft.com.akadns.net) is the source for the subdomains list.

**Comment by crazy-max** [comment]
Thanks, i will take a look at this list

**Comment by Atavic** [comment]
It's a long list and most of the urls are freshly created. They are potential adversaries for the future.

**Comment by crazy-max** [comment]
@Atavic Ofc

**Comment by crazy-max** [comment]
@razzor1984 @Atavic I prefer to continue using packet capture to trigger new probes rather than adding domains without being sure of not impacting the user environment. Anyway I keep this list aside. Thanks
