### ISSUE TITLE
Office template downloads blocked

### ISSUE THREAD

**Issue by Gittyperson** [crazy-max/WindowsSpyBlocker#67]
Something in data/firewall/win10/spy.txt is blocking the Office online template downloads. Disabling those rules makes it work again. Not using any other rules, Windows 10 x64 (1703 / 15063.413).

![office](https://user-images.githubusercontent.com/7165208/27596471-58b63226-5b68-11e7-98d5-3f14e1c6a88b.jpg)

**Comment by Atavic** [comment]
I'd suggest to download all the templates you need first, then apply this blocker list.

You can download templates with another PC then import them from [here](https://templates.office.com/).

**Comment by crazy-max** [comment]
Hi,

Ok thanks for your feedback, i will investigate on this issue.

**Comment by crazy-max** [comment]
The ip address involved seems to be `23.97.178.173` linked to `officeclient.micrososft.com`, can you remove this IP from your firewall and try again @Gittyperson ?

**Comment by Gittyperson** [comment]
Don't know how to clear the already downloaded template lists, but it seems to work now (without making your proposed change), I tested some other categories that tried -and succeeded- to download stuff.

If it happens again, I'll remove that IP and post back.

**Comment by crazy-max** [comment]
@Gittyperson Ok thanks but i'm pretty sure this IP class is concerned : https://www.threatcrowd.org/ip.php?ip=23.97.178.173 ;)

**Comment by crazy-max** [comment]
Solved in 4.7.1
