### ISSUE TITLE
Add p2p data format

### ISSUE THREAD

**Issue by crazy-max** [crazy-max/WindowsSpyBlocker#69]
Add the [P2P data format](https://en.wikipedia.org/wiki/PeerGuardian#P2P_plaintext_format).
Can be used with [PeerBlock](https://sourceforge.net/projects/peerblock), [PeerGuardian](http://sourceforge.net/projects/peerguardian/), [iplist](http://iplist.sourceforge.net/) and many others.
Would be interesting to add WindowsSpyBlocker rules to [I-BlockList](https://www.iblocklist.com/) as well.

**Comment by crazy-max** [comment]
Solved in 4.7.1

**Comment by Atavic** [comment]
Just a note: 

By Peerblock standards the beginning of every string contains the owner's name of the IP list.
By this standard `WindowsSpyBlocker:` means that those IP fall under the evil WindowsSpyBlocker Corp. (which are not)

Nice work, btw

**Comment by crazy-max** [comment]
@Atavic You right, but if we take for example the [cruzit web attacks](https://www.iblocklist.com/list?list=czvaehmjpsnwwttrdoyl) list, it's a *Individual IP addresses of compromised machines scanning for vulnerabilities and DDOS attacks.*. If you download this list, you can see the owner is the same string `cruzit blocked`.
So for WindowsSpyBlocker it seems normal to apply the same principle. But I could solve each IP address and apply the actual organization indeed ;)

**Comment by Atavic** [comment]
Didn't know about that list. So, the problem is non-existent.
