### ISSUE TITLE
Windows Update was blocked unintentional.

### ISSUE THREAD

**Issue by ShrimpBFM** [crazy-max/WindowsSpyBlocker#7]
Hello.

So I did every step from your instructions on **Windows 10 64bit** except "DNSCrypt" and "Proxifier". I did not do those two.

When I did the Hosts-File,
I only used the "**windowsX_spy.txt**" and "**windowsX_extra.txt**".
I **_did not_** use "**windowsX_update.txt**", as I still want to receive updates.

Now, when I go to _Settings/Update&Security/Windows Update_  and then click on "Check for updates",
it only takes about 1 second before the following message appears:

"**We couldn't connect to the update service. We'll try again later, or you can check now. If it still doesn't work, make sure you're connected to the Internet.**"

I never had this before.

So what could I do to still be able to receive Updates?

**Comment by crazy-max** [comment]
If you apply firewall rules, remove them and try to search for windows updates.
I will investigate on this issue.

**Comment by ShrimpBFM** [comment]
Hello and thanks for the response!

Turning off the Windows Firewall helped.

Thank you, you are awesome!

**Comment by crazy-max** [comment]
Ok so there is a problem in the latest release of firewall rules
Thanks for your support :)

**Comment by crazy-max** [comment]
@ShrimpBFM Can you give me a screenshot of your winver (<kbd>WIN</kbd>+<kbd>R</kbd> and type `winver`) ?

**Comment by ShrimpBFM** [comment]
![new bitmap image](https://cloud.githubusercontent.com/assets/19552753/15555182/e5c5fa5a-22c7-11e6-87f8-df29b599ae5b.jpg)

**Comment by crazy-max** [comment]
Solved on 2.7
