### ISSUE TITLE
No windows update after Win10 Creators update

### ISSUE THREAD

**Issue by bup4gr** [crazy-max/WindowsSpyBlocker#70]
In windows 10 pro after the creators update i got error 0x800704cf when i try to update windows.
This problem is with version 4.6.1 and win10 spy and win10 extra rules installed in firewall

Before the creators update i have no problem.
After creators update error 0x800704cf.

I try to uninstall all rules and windows update works.
I try to install only win10 spy rules and windows update works.

So i think there is a rule in win10 extra that block the updates of win10 after creators update.

**Comment by crazy-max** [comment]
Hi @bup4gr,

Extra rules are intended only for advertised users.
Basically, extra is a "misc" category for unknown probes from Windows.
I will add more info in the README about that but for now, there is only support for spy rules.
Anyway thanks for your support!
