### ISSUE TITLE
Windows store icon is always blue

### ISSUE THREAD

**Issue by skipik** [crazy-max/WindowsSpyBlocker#71]
#### Please first
* Read the FAQ : https://github.com/crazy-max/WindowsSpyBlocker/wiki/FAQ
* Search for existing issues : https://github.com/crazy-max/WindowsSpyBlocker/issues

#### Steps to reproduce this issue
1. Open Start Menu
2. Look at Win Store icon
3.

#### Expected Behaviour
I should see some apps or games pictures on the win store icon

#### Actual Behaviour
I always see only blue win store icon

#### Configuration

**Country (ex. United-States)** : Russia

**Operating system (ex. Windows 10 Pro 64 bits)** : Windows 10 Pro x64 v1703

**Winver screenshot** : 
![winstore](https://user-images.githubusercontent.com/24621645/27763314-1a966c84-5e8a-11e7-867b-c86e3eb7377e.png)
![winver](https://user-images.githubusercontent.com/24621645/27763315-1a978542-5e8a-11e7-91aa-1ab44af7f568.png)

```
Open a command prompt and type winver then
take / save the screenshot of the window and
drag the image file in this issue.
For example: https://goo.gl/03d7gI
```
I use Spy lists for Win10 on my router.

**Comment by Atavic** [comment]
Try adding # to this line [here](https://github.com/crazy-max/WindowsSpyBlocker/blob/cd2e705ffe320c3c12017bbecc99e19481d3bc4e/data/hosts/win10/extra.txt#L42).

**Comment by skipik** [comment]
@Atavic Thanks, but I use only spy.txt list.

**Comment by Atavic** [comment]
I see something with store [here](https://github.com/crazy-max/WindowsSpyBlocker/blob/cd2e705ffe320c3c12017bbecc99e19481d3bc4e/data/hosts/win10/spy.txt#L226).

**Comment by skipik** [comment]
@Atavic Nope. It didn't help. I use [these](https://github.com/crazy-max/WindowsSpyBlocker/tree/cd2e705ffe320c3c12017bbecc99e19481d3bc4e/data/openwrt/win10/spy) lists btw (both).

**Comment by crazy-max** [comment]
@skipik I cannot display apps or games pictures even if i remove all the win10 spy rules.
Can you post a screenshot of the expected behaviour plz ?

**Comment by skipik** [comment]
@crazy-max I think you have to reboot your PC after deleting those entries. It was fine untill I added the spy rules.

**Comment by crazy-max** [comment]
@skipik Ok but can you post a screenshot when it works ? Thx.

**Comment by skipik** [comment]
@crazy-max I can't reproduce it now. May be MS changed something. I'll try to investigate it and keep you in touch.

**Comment by crazy-max** [comment]
@skipik Ok thx

**Comment by crazy-max** [comment]
@skipik If you have more info reopen this issue.
