### ISSUE TITLE
Skype doesn't work

### ISSUE THREAD

**Issue by skipik** [crazy-max/WindowsSpyBlocker#72]
#### Please first
* Read the FAQ : https://github.com/crazy-max/WindowsSpyBlocker/wiki/FAQ
* Search for existing issues : https://github.com/crazy-max/WindowsSpyBlocker/issues

#### Steps to reproduce this issue
1. Open Skype from modern applications
2. 
3.

#### Expected Behaviour
You should be connected

#### Actual Behaviour
It always says to me "Connecting..."

#### Configuration

**Country (ex. United-States)** : Russia

**Operating system (ex. Windows 10 Pro 64 bits)** : Windows 10 Pro x64 v1703

**Winver screenshot** : 
![skype](https://user-images.githubusercontent.com/24621645/27763368-2d847ff6-5e8b-11e7-899d-f3ab8d474bc0.png)
![winver](https://user-images.githubusercontent.com/24621645/27763369-2d88356a-5e8b-11e7-8496-9af77d56ec67.png)

```
Open a command prompt and type winver then
take / save the screenshot of the window and
drag the image file in this issue.
For example: https://goo.gl/03d7gI
```
I use Spy lists for Win10 on my router.

**Comment by crazy-max** [comment]
Hi @skipik,

I cannot reproduce your issue using the win10 spy rules (domains and ips).
And in your screenshot you are connected, no ?
Can you post a screenshot of your "Connecting..." loop ?

Thanks

**Comment by skipik** [comment]
@crazy-max I already did. Look at my screenshot. "Подключение..." means "Connecting...". And no, I'm not connected with those rules. The issue is gone when I removed everything from my router.

**Comment by timofonic** [comment]
@skipik 

What's the point of this issue then? The ideal way would be to check why it happens. Please take some patience, maybe @crazy-max could discover why it's happening with some feedback (checking where Skype connects to, for example) :)

**Comment by crazy-max** [comment]
@skipik I've checked with the latest firewall and host win10 spy rules (4.8.1) and everything works fine on Windows 10 Pro v1703 15063.483 :

![skype](https://user-images.githubusercontent.com/1951866/28248333-6dfc69e0-6a43-11e7-8202-31ce33f3aec5.png)
