### ISSUE TITLE
Pointed to this repo on asuswrt-merlin

### ISSUE THREAD

**Issue by Atavic** [crazy-max/WindowsSpyBlocker#74]
@RMerl has nice wiki pages that link to [DisableWinTracking](https://github.com/10se1ucgo/DisableWinTracking).

I did a little push to @crazy-max hard work there, as the wiki cite an IP spy list that's now outdated.

See: https://github.com/RMerl/asuswrt-merlin/issues/1454

**Comment by Atavic** [comment]
Positive feedback received. My only problem is that ASUS has the TPM chips embedded. The Trusted Platform Module is an hardware solution for enterprise (not needed for my home LAN) that's running at low level (not seen by the OS) and opens the system to potential backdoors.

**Comment by Atavic** [comment]
Positive feedback received. My only problem is that ASUS has the TPM chips embedded. The Trusted Platform Module is an hardware solution for enterprise (not needed for my home LAN) that's running at low level (not seen by the OS). It opens the system to potential backdoors.

**Comment by crazy-max** [comment]
Thanks for your contrib @Atavic 
Maybe you can add a link to the dnsmasq config in their Wiki section ?

**Comment by Atavic** [comment]
Added a little section [here](https://github.com/RMerl/asuswrt-merlin/wiki/Legacy-Ipset-Scripts#windows-spy-blocker).

**Comment by crazy-max** [comment]
Great thanks
