### ISSUE TITLE
Allow using nested data folder

### ISSUE THREAD

**Issue by crile** [crazy-max/WindowsSpyBlocker#75]
Hi, thanks for this program.
Is there a way to modify manually the rules ?
Like copy the "data" directory in the same directory than the executable ?

**Comment by Atavic** [comment]
To manually customize the firewall rules, you can modify the files in these [folders](https://github.com/crazy-max/WindowsSpyBlocker/tree/master/data/firewall) before running the executable.

**Comment by crazy-max** [comment]
@crile @Atavic Files in `data` folder are embedded in the executable. But i can implement a new feature to use the data folder if it exists.

**Comment by crile** [comment]
Ok, thanks. I think it can be a good feature without too much trouble to develop (I know nothing about go language :'(, else I could do it myself)

**Comment by crazy-max** [comment]
@crile With latest release (4.12.0) you can extract the current data and use your own :

![image](https://user-images.githubusercontent.com/1951866/37940053-de100e4a-3166-11e8-9216-f68070fdbd9a.png)

To use the data in the nested folder, you have to set option `useEmbeddedData` to false in [app.conf](https://github.com/crazy-max/WindowsSpyBlocker/blob/master/app.conf#L4).
