### ISSUE TITLE
The list isn't full

### ISSUE THREAD

**Issue by sudosusudo** [crazy-max/WindowsSpyBlocker#77]
Hello. I want offer to you entire list of MS telemetry servers. It would be great if you implement new records to your software.
I copied from hosts file with "127.0.0.1", but I think you will decide what to do with that list)

127.0.0.1  dns.msftncsi.com
127.0.0.1  ipv6.msftncsi.com
127.0.0.1  win10.ipv6.microsoft.com
127.0.0.1  ipv6.msftncsi.com.edgesuite.net
127.0.0.1  a978.i6g1.akamai.net
127.0.0.1  win10.ipv6.microsoft.com.nsatc.net
127.0.0.1  en-us.appex-rf.msn.com
127.0.0.1  v10.vortex-win.data.microsoft.com
127.0.0.1  client.wns.windows.com
127.0.0.1  wildcard.appex-rf.msn.com.edgesuite.net
127.0.0.1  v10.vortex-win.data.metron.life.com.nsatc.net
127.0.0.1  wns.notify.windows.com.akadns.net
127.0.0.1  americas2.notify.windows.com.akadns.net
127.0.0.1  travel.tile.appex.bing.com
127.0.0.1  any.edge.bing.com
127.0.0.1  fe3.delivery.mp.microsoft.com
127.0.0.1  fe3.delivery.dsp.mp.microsoft.com.nsatc.net
127.0.0.1  ssw.live.com
127.0.0.1  ssw.live.com.nsatc.net
127.0.0.1  login.live.com.nsatc.net
127.0.0.1  directory.services.live.com
127.0.0.1  directory.services.live.com.akadns.net
127.0.0.1  bl3302.storage.live.com
127.0.0.1  skyapi.live.net
127.0.0.1  bl3302geo.storage.dkyprod.akadns.net
127.0.0.1  skyapi.skyprod.akadns.net
127.0.0.1  skydrive.wns.windows.com
127.0.0.1  register.mesh.com
127.0.0.1  BN1WNS2011508.wns.windows.com
127.0.0.1  settings-win.data.microsoft.com
127.0.0.1  settings.data.glbdns2.microsoft.com
127.0.0.1  OneSettings-bn2.metron.live.com.nsatc.net
127.0.0.1  watson.telemetry.microsoft.com
127.0.0.1  watson.telemetry.microsoft.com.nsatc.net
127.0.0.1  vortex.data.microsoft.com
127.0.0.1  vortex-win.data.microsoft.com
127.0.0.1  telecommand.telemetry.microsoft.com
127.0.0.1  telecommand.telemetry.microsoft.com.nsatc.net
127.0.0.1  oca.telemetry.microsoft.com
127.0.0.1  oca.telemetry.microsoft.com.nsatc.net
127.0.0.1  sqm.telemetry.microsoft.com
127.0.0.1  sqm.telemetry.microsoft.com.nsatc.net
127.0.0.1  redir.metaservices.microsoft.com
127.0.0.1  choice.microsoft.com
127.0.0.1  choice.microsoft.com.nsatc.net
127.0.0.1  df.telemetry.microsoft.com
127.0.0.1  reports.wes.df.telemetry.microsoft.com
127.0.0.1  wes.df.telemetry.microsoft.com
127.0.0.1  services.wes.df.telemetry.microsoft.com
127.0.0.1  sqm.df.telemetry.microsoft.com
127.0.0.1  telemetry.microsoft.com
127.0.0.1  watson.ppe.telemetry.microsoft.com
127.0.0.1  telemetry.appex.bing.net
127.0.0.1  telemetry.urs.microsoft.com
127.0.0.1  telemetry.appex.bing.net:443
127.0.0.1  settings-sandbox.data.microsoft.com
127.0.0.1  vortex-sandbox.data.microsoft.com
127.0.0.1  survey.watson.microsoft.com
127.0.0.1  watson.live.com
127.0.0.1  watson.microsoft.com
127.0.0.1  statsfe2.ws.microsoft.com
127.0.0.1  corpext.msitadfs.glbdns2.microsoft.com
127.0.0.1  compatexchange.cloudapp.net
127.0.0.1  cs1.wpc.v0cdn.net
127.0.0.1  a-0001.a-msedge.net
127.0.0.1  statsfe2.update.microsoft.com.akadns.net
127.0.0.1  sls.update.microsoft.com.akadns.net
127.0.0.1  fe2.update.microsoft.com.akadns.net
127.0.0.1  diagnostics.support.microsoft.com
127.0.0.1  corp.sts.microsoft.com
127.0.0.1  statsfe1.ws.microsoft.com
127.0.0.1  pre.footprintpredict.com
127.0.0.1  i1.services.social.microsoft.com
127.0.0.1  i1.services.social.microsoft.com.nsatc.net
127.0.0.1  feedback.windows.com
127.0.0.1  feedback.microsoft-hohm.com
127.0.0.1  feedback.search.microsoft.com
127.0.0.1  preview.msn.com
127.0.0.1  ad.doubleclick.net
127.0.0.1  ads.msn.com
127.0.0.1  ads1.msads.net
127.0.0.1  a.ads1.msn.com
127.0.0.1  a.ads2.msn.com
127.0.0.1  adnexus.net
127.0.0.1  adnxs.com
127.0.0.1  az361816.vo.msecnd.net
127.0.0.1  az512334.vo.msecnd.net

**Comment by crazy-max** [comment]
Hi,

I will take a look on your list but do you have a source for it ?
Thanks for your contrib!

**Comment by sudosusudo** [comment]
I'm sorry, but I can't tell you exactly where I found that list, I can't remember. There are is a lot of similar list in Internet, some of them are smaller, some are bigger.

**Comment by crazy-max** [comment]
Ok i keep your list aside for the moment

**Comment by ltGuillaume** [comment]
https://github.com/W4RH4WK/Debloat-Windows-10/blob/master/scripts/block-telemetry.ps1
https://github.com/10se1ucgo/DisableWinTracking/blob/master/dwt.py

**Comment by ltGuillaume** [comment]
The results from these two compared with your hosts:

# These are not present
184-86-53-99.deploy.static.akamaitechnologies.com
a1621.g.akamai.net
a1856.g2.akamai.net
a248.e.akamai.net
a978.i6g1.akamai.net
any.edge.bing.com
choice.microsoft.com.nstac.net
e2835.dspb.akamaiedge.net
e7341.g.akamaiedge.net
e7502.ce.akamaiedge.net
spynet.microsoft.com
www.go.microsoft.akadns.net

# Present here in firewall-test-extra or hosts-count
a1961.g.akamai.net
cy2.vortex.data.microsoft.com.akadns.net
e8218.ce.akamaiedge.net
hostedocsp.globalsign.com
msnbot-65-55-108-23.search.msn.com

# Only NCSI related
ipv6.msftncsi.com
ipv6.msftncsi.com.edgesuite.net

# Without .com. in between
onesettings-db5.metron.live.nsatc.net

# Only present without www.
www.bingads.microsoft.com

# Present only in -update
fe2.update.microsoft.com.akadns.net
sls.update.microsoft.com.akadns.net
statsfe1.ws.microsoft.com
statsfe2.update.microsoft.com.akadns.net
statsfe2.ws.microsoft.com

# Irrelevant
ad.doubleclick.net

**Comment by sudosusudo** [comment]
You've done great work!
But problem is in fact that M$ can edit or add new telemetry servers with every update...

**Comment by ltGuillaume** [comment]
Thanks. Just to be completely clear on this: I only compared the entries from the two URLs I provided with the entries present in WindowsSpyBlocker's repo. I did not compare your list.
