### ISSUE TITLE
Difference between extra and update?

### ISSUE THREAD

**Issue by Skrell** [crazy-max/WindowsSpyBlocker#78]
Can someone please describe the differences between the various lists?  My Win8.1 update no longer works and as far as I know I never used the update.txt block list...   Just hoping to better understand what this awesome tool does.

**Comment by crazy-max** [comment]
Hi @Skrell,

* data/<type>/winX/spy.txt : Block Windows Spy / Telemetry
* data/<type>/winX/update.txt : Block Windows Update
* data/<type>/winX/extra.txt : Block third party applications from Microsoft like Skype, OneDrive, Live, etc...

**Comment by Skrell** [comment]
Thank you!!! Please post this in the readme ! :) LOVE YOUR WORK

**Comment by crazy-max** [comment]
It is in the README :

![image](https://user-images.githubusercontent.com/1951866/31717973-679c6d6a-b40e-11e7-802d-9ae7fefefb66.png)

And thanks for your support ;)

**Comment by meffect** [comment]
When I did `spy`, no probz. When I did `spy` + `extra` , windows update no longer worked.

**Comment by crazy-max** [comment]
Yes this issue is already known : #80
