### ISSUE TITLE
Extra Rules block Windows Update

### ISSUE THREAD

**Issue by Ar1sC** [crazy-max/WindowsSpyBlocker#80]
When I add extra rules it blocks Windows Update.

Steps I Followed..
Download 4.9
Remove every Rule
Add Spy Rules... Windows Update works.
Add Extra Rules... No More...

**Comment by crazy-max** [comment]
Hi @Ar1sC,

Hosts or Firewall rules ?

And please read the [SUPPORT](https://github.com/crazy-max/WindowsSpyBlocker/blob/master/.github/SUPPORT.md) page before reporting an issue.

**Comment by Ar1sC** [comment]
Firewall Rules
Windows 10 64bit
Screenshots.
https://imgur.com/a/zPKmX

**Comment by crazy-max** [comment]
Ok thanks for your feedback, i'll keep you in touch

**Comment by crazy-max** [comment]
Fyi, here the diff with the previous release : https://github.com/crazy-max/WindowsSpyBlocker/commit/2dff7e53a43bf070933a244de7840fe20007a253#diff-3058f7bf422d9f6c5e3e505e858f6ba2

**Comment by Atavic** [comment]
Related to: https://github.com/crazy-max/WindowsSpyBlocker/issues/62

**Comment by crazy-max** [comment]
@Ar1sC I cannot reproduce your issue, can you check and remove one by one these IPs :

```
40.77.224.11
40.90.136.20
40.101.46.178
157.55.134.136
157.55.134.138
157.55.134.140
157.55.135.128
204.152.141.244
```

And tell me if one of them block Windows Update

Thanks

**Comment by Ar1sC** [comment]
I was trying to update with Spy Rules and it didn't work. After many clicks on update button.. it worked... then I added extra rules and Im getting version 1709....

**Comment by crazy-max** [comment]
@Ar1sC Oh so the extra rules are not related with your issue but the spy ones ?

**Comment by Ar1sC** [comment]
After 1709 (OS Build 16299.19) I didn't encounter any problem with Spy & Extra Rules....

**Comment by crazy-max** [comment]
Ok will see in the next update of WSB ;)
