### ISSUE TITLE
Vetted against new windows 10 RTM released today, 1709 build is 16299.15 ?

### ISSUE THREAD

**Issue by meffect** [crazy-max/WindowsSpyBlocker#81]
Has this been confirmed working against new windows 10 RTM released today, 1709 build is 16299.15 ?

**Comment by meffect** [comment]
I found this [website](http://sihmar.com/) has good info if you want to upgrade before windows update presents

You can probably download the iso's by now, but learning [esd](http://sihmar.com/download-windows-10-build-16299-15-esd-files-direct-links/) + [decrypt-multi-release](https://rg-adguard.net/decrypt-multi-release/) [directions](http://sihmar.com/how-to-convert-windows-10-esd-to-iso/) was worthwhile, as it is preferable to downloading the iso in some cases, like earlier when the ISO's were only 3rd party created with no CRC's

**Comment by meffect** [comment]
just fyi, looks like Microsoft released a patch already, moving build to from 16299.15 to [16299.19](http://sihmar.com/kb4043961-windows-10-v1709-changelog/)

**Comment by meffect** [comment]
also in 16299.15, insider program now has a nice option called [Just fixes, apps, and drivers](https://askwoody.com/2017/how-to-get-the-latest-version-of-win10-fall-creators-update-version-1709-build-16299-19/) , which is currently the only way to get the 16299.**19** patch, the official way

**Comment by crazy-max** [comment]
No, Windows machines used for WindowsSpyBlocker are not part of the Insider Preview program.

**Comment by meffect** [comment]
@crazy-max Crazy! I see what happened, I put so much amazing information that it got lost in translation! Windows 10 Version 1709 Build 16299.15 (or 16299.19) AKA "Redstone 3" was officially released to the non insider preview program public yesterday, 2017-10-17. I mentioned insider program previous to educate the audience of the fact that there now is a much safer insider branch that can be chosen in this new production version of windows, called `Just fixes, apps, and drivers`

**Comment by crazy-max** [comment]
Yep indeed, virtual machines for WindowsSpyBlocker have been updated yesterday to 16299.19 ;)
