### ISSUE TITLE
Use UPX compression

### ISSUE THREAD

**Issue by crazy-max** [crazy-max/WindowsSpyBlocker#83]

**Comment by ctd1500** [comment]
@crazy-max Continuing here if you don't mind (https://github.com/golang/go/issues/16706#issuecomment-337862284)

I use ConEmu as my standard command line shell, so it captures cli apps and puts them in a tab automatically.  What I saw as somewhat unusual from WindowsSpyBlocker is that when you open it by double clicking, it opens in conemu momentarily, then it breaks out a second separate command line window.

An example recording showing what happens with a simple cli I made, compared to what happens with WindowsSpyBlocker: https://youtu.be/5FLQCYKgJys

**Comment by crazy-max** [comment]
@ctd1500 Thanks for your input!
I think i've made a mistake with the ldflags

**Comment by Atavic** [comment]
Pros and Cons by using UPX: https://github.com/crazy-max/WindowsSpyBlocker/issues/84#issuecomment-338501815
