### ISSUE TITLE
10-HUT Hosts Updating Tool

### ISSUE THREAD

**Issue by ltGuillaume** [crazy-max/WindowsSpyBlocker#84]
For what it's worth, since I didn't like HostsMan much, I had a look and found this thing: it'll just download the list(s) you want and merge them with hosts. Use a scheduled task to periodically run it (batch file to create such a task is included).

Pros:
- Portable
- Nothing permanently running
- .ini-file to choose spy/extra/update (it'll check for win7/8.1/10 automatically)
- 10 Custom lists can be added
- No prompts, unless something goes wrong
- Creates a backup if any changes are to be made
- Keeps the downloaded lists for comparison, if you want

Cons:
- Won't delete hosts that were dropped from the list

[10-HUT.zip](https://github.com/crazy-max/WindowsSpyBlocker/files/1404081/10-HUT.zip)

**Comment by Atavic** [comment]
VT: https://www.virustotal.com/en/file/f5458d806ff57dfaab44987c216ea4bfb4a2796d86d2a01b4f3e935faabb63cf/analysis/1508627216/

Detection ratio: 	11 / 66

**Comment by ltGuillaume** [comment]
It's packed with UPX, that triggers some stupid AV's, results are already different if unpacked. And it changes the hosts file, some heuristics will pick up on such behavior, that's all.

**Comment by ltGuillaume** [comment]
Ran it in a virtual machine with Process Monitor and Regshot: it runs for mere second(s) and touches only the hosts file.

**Comment by Atavic** [comment]
Seems legit, Kaspersky doesn't flag it. Once unpacked the detection rate is: 8/66

@crazy-max be aware of false positives with UPX.

**Comment by ltGuillaume** [comment]
Did some Wiresharking, too (about 50 runs of 10-HUT). Only contacts the download locations, nothing else.

**Comment by crazy-max** [comment]
Hi @ltGuillaume,

Thanks for your input
Your features sound great and i have some ideas to implement some of them in WSB like:

* Auto check the operating system
* Add non-interactive mode (pass args to WSB exe)
* Rollback feature
* Archive old rules

What do you think ?

**Comment by ltGuillaume** [comment]
Sounds fantastic! As soon as command line arguments are implemented, you could also allow people to create an auto-update task from within the program. :)

**Comment by crazy-max** [comment]
> As soon as command line arguments are implemented, you could also allow people to create an auto-update task from within the program.

Exactly!

I will create separate issues for each feature and close this one.
