### ISSUE TITLE
Project

### ISSUE THREAD

**Issue by BBcan177** [crazy-max/WindowsSpyBlocker#85]
Hi, Would you consider adding pfBlockerNG as a project?  Thanks!
    https://forum.pfsense.org/index.php?topic=102470.0

**Comment by Atavic** [comment]
That's for pfSense. PFSense is mainky used for host servers, while this repo deals with single machines running browsers (and other clients) and doesn't need to block spammers.

**Comment by Atavic** [comment]
That's for pfSense. PFSense is mainly used for host servers, while this repo deals with single machines running browsers (and other clients) and doesn't need to block spammers.

**Comment by BBcan177** [comment]
Yes pfSense is an open source firewall. 

I am the dev of pfBlockerNG and it is an IP and Domain management package to block malicious IPs, Domains, ADverts, Telemetry etc etc... The Host files are compatible with the package. Refer to the link above for more details about the package.

**Comment by crazy-max** [comment]
Hi @BBcan177,

Thanks for your interest in WSB!
Do you have an official website or a repository link (github / bitbucket / ...) for your app other than a forum post please ?

**Comment by BBcan177** [comment]
Unfortunately not at this time.  Work in progress tho.

The Forum link is the best for now.

The Github page is  here tho: 
    https://github.com/pfsense/FreeBSD-ports/blob/devel/net/pfSense-pkg-pfBlockerNG/pkg-descr

**Comment by Atavic** [comment]
So, by looking [here](https://forum.pfsense.org/index.php?PHPSESSID=gg8f8gck3vooo3t44hvqg3kp82&topic=86212.0) **pfBlockerNG** is an IP Download manager and it can download hosts files.

@BBcan177 are you asking for pfBlockerNG to be included in the list [here](https://github.com/crazy-max/WindowsSpyBlocker#projects-using-windowsspyblocker) ?

**Comment by BBcan177** [comment]
@Atavic - See my first post showing v2 which includes DNSBL.    And yes, if possible...

**Comment by Atavic** [comment]
- pfBlockerNG : An IP Download manager based on pfSense firewall.

@crazy-max should add

**Comment by Atavic** [comment]
- pfBlockerNG : An IP Download manager based on pfSense firewall.

@crazy-max should add it [here](https://github.com/crazy-max/WindowsSpyBlocker#projects-using-windowsspyblocker).

**Comment by Atavic** [comment]
Which is the official page for pfBlockerNG?

**Comment by crazy-max** [comment]
@BBcan177 As I can see, pfBlockerNG is [a package of pfSense](https://doc.pfsense.org/index.php/Package_list).

The [Github link](https://github.com/pfsense/FreeBSD-ports/blob/devel/net/pfSense-pkg-pfBlockerNG/pkg-descr) you posted does not contain any reference of WindowsSpyBlocker. On the other hand, I found a [commit on the repository](https://github.com/pfsense/FreeBSD-ports/commit/435585fa380d5165e5187c30c5ee6bca1d6fcc76) mentioning WindowsSpyBlocker which seems to be linked to the [FreeBSD void-zones-tools package](https://github.com/cyclaero/void-zones-tools) by @cyclaero.

If you want your project to appear in the [list of related projects](https://github.com/crazy-max/WindowsSpyBlocker#projects-using-windowsspyblocker) you need a reference to WindowsSpyBlocker. Do you have one ? Thanks.

**Comment by cyclaero** [comment]
> Am 14.11.2017 um 19:14 schrieb CrazyMax <notifications@github.com>:
> 
> @BBcan177 <https://github.com/bbcan177> As I can see, pfBlockerNG is a package of pfSense <https://doc.pfsense.org/index.php/Package_list>.
> 
> The Github link <https://github.com/pfsense/FreeBSD-ports/blob/devel/net/pfSense-pkg-pfBlockerNG/pkg-descr> you posted does not contain any reference of WindowsSpyBlocker. On the other hand, I found a commit on the repository <https://github.com/pfsense/FreeBSD-ports/commit/435585fa380d5165e5187c30c5ee6bca1d6fcc76> mentioning WindowsSpyBlocker which seems to be linked to the FreeBSD void-zones-tools package <https://github.com/cyclaero/void-zones-tools> by @cyclaero <https://github.com/cyclaero>.
> 
> If you want your project to appear in the list of related projects <https://github.com/crazy-max/WindowsSpyBlocker#projects-using-windowsspyblocker> you need a reference to WindowsSpyBlocker. Do you have one ? Thanks.
> 
Hello,

I am the developer of the void-zones-tools <https://github.com/cyclaero/void-zones-tools>. WindowsSpyBlocker is mentioned in the list of hosts file providers in the description on the project site on GitHub. See screenshot below.

Best regards

Rolf Jansen

**Comment by crazy-max** [comment]
@cyclaero,

Hello Rolf, we misunderstood each other.
I was talking to @BBcan177 in this discussion (https://github.com/crazy-max/WindowsSpyBlocker/issues/85) so that he would mention WindowsSpyBlocker if it was included in his project by taking yours as an example.

**Comment by cyclaero** [comment]
Ah, OK, sorry.

I didn't follow this thread. I suddenly received an e-mail message from GitHub because my user name was mentioned in a message, and I answered to this by e-mail. BTW, I would be glad if you would consider to add the [void-zones-tools](https://github.com/cyclaero/void-zones-tools) to your list Projects using WindowsSpyBlocker.

**Comment by crazy-max** [comment]
No problem @cyclaero and yes i will add your project ;)

**Comment by crazy-max** [comment]
@cyclaero, void-zones-tools has been added
@BBcan177, i close this issue. Reopen it when you have the information I [mentioned above](https://github.com/crazy-max/WindowsSpyBlocker/issues/85#issuecomment-344400515). Thanks
