### ISSUE TITLE
Microsoft.photos.exe 

### ISSUE THREAD

**Issue by mscreenie** [crazy-max/WindowsSpyBlocker#90]
After updating yesterday, today Windows decided to call home randomly whilst I watched YouTube.

![untitled](https://user-images.githubusercontent.com/11147410/32803099-5cf171f4-c97a-11e7-8e2e-d818fa503a90.png)

How do I add these hosts here?

**Comment by crazy-max** [comment]
Hi @mscreenie, a new version of WSB will be released this week. I'll let you know if these addresses have been detected.

**Comment by Atavic** [comment]
[threatcrowd](https://www.threatcrowd.org/domain.php?domain=cs9.wac.phicdn.net) has some related subdomains

**Comment by crazy-max** [comment]
@mscreenie Those adresses have not been probed and the domain `phicdn.net` seems linked to Verizon. Please next time follow the [SUPPORT guide](Those adresses have not benn probed) to get more details. Thanks
