### ISSUE TITLE
HostsMan url is down

### ISSUE THREAD

**Issue by divinity76** [crazy-max/WindowsSpyBlocker#91]
the HostsMan url on https://github.com/crazy-max/WindowsSpyBlocker/wiki/dataHosts is down.

**Comment by Atavic** [comment]
Works here, maybe 3rd parties are blocking it?

**Comment by crazy-max** [comment]
Hi @divinity76,

Yes indeed, the [official](http://www.abelhadigital.com/hostsman) website [seems down](http://www.isitdownrightnow.com/abelhadigital.com.html) but is available with the WayBackMachine : https://web.archive.org/web/20171116044202/http://www.abelhadigital.com/hostsman

**Comment by divinity76** [comment]
@Atavic really? what DNS are you using? 

> $ nslookup www.abelhadigital.com
> Server:  google-public-dns-a.google.com
> Address:  8.8.8.8
> 
> *** google-public-dns-a.google.com can't find www.abelhadigital.com: Server failed

**Comment by Atavic** [comment]
Y a n d e x

Site's up.

**Comment by crazy-max** [comment]
Releases url : http://hostsman2.it-mate.co.uk/

**Comment by divinity76** [comment]
huh, you're right.

> $ nslookup www.abelhadigital.com 77.88.8.8
> Server:  dns.yandex.ru
> Address:  77.88.8.8
> 
> Non-authoritative answer:
> Name:    ghs.google.com
> Addresses:  2a00:1450:4010:c0a::79
>           173.194.73.121
> Aliases:  www.abelhadigital.com

@crazy-max well, the site is up depending on what DNS you use. (works on Yandex DNS, does not work on GoogleDNS)
