### ISSUE TITLE
IPs blocking Windows Update and Store updates in Windows 10 RS3

### ISSUE THREAD

**Issue by Ainatar** [crazy-max/WindowsSpyBlocker#92]
Hi,
the next recently added IPs are blocking Windows Update and Store updates in Windows 10 RS3 (in Europe at least):

IPs from (data/firewall/win10/spy.txt)
13.68.87.175 #sls.update.microsoft.com
13.74.179.117 #sls.update.microsoft.com
13.78.230.134 #sls.update.microsoft.com
52.229.171.202 #sls.update.microsoft.com

Keep the good job, your repository is the best!

**Comment by crazy-max** [comment]
Hi @Ainatar 

I will investigate on this and thanks for your support 😉

**Comment by crazy-max** [comment]
According to threatcrowd, urlscan, packettotal and telemetry collected through WSB :

* 13.68.87.* > sls.update.microsoft.com (Norwalk)
* 13.74.179.* > sls.update.microsoft.com (Hong Kong)
* 13.78.230.134 > not affiliate to update proto
* 52.229.171.* > sls.update.microsoft.com (Hong Kong)

Can you only remove 13.68.87.175, 13.74.179.117, 52.229.171.202 and check again plz ?

**Comment by skipik** [comment]
WU doesn't work for me either after the latest WSB update.

**Comment by crazy-max** [comment]
A fix will be available today. Other IPs are involved. I keep you in touch.

**Comment by crazy-max** [comment]
Check the latest release ;)

**Comment by skipik** [comment]
Fixed. Thanks! :-)
