### ISSUE TITLE
Please provide evidence that the domains/IP's collecting data 

### ISSUE THREAD

**Issue by CHEF-KOCH** [crazy-max/WindowsSpyBlocker#93]
Hello, I'm watching this project since day one and I have serious doubts that most of these IP's or domains really submitting private data, some of them do, others don't and some never gets called unless you use specific windows versions, apps and gpedit.msc rules.

It's questionable what are the benefits of blocking domains when dnsapi.dll hard-coded several (here listed domains, like e.g. bing) which even bypasses IPSec rules due the nature of windows own DNS mechanism (svchost.exe aka DNSCache). 

The project states that you can capture the traffic but that's not a proof in any way that these connections are done to track/spy or to collect sensitive data, most data are encrypted and I have serious doubts that someone can decrypt hundreds of connections in a short time to inspect what's really going on in there. I'm not saying the project is a hoax but even for me it's difficult to analyse 50 IP's per week and I'm really long in this business. 

Some connections are made to synchronize the time, others to validate certificates or to check for Windows updates. Another problem is that Microsoft just could release another update to include more checks e.g. when an app update is downloaded/installed which might connect to 3rd-party advertisers.These connections are done by Explorer.exe.

Some issue here in this project e.g. want to block SpyNet which is a part of [Windows Defender protection mechanism](https://en.wikipedia.org/wiki/Microsoft_Active_Protection_Service), whenever you disable WD there will never ever a connection to or from it, so again I have my doubts about this because blocking legit things like this ends up with reducing the overall security and does not improve it, this must be analysed by experts and not by beginners beause just because there are connections doesn't automatically mean that this is abused. Analysing and collecting data is one thing but understanding and interpreting them correctly another.

It should also somewhat mentioned that most the important connections are made in only four conditions 1) When you install/activate the OS 2) When you update the OS 3) When you install/Update apps and 4) When there are programs/task scheduler active which do what there designed to do, executing xyz program. However, as mentioned earlier some of this is not blockable via DNS or HOSTS file and this should be mentioned. Also together with the fact that Microsoft official explains which data are been collected, the only thing what they don't explain is on which IP/Domain that behaviour is, but that's in my opinion more to avoid more harm, e.g. if you block the Windows activation you not need to wonder that you get an error. Each Windows build also handles these things differently, that's the reason why MS provides a telemetry guide for each major release.

From my own tests I can say that the most important/critical connections are done while you install and activating the OS because it collects your MAC address, your IP among other private things, but that's not a secret and documented since years. Theoretically it would be more practically to work with a whitelist instead of a blacklist if someone really wants a 'spy blocker'(whatever that means) because working with a blacklist is working against a windmill - hopeless and useless. That is all somehow not really mentioned and people which aren't experts might see this program or collection here as 'universal' tool because the name is misleading and it's really questionable if the connections not anyway getting bypassed or really transmitting 'spying' related things. There are is except my article on an older OS no proof in the entire internet and as said in meantime MS has change a lot which makes it pointless to talk about because no one should use unsupported builds anymore.

**What I suggest is**
============
* A page which explains what this tool is and what it's not
* Some explanation or rules to identify what spying is and how to search for spying 
* Clarification which connections are not harmful (e.g. because of activation, time-sync,...)
* Explanation how to work with a whitelist instead of a blacklist, especially if you work with programs which altering DNS, e.g. Unbound can block specific ranges or interfaces and allowing anyone to work with only specific pre-set of rules or instead you could use ASN-blocking to exclude several companys. 

**Resource**
* https://blogs.windows.com/windowsexperience/2017/04/05/windows-10-privacy-journey-continues-more-transparency-and-controls-for-you/#xoczYDMPIxzxl4QG.97
* https://docs.microsoft.com/en-us/windows/configure/basic-level-windows-diagnostic-events-and-fields
* https://docs.microsoft.com/en-us/windows/configuration/configure-windows-telemetry-in-your-organization
* https://technet.microsoft.com/en-us/library/ff793409.aspx
* https://en.wikipedia.org/wiki/Microsoft_Product_Activation
* https://redmondmag.com/articles/2010/07/01/what-does-microsoft-know-about-you.aspx
* https://en.wikipedia.org/wiki/Deep_packet_inspection
* https://en.wikipedia.org/wiki/Net_neutrality (Quality of service, ..)

Edit:
I shouldn't write comments after 27 hours without sleep. Comment edited ...

**Comment by crazy-max** [comment]
Hi @CHEF-KOCH, thanks for this diagnosis. I will explain the process behind WSB to collect data asap and include it in the wiki. Thanks

**Comment by Atavic** [comment]
We have substantial evidence:

- https://gist.github.com/bluehat/76a07a5d25f038a89f3b99c54a9a94a9#known-compromised-systems

Also: https://github.com/crazy-max/WindowsSpyBlocker/issues/35#issuecomment-292642256

**Comment by CHEF-KOCH** [comment]
That's not evidence that's again only EULA, this is however not new in any way and doused times listed. Evidence would be to clarify what exactly spying includes and what is already explained, I think my original post covered already all of it. 

I guess I will do another example wireshark/Burp inspection myself to debunk some myths with Redstone 4 when I have enough time, people should't forget that MS changes EULA + the OS and because it might was there doesn't mean automatically that this is still there, I have my doubts that MS gets punished by EU to pay millions over millions and no one checked if it simply submits things, that's easily done in 5 min with Fiddler. The remaining question is, what is exactly submitted and is it that what MS really say or is it really 'spying'.
Most of the mentioned IP's never getting called unless the mentioned conditions are activated and even then there is a difference between several Windows versions like G, S, Pro and Enterprise.

**Comment by Atavic** [comment]
OK, we had evidence. My ISP will look at me and DNS requests will be monitored; but I don't want the doubt that an OS looking at my activities. I don't need Cortana to map where I buy products from.

**Comment by Atavic** [comment]
NSA [Word Games Explained](https://www.eff.org/deeplinks/2013/06/director-national-intelligences-word-games-explained-how-government-deceived):

- *Collecting* is the active intervention of humans on previously harvested data-sets. To "collect" means to "show intercepts to humans".

- *Data Mining* is the goliath giant known as Prism that intercepts plain unencrypted and most encrypted data. These intercepts are automated and that's not considered as "collecting".

By following the NSA wordgame, most of the EULA we agreed to (like M$ one) assume different meanings.

*thanks to mirimir (Wilderssecurity)*

**Comment by beerisgood** [comment]
@Atavic you know you can disable Cortana dont you? Or Block in Firewall or do both.
If you dont allow it, it doesnt collect Data. Yes its still running but thats because its integrated into Windows start menu

**Comment by Atavic** [comment]
Too much is running at System Privilege, higher than Administrator.

**Comment by beerisgood** [comment]
@Atavic relevant to what?

**Comment by Atavic** [comment]
In Windows 10 too many services run at system level. Connections start at system level. You disable services and they are enabled after an update.

**Comment by CHEF-KOCH** [comment]
Please do not abuse my threads with discussion like this, I have a [discord channel here](https://discordapp.com/invite/NqyTbh), you can talk all day long about such things in this channel but GitHub is not the right place for forum talk like that.

That Windows needs an upper layer for recovery, upgrades and to maintain certain things has nothing to do with my initial post, this is btw in every OS and not exclusive in Windows.

Thanks.

**Comment by crazy-max** [comment]
In the latest release I did a review of all IPs. As you say, some of them are attributed to operations dedicated to running Windows itself, while others are used for telemetry.

I have isolated some IPs according to the Windows services used and I have also reviewed the types of requests made (DNS, MDNS, HTTP, SSDP, etc...) so that they are sorted in the three proposed lists (extra, spy, update). I rarely analyze the content of packages because the number of requests is quite huge over a month of analysis. For IP addresses, I first look at whether this one is attached to a Microsoft domain and also what kind of requests it makes. Since Microsoft has quite a few ranges of IP addresses, it often happens that a domain is not attached to a fixed IP address but changes over time. This is why in the `logs` folder of the repository, you can find the tracking of IP addresses in the `firewall.csv` files.

As far as blocking via hard-coding in dll `dnsapi.dll` is concerned, I had already mentioned this before and that's why I had advised to use either one's own router as a firewall or tools like pi-hole.

In the latest version (4.11.0) I have taken into account time traffic, Certificate Authority related traffic and other legitimate services. As for 3rd party advertisers that are not related to Microsoft they are excluded from my analysis. Especially CDN services like Akamai.

For Windows Defender, SpyNet is generally used to provide analysis samples. Windows Defender updates are anyway provided by Windows Update so I don't see why this kind of traffic is needed for an antivirus.

The most important and critical data connections and uploads are made during OS installation, activation and updates you're right. That's why again I recommend having a firewall upstream.

I will be working on a new way to deploy WSB that would be more flexible and understandable for the user and also provide a more detailed level of explanation than today. For that I plan to set up a website for the application.

I hope it meets your expectations. If you have any further questions, please do not hesitate and thank you for your support and criticism.

**Comment by Atavic** [comment]
>.m1-msedge.net TLSv1.2 Used by OfficeHub to get the metadata of Office apps.
.search.msn.com TLSv1.2 Used to retrieve Windows Spotlight metadata.

[gist](https://gist.github.com/Atavic/c6413717d9c9798e2cd906e68d937361)

From the Docs linked [here](https://github.com/crazy-max/WindowsSpyBlocker/issues/104#issuecomment-372157124).

**Comment by CHEF-KOCH** [comment]
Not bad your gist, sadly it doesn't answers the question which domains are delivering possible meta-data directly to MS which is formerly known as telemetry what exactly is delivered and which options triggering which telemetry. I think I have to do this on my own to provide some pcaps otherwise all of it is only speculation because what MS said could be different from what actually will be delivered, remember that MS changes monthly something in the OS and this article is written a while back. Redstone 4 also reduces a lot of telemetry + there providing toggles to take (more) control over it.

I think most of these connections are pretty much okay (the ones Microsoft explains) cause there never triggered in case certain conditions are present, bing never gets called when Cortana or any app is actually running. So that's definitely not telemetry related because it's simply a part of how these apps are working.

The apps part is also from my experience different, cause you can uninstall them, I categories the OS 'telemetry' as the important one because you can't fully opt-out of it even in Redstone 4. 

My exceptions was that someone really provide an pcap which can be opened with Burp/Whireshark & co. to check if MS really holds what they promise, analyze the traffic to come to real conclusions, the project here is more to avoid any outgoing connections (not telemetry) and that's in my opinion not necessary unless someone proves that the same connections are done even if you uninstall the apps which causing them - which is still unproven as of today.

I think when I release my own findings, everyone could pickup my pcaps and check what I say is true or not and if MS really collect as much as people always complain about which I really doubt. It's also questionable what exactly these 'metadata' contain, if there contain as the same as you would normally use a normal search engine then I would not understand the entire discussion at all because you simply can't provide something useful without meta-data cause there is no protocol which doesn't leak any meta-data and at some point the service you like to use also needs some information in order to provide results or protect themselves or you against attacks like DOS & co.

So no, the answer is not what I'm looking for, but I already gave up in every projects which has something to do with telemetry because everything is just plain guessing without any proof and I also not understand why the big ones like EFF and Co. not provide something for their claims maybe because this takes month to archive because inspecting one single domain takes one or more domain to come to an conclusion which is really helpful.
