### ISSUE TITLE
Can't get KB4056892 while using Windows 10 spy list

### ISSUE THREAD

**Issue by skipik** [crazy-max/WindowsSpyBlocker#94]
I couldn't update to OS Build 16299.192. WU shows me that "you are up to date" and nothing found. But when I deleted everything from dnsmasq.conf and firewall.user it immediately found a new update - that was KB4056892.

**Comment by Atavic** [comment]
Simply download standalone installer and install it by yourself:

- x64

http://download.windowsupdate.com/c/msdownload/update/software/secu/2018/01/windows10.0-kb4056892-x64_a41a378cf9ae609152b505c40e691ca1228e28ea.msu

- x32

http://download.windowsupdate.com/d/msdownload/update/software/secu/2018/01/windows10.0-kb4056892-x86_d3aaf1048d6f314240b8c6fe27932aa52a5e6733.msu

[But several tools are available to update offline](https://github.com/crazy-max/WindowsSpyBlocker/wiki/miscFAQ#couldnt-connect-to-the-update-service)

**Comment by skipik** [comment]
It's just a workaround. Spy list shouln't block any updates. We have separate list fot that. :-)

**Comment by Atavic** [comment]
:+1: You're right, I didn't read that you had spy list only.

**Comment by crazy-max** [comment]
Hi @skipik, i keep u in touch asap. Thx

**Comment by crazy-max** [comment]
I'm closing this issue. Do not hesitate to reopen it if you still encounter this problem.

**Comment by r-a-y** [comment]
FWIW, I also encountered this.

**Comment by skipik** [comment]
Yeah, the problem is still reproducible.

**Comment by crazy-max** [comment]
@r-a-y @skipik Do you have an antivirus ? Maybe it's an issue related to [this thread](https://support.microsoft.com/en-us/help/4072699/january-3-2018-windows-security-updates-and-antivirus-software).

**Comment by skipik** [comment]
@crazy-max Yeah, I have Kaspersky 2018, but it doesn't matter, cus its completely compatible with that Windows Update.
Also I already wrote this - "But when I deleted everything from dnsmasq.conf and firewall.user it immediately found a new update - that was KB4056892."

**Comment by crazy-max** [comment]
@skipik Ok thanks, i have spotted these ips that could mess with this update : `13.78.230.134` and `13.79.239.69`. Can you remove them and check if it works ?

**Comment by skipik** [comment]
@crazy-max Looks like it works now, yeah. I just got (KB4058258) OS Build 16299.214 on a machine which had OS Build 16299.192 before that. I couldn't find any updates before I removed those 2 rules, so 99% that it fix the problem. :-)

**Comment by crazy-max** [comment]
Ok I will make an update asap

**Comment by crazy-max** [comment]
Available in the latest release, thanks for your input guys!
