### ISSUE TITLE
microsoft patched win10 updates to ignore the hosts file?

### ISSUE THREAD

**Issue by divinity76** [crazy-max/WindowsSpyBlocker#95]
i have `0.0.0.0 a-0003.a-msedge.net` in the hosts file , and have had it since boot, yet svchosts.exe is downloading from a-0003.a-msedge.net at 1.2Mbps, according to process explorer... that's weird, anyone know anything about this?

**Comment by RomelSan** [comment]
is it resolving via IPv6?
if so then you should have:
0.0.0.0 a-0003.a-msedge.net
0:0:0:0:0:0:0:0 a-0003.a-msedge.net

**Comment by divinity76** [comment]
that may be it! thanks

but i won't be able to test it before tuesday

**Comment by crazy-max** [comment]
@divinity76 Any news about your issue ?

**Comment by divinity76** [comment]
@crazy-max yeah, adding the ipv6 blocks seems to have fixed it, i can no longer reproduce the issue :+1: 

thanks

**Comment by divinity76** [comment]
@RomelSan  @crazy-max yeah, adding the ipv6 blocks seems to have fixed it, i can no longer reproduce the issue :+1: 

thanks
