### ISSUE TITLE
Bitdefender Issues

### ISSUE THREAD

**Issue by BlueScreenBuddy** [crazy-max/WindowsSpyBlocker#96]
Bitdefender Total Security 2018 nuked the executable. Had to exclude it.

**Comment by beerisgood** [comment]
You need contact bitdefender then

**Comment by BlueScreenBuddy** [comment]
No I don't need to contact them. The developer would have to. I didn't make the app.

**Comment by crazy-max** [comment]
Hi @BlueScreenBuddy, the [VirusTotal analysis](https://www.virustotal.com/#/file/8023646b661b0925e72b2f4110a02fab3142bc0ec81f37d0f3ad2be164072eb9/detection) did not report any issue with Bitdefender. Are your definitions up to date ?
And before reporting an issue, please read and apply the [SUPPORT page](https://github.com/crazy-max/WindowsSpyBlocker/blob/master/.github/SUPPORT.md), it will help both of us!
Specially the [FAQ](https://github.com/crazy-max/WindowsSpyBlocker/wiki/miscFAQ#antivirus-complains-about-windowsspyblocker)... ;) Thanks

**Comment by stamepicmorg** [comment]
>  VirusTotal analysis did not report any issue with Bitdefender.

![66](https://user-images.githubusercontent.com/1307229/35471120-54ca41d8-0366-11e8-8582-398aa7a0fb1b.png)

**Comment by crazy-max** [comment]
I have sent the exe to Bitdefender. They tell me it's a false positive and they have uptaded their signature database. I have made a new VirusTotal scan and now it's ok : https://www.virustotal.com/#/file/8023646b661b0925e72b2f4110a02fab3142bc0ec81f37d0f3ad2be164072eb9/detection
