### ISSUE TITLE
How to compile it in Windows 10 

### ISSUE THREAD

**Issue by merlinnusr** [crazy-max/WindowsSpyBlocker#97]
I am trying to compile WindowsSpyBlocker but I receive this error

> main.go:11:2: cannot find package "github.com/crazy-max/WindowsSpyBlocker/app/cmds/dev" in any of:
>         C:\Go\src\github.com\crazy-max\WindowsSpyBlocker\app\cmds\dev (from $GOROOT)
>         C:\Users\moe\go\src\github.com\crazy-max\WindowsSpyBlocker\app\cmds\dev (from $GOPATH)
> main.go:12:2: cannot find package "github.com/crazy-max/WindowsSpyBlocker/app/cmds/telemetry" in any of:
>         C:\Go\src\github.com\crazy-max\WindowsSpyBlocker\app\cmds\telemetry (from $GOROOT)
>         C:\Users\moe\go\src\github.com\crazy-max\WindowsSpyBlocker\app\cmds\telemetry (from $GOPATH)
> main.go:13:2: cannot find package "github.com/crazy-max/WindowsSpyBlocker/app/menu" in any of:
>         C:\Go\src\github.com\crazy-max\WindowsSpyBlocker\app\menu (from $GOROOT)
>         C:\Users\moe\go\src\github.com\crazy-max\WindowsSpyBlocker\app\menu (from $GOPATH)
> main.go:14:2: cannot find package "github.com/crazy-max/WindowsSpyBlocker/app/utils/app" in any of:
>         C:\Go\src\github.com\crazy-max\WindowsSpyBlocker\app\utils\app (from $GOROOT)
>         C:\Users\moe\go\src\github.com\crazy-max\WindowsSpyBlocker\app\utils\app (from $GOPATH)
> main.go:15:2: cannot find package "github.com/crazy-max/WindowsSpyBlocker/app/utils/config" in any of:
>         C:\Go\src\github.com\crazy-max\WindowsSpyBlocker\app\utils\config (from $GOROOT)
>         C:\Users\moe\go\src\github.com\crazy-max\WindowsSpyBlocker\app\utils\config (from $GOPATH)
> main.go:16:2: cannot find package "github.com/crazy-max/WindowsSpyBlocker/app/utils/windows" in any of:
>         C:\Go\src\github.com\crazy-max\WindowsSpyBlocker\app\utils\windows (from $GOROOT)
>         C:\Users\moe\go\src\github.com\crazy-max\WindowsSpyBlocker\app\utils\windows (from $GOPATH)
> main.go:17:2: cannot find package "github.com/fatih/color" in any of:
>         C:\Go\src\github.com\fatih\color (from $GOROOT)
>         C:\Users\moe\go\src\github.com\fatih\color (from $GOPATH)
> main.go:18:2: cannot find package "github.com/mcuadros/go-version" in any of:
>         C:\Go\src\github.com\mcuadros\go-version (from $GOROOT)
>         C:\Users\moe\go\src\github.com\mcuadros\go-version (from $GOPATH)
>

**Comment by crazy-max** [comment]
Hi @merlinnusr,

What command do you type ?
What is your Go version ?
What is your Windows platform ?

Thanks

**Comment by merlinnusr** [comment]
ok

**Comment by crazy-max** [comment]
Ok, can you type `go env && pwd` in the location where you type `go build` and give me the output ?

And for your information, you have to download [godep](https://github.com/tools/godep) package first to grab all dependencies : `go get -v github.com/golang/dep/...` and download the deps with : `dep ensure -v` (type this in WindowsSpyBlocker root folder).
